// Copyright (c) 2011 CZ.NIC z.s.p.o. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// blame: jnml, labs.nic.cz

// WARNING: If this file is parser.go then DO NOT EDIT.
// parser.go is generated by goyacc from parser.y (see the Makefile).

package zone

import (
	"fmt"
	"github.com/cznic/dns"
	"github.com/cznic/dns/rr"
	"github.com/cznic/strutil"
	"math"
	"net"
)

type rrHead struct {
	ttl   int32
	class rr.Class
}

type yySymType struct {
	yys    int
	alg    rr.AlgorithmType
	class  rr.Class
	data   []byte
	str    string
	u64    uint64
	int    int
	float  float64
	uint   uint
	ip     net.IP
	rrh    rrHead
	rrData dns.Wirer
	rr     *rr.RR
	typ    rr.Type
	types  []rr.Type
	strs   []string
}

const tA = 57346
const tA6 = 57347
const tAAAA = 57348
const tAFSDB = 57349
const tAPL = 57350
const tATMA = 57351
const tBACKSLASH_HASH = 57352
const tBLANK_START = 57353
const tCDS = 57354
const tCERT = 57355
const tCNAME = 57356
const tDHCID = 57357
const tDLR_TTL = 57358
const tDNAME = 57359
const tDNSKEY = 57360
const tDNS_PORT = 57361
const tDS = 57362
const tEID = 57363
const tGID = 57364
const tGPOS = 57365
const tHINFO = 57366
const tHIP = 57367
const tIPSECKEY = 57368
const tISDN = 57369
const tKEY = 57370
const tKX = 57371
const tLOC = 57372
const tMB = 57373
const tMD = 57374
const tMF = 57375
const tMG = 57376
const tMINFO = 57377
const tMR = 57378
const tMX = 57379
const tNAPTR = 57380
const tNIMLOC = 57381
const tNINFO = 57382
const tNS = 57383
const tNSAP = 57384
const tNSAP_PTR = 57385
const tNSEC = 57386
const tNSEC3 = 57387
const tNSEC3PARAM = 57388
const tNULL = 57389
const tNXT = 57390
const tPTR = 57391
const tPX = 57392
const tRKEY = 57393
const tRP = 57394
const tRRSIG = 57395
const tRT = 57396
const tSIG = 57397
const tSMTP_PORT = 57398
const tSOA = 57399
const tSPF = 57400
const tSRV = 57401
const tSSHFP = 57402
const tTA = 57403
const tTALINK = 57404
const tTCP_PROTO = 57405
const tTKEY = 57406
const tTSIG = 57407
const tTXT = 57408
const tUDP_PROTO = 57409
const tUID = 57410
const tUINFO = 57411
const tUNSPEC = 57412
const tWKS = 57413
const tX25 = 57414
const tTYPE_X = 57415
const tDLV = 57416
const tHEX = 57417
const t0xHEX = 57418
const tBASE32EXT = 57419
const tBASE64 = 57420
const tDOMAIN_NAME = 57421
const tDOMAIN_NAME2 = 57422
const tSRV_DOMAIN = 57423
const tQSTR = 57424
const tFLOAT = 57425
const tCLASS = 57426
const tIPV4 = 57427
const tIPV6 = 57428
const tDECADIC = 57429

var yyToknames = []string{
	"tA",
	"tA6",
	"tAAAA",
	"tAFSDB",
	"tAPL",
	"tATMA",
	"tBACKSLASH_HASH",
	"tBLANK_START",
	"tCDS",
	"tCERT",
	"tCNAME",
	"tDHCID",
	"tDLR_TTL",
	"tDNAME",
	"tDNSKEY",
	"tDNS_PORT",
	"tDS",
	"tEID",
	"tGID",
	"tGPOS",
	"tHINFO",
	"tHIP",
	"tIPSECKEY",
	"tISDN",
	"tKEY",
	"tKX",
	"tLOC",
	"tMB",
	"tMD",
	"tMF",
	"tMG",
	"tMINFO",
	"tMR",
	"tMX",
	"tNAPTR",
	"tNIMLOC",
	"tNINFO",
	"tNS",
	"tNSAP",
	"tNSAP_PTR",
	"tNSEC",
	"tNSEC3",
	"tNSEC3PARAM",
	"tNULL",
	"tNXT",
	"tPTR",
	"tPX",
	"tRKEY",
	"tRP",
	"tRRSIG",
	"tRT",
	"tSIG",
	"tSMTP_PORT",
	"tSOA",
	"tSPF",
	"tSRV",
	"tSSHFP",
	"tTA",
	"tTALINK",
	"tTCP_PROTO",
	"tTKEY",
	"tTSIG",
	"tTXT",
	"tUDP_PROTO",
	"tUID",
	"tUINFO",
	"tUNSPEC",
	"tWKS",
	"tX25",
	"tTYPE_X",
	"tDLV",
	"tHEX",
	"t0xHEX",
	"tBASE32EXT",
	"tBASE64",
	"tDOMAIN_NAME",
	"tDOMAIN_NAME2",
	"tSRV_DOMAIN",
	"tQSTR",
	"tFLOAT",
	"tCLASS",
	"tIPV4",
	"tIPV6",
	"tDECADIC",
}
var yyStatenames = []string{}

const yyEofCode = 1
const yyErrCode = 2
const yyMaxDepth = 200

var yyExca = []int{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 334,
	75, 36,
	-2, 40,
	-1, 354,
	1, 118,
	11, 118,
	16, 118,
	79, 118,
	88, 118,
	90, 118,
	-2, 194,
	-1, 378,
	75, 36,
	-2, 41,
	-1, 442,
	1, 121,
	11, 121,
	16, 121,
	79, 121,
	88, 121,
	90, 121,
	-2, 194,
}

const yyNprod = 308
const yyPrivate = 57344

var yyTokenNames []string
var yyStates []string

const yyLast = 455

var yyAct = []int{

	126, 354, 403, 356, 423, 414, 343, 14, 15, 131,
	311, 301, 165, 392, 393, 348, 349, 308, 309, 415,
	20, 137, 302, 395, 329, 390, 388, 135, 136, 119,
	404, 134, 221, 222, 223, 224, 226, 225, 355, 132,
	227, 228, 229, 230, 21, 232, 233, 16, 234, 235,
	236, 237, 238, 240, 241, 242, 243, 244, 245, 246,
	247, 248, 425, 239, 249, 250, 251, 252, 253, 254,
	255, 256, 257, 258, 259, 262, 261, 263, 264, 266,
	267, 265, 268, 269, 189, 270, 271, 272, 273, 260,
	274, 138, 275, 276, 277, 184, 278, 279, 280, 281,
	282, 283, 231, 344, 179, 183, 160, 6, 163, 16,
	295, 178, 4, 118, 367, 328, 290, 420, 396, 353,
	287, 293, 291, 175, 171, 169, 437, 173, 450, 449,
	441, 428, 400, 180, 181, 191, 192, 193, 194, 186,
	362, 360, 352, 190, 341, 335, 325, 321, 313, 196,
	286, 218, 216, 211, 188, 210, 208, 205, 206, 207,
	204, 195, 203, 202, 199, 201, 200, 187, 217, 182,
	408, 407, 284, 185, 433, 5, 288, 212, 213, 209,
	371, 374, 294, 440, 3, 375, 7, 297, 215, 11,
	289, 299, 120, 292, 2, 438, 8, 13, 410, 296,
	17, 373, 332, 174, 406, 170, 168, 304, 172, 300,
	167, 405, 166, 303, 364, 164, 447, 315, 285, 323,
	439, 310, 312, 162, 161, 319, 446, 219, 334, 177,
	12, 322, 159, 320, 158, 317, 318, 70, 157, 71,
	72, 156, 155, 432, 154, 316, 73, 74, 75, 153,
	77, 78, 152, 79, 151, 150, 109, 110, 111, 117,
	112, 81, 82, 83, 84, 85, 86, 87, 88, 89,
	90, 91, 431, 149, 92, 93, 94, 95, 96, 97,
	98, 314, 99, 100, 148, 101, 102, 103, 104, 147,
	105, 106, 107, 108, 113, 146, 145, 324, 326, 114,
	144, 143, 142, 198, 115, 116, 69, 76, 141, 10,
	9, 336, 327, 305, 139, 340, 345, 331, 176, 333,
	330, 346, 133, 337, 338, 130, 339, 357, 358, 129,
	125, 124, 370, 312, 128, 351, 365, 380, 422, 382,
	298, 384, 123, 122, 359, 361, 121, 363, 1, 412,
	386, 385, 366, 342, 372, 387, 376, 389, 397, 379,
	306, 394, 381, 350, 383, 197, 140, 424, 220, 401,
	429, 402, 369, 127, 19, 18, 68, 67, 66, 65,
	60, 59, 398, 399, 58, 57, 56, 55, 54, 53,
	52, 51, 214, 413, 50, 417, 49, 409, 48, 47,
	46, 45, 44, 411, 43, 419, 427, 426, 42, 41,
	40, 416, 39, 418, 38, 37, 36, 35, 34, 33,
	64, 80, 32, 63, 62, 61, 31, 30, 434, 29,
	436, 435, 28, 27, 442, 26, 25, 24, 23, 445,
	22, 307, 391, 347, 443, 444, 397, 430, 448, 377,
	451, 452, 378, 368, 421,
}
var yyPact = []int{

	96, 96, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 22,
	-1000, -1000, -40, -1000, -1000, -1000, -1000, -1000, -1000, 233,
	29, 22, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 182,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -48, -1000,
	-58, -48, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	43, -1000, 42, -1000, -1000, -1000, 41, -1000, -1000, -1000,
	-1000, 26, 18, -48, -48, 90, -1000, 17, 95, -48,
	88, -3, -1000, -48, -1000, -1000, -1000, -1000, -3, -48,
	-1000, -3, 87, 86, 84, 83, 81, 78, -48, -48,
	77, 103, 76, 74, -3, -3, 178, 73, -48, 72,
	-1000, 28, -48, -1000, 71, 38, -48, -3, 33, 40,
	-3, 39, -48, 38, 25, -1000, -3, -48, -1000, -1000,
	-1000, -48, -1000, -1000, -1000, -1000, -3, -1000, -3, -1000,
	-3, -1000, -1000, -1000, -1000, -3, -1000, -75, -3, -3,
	-1000, -1000, -1000, -1000, 69, -1000, -1000, -48, -1000, -1000,
	-1000, -1000, -3, -3, -1000, -48, -1000, -1000, 68, -3,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -3, 67, -1000, -48, -3,
	32, -1000, -1000, -1000, -3, -1000, -3, -1000, 66, -3,
	-3, -1000, -1000, -3, -1000, 65, 16, 22, -1000, -1000,
	-3, -79, -3, -1000, 63, 37, -50, -48, -48, -1000,
	62, -1000, -3, 61, -3, -1000, -48, -1000, 31, -1000,
	105, -3, 118, -3, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, 16, -63, -64, -83, -1000, -1000, -1000,
	-1000, -66, -1000, 36, -1000, -1000, -1000, -1000, -1000, -1000,
	53, 22, -1000, 22, -57, -1000, -1000, -1000, -1000, 93,
	92, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, 16, -72, -3, -72,
	-3, -1000, -1000, -1000, -1000, -48, 35, -1000, -1000, -1000,
	-1000, -25, -25, -57, -1000, 52, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 97, -25, -1000, -1000, -25, -57, -1000, 46,
	164, 51, -50, -1000, -48, -48, -57, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -57, 50, 49, -1000, -1000,
	-1000, -1000, -1000,
}
var yyPgo = []int{

	0, 11, 454, 0, 453, 24, 452, 449, 447, 7,
	8, 443, 442, 441, 440, 438, 437, 436, 435, 433,
	432, 429, 427, 426, 425, 424, 423, 422, 421, 420,
	419, 418, 417, 416, 415, 414, 412, 410, 409, 408,
	404, 402, 401, 400, 399, 398, 396, 394, 392, 391,
	390, 389, 388, 387, 386, 385, 384, 381, 380, 379,
	378, 377, 376, 189, 375, 374, 373, 372, 12, 370,
	3, 368, 1, 367, 366, 365, 10, 363, 361, 360,
	357, 355, 6, 4, 22, 9, 2, 353, 351, 349,
	348, 194, 346, 343, 342, 340, 338, 334, 332, 331,
	330, 329, 325, 324, 322, 320, 318, 315, 314, 313,
	310, 309, 5, 308, 303, 302, 301, 300, 296, 295,
	289, 284, 281, 273, 272, 255, 254, 252, 249, 245,
	244, 243, 242, 241, 238, 234, 233, 232, 230, 229,
	228, 227, 226, 224, 223, 219, 218, 216, 215, 214,
	212, 211, 210, 208, 206, 205, 204, 203, 202, 201,
	198, 195,
}
var yyR1 = []int{

	0, 90, 90, 92, 14, 93, 15, 94, 95, 16,
	1, 96, 2, 3, 97, 66, 66, 4, 98, 67,
	67, 99, 17, 100, 18, 19, 101, 20, 102, 21,
	103, 22, 104, 23, 73, 83, 105, 5, 6, 6,
	7, 7, 106, 28, 27, 27, 27, 27, 107, 30,
	108, 109, 31, 91, 110, 91, 111, 91, 91, 91,
	32, 87, 87, 88, 88, 89, 89, 82, 81, 81,
	79, 112, 112, 80, 80, 13, 13, 13, 113, 74,
	114, 75, 11, 11, 12, 12, 76, 76, 77, 77,
	78, 78, 115, 33, 116, 34, 117, 35, 118, 36,
	119, 37, 120, 38, 121, 122, 39, 123, 124, 40,
	125, 41, 126, 42, 127, 43, 128, 129, 44, 130,
	131, 45, 132, 46, 133, 47, 48, 48, 134, 49,
	135, 136, 50, 137, 51, 138, 63, 64, 64, 64,
	64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
	64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
	64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
	64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
	64, 64, 64, 64, 139, 140, 64, 65, 65, 65,
	65, 141, 142, 52, 143, 70, 72, 72, 72, 71,
	71, 71, 71, 71, 71, 71, 71, 71, 71, 71,
	71, 71, 71, 71, 71, 71, 71, 71, 71, 71,
	71, 71, 71, 71, 71, 71, 71, 71, 71, 71,
	71, 71, 71, 71, 71, 71, 71, 71, 71, 71,
	71, 71, 71, 71, 71, 71, 71, 71, 71, 71,
	71, 71, 71, 71, 71, 71, 71, 71, 71, 71,
	71, 71, 144, 145, 53, 146, 147, 54, 148, 149,
	55, 56, 150, 151, 57, 152, 58, 153, 59, 9,
	60, 68, 68, 154, 24, 25, 155, 156, 26, 69,
	69, 29, 29, 84, 85, 10, 86, 157, 158, 160,
	61, 159, 159, 161, 161, 8, 8, 62,
}
var yyR2 = []int{

	0, 1, 2, 0, 3, 0, 3, 0, 0, 5,
	1, 0, 2, 2, 0, 2, 2, 1, 0, 2,
	2, 0, 6, 0, 3, 2, 0, 6, 0, 3,
	0, 6, 0, 6, 1, 1, 0, 2, 1, 2,
	0, 1, 0, 5, 3, 3, 3, 3, 0, 6,
	0, 0, 5, 1, 0, 3, 0, 3, 2, 2,
	5, 0, 2, 0, 2, 0, 1, 3, 0, 2,
	4, 0, 1, 0, 2, 0, 1, 1, 0, 4,
	0, 4, 1, 1, 1, 1, 0, 2, 0, 2,
	0, 2, 0, 3, 0, 3, 0, 3, 0, 3,
	0, 4, 0, 3, 0, 0, 5, 0, 0, 9,
	0, 3, 0, 3, 0, 3, 0, 0, 5, 0,
	0, 9, 0, 6, 0, 3, 3, 1, 0, 3,
	0, 0, 6, 0, 4, 0, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 0, 0, 7, 2, 2, 1,
	1, 0, 0, 12, 0, 2, 1, 1, 2, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 0, 0, 5, 0, 0, 12, 0, 0,
	10, 2, 0, 0, 7, 0, 5, 0, 6, 1,
	2, 0, 2, 0, 5, 3, 0, 0, 7, 0,
	2, 2, 3, 1, 1, 1, 1, 0, 0, 0,
	7, 1, 1, 1, 1, 0, 2, 2,
}
var yyChk = []int{

	-1000, -90, -91, 88, 16, 79, 11, 90, -91, -110,
	-111, -63, -138, -63, -9, -10, 87, -63, -64, -65,
	-9, 84, -14, -15, -16, -17, -18, -19, -20, -21,
	-22, -23, -27, -30, -31, -32, -33, -34, -35, -36,
	-37, -38, -39, -40, -41, -42, -43, -44, -45, -46,
	-47, -49, -50, -51, -52, -53, -54, -55, -56, -57,
	-58, -24, -25, -26, -29, -59, -60, -61, -62, 73,
	4, 6, 7, 13, 14, 15, 74, 17, 18, 20,
	-28, 28, 29, 30, 31, 32, 33, 34, 35, 36,
	37, 38, 41, 42, 43, 44, 45, 46, 47, 49,
	50, 52, 53, 54, 55, 57, 58, 59, 60, 23,
	24, 25, 27, 61, 66, 71, 72, 26, 84, -9,
	10, -92, -93, -94, -99, -100, -3, -66, -97, -101,
	-102, -85, 87, -104, 89, 85, 86, 79, -85, -108,
	-74, -113, -115, -116, -117, -118, -119, -120, -121, -123,
	-125, -126, -127, -128, -130, -132, -133, -134, -135, -137,
	-70, -143, -144, -70, -148, -68, -150, -152, -154, 82,
	-155, 82, -153, -68, -157, 82, -106, -139, 85, 86,
	-85, -85, 79, 88, 78, 78, -85, 79, -84, 87,
	-85, -3, -3, -3, -3, -84, -85, -75, -114, -84,
	79, 79, 79, 79, 79, 79, -85, -85, 79, 76,
	79, 79, -84, -84, -48, 10, 79, -85, 79, -141,
	-71, 4, 5, 6, 7, 9, 8, 12, 13, 14,
	15, 74, 17, 18, 20, 21, 22, 23, 24, 35,
	25, 26, 27, 28, 29, 30, 31, 32, 33, 36,
	37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
	61, 48, 47, 49, 50, 53, 51, 52, 54, 55,
	57, 58, 59, 60, 62, 64, 65, 66, 68, 69,
	70, 71, 72, 73, -85, -146, 79, 82, -85, -84,
	83, 82, -84, 82, -85, 85, -84, -85, -95, -85,
	-84, -1, -84, -84, -1, -109, -79, -13, 92, 93,
	-84, -76, -84, 79, -122, -85, -129, -84, -84, -85,
	-136, 79, -1, -145, -1, 79, -85, -84, 83, -5,
	-105, -84, -158, -84, -140, 79, -1, -84, -103, -84,
	-107, 79, -87, -82, 87, -10, -76, -11, 94, 95,
	-77, -84, 79, 82, -72, 88, -70, -85, -85, -5,
	79, -84, 79, -84, -149, -85, -5, 83, -4, -67,
	-98, 75, -84, -159, 63, 67, -84, -7, -6, -5,
	-3, -5, -3, -5, -3, -88, -82, -81, 89, -80,
	89, -12, 96, 97, -78, 89, 82, -70, -5, -5,
	79, -9, -9, -86, 87, -151, -156, 78, 78, -5,
	-160, -5, -89, -82, -112, 91, -84, -112, -84, -85,
	82, -2, -96, -83, -73, 87, -83, -86, 79, -69,
	-8, -124, -131, 77, -83, -83, -86, 80, -161, 56,
	19, 79, -72, -85, -85, -86, -142, -147, -86, 79,
	79, -3, -3,
}
var yyDef = []int{

	0, -2, 1, 53, 54, 56, 135, 135, 2, 0,
	135, 58, 0, 59, 55, 279, 295, 57, 136, 0,
	189, 190, 137, 138, 139, 140, 141, 142, 143, 144,
	145, 146, 147, 148, 149, 150, 151, 152, 153, 154,
	155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
	165, 166, 167, 168, 169, 170, 171, 172, 173, 174,
	175, 176, 177, 178, 179, 180, 181, 182, 183, 0,
	3, 5, 7, 21, 23, 14, 26, 28, 0, 32,
	0, 0, 50, 78, 92, 94, 96, 98, 100, 102,
	104, 107, 110, 112, 114, 116, 119, 122, 124, 128,
	130, 133, 194, 262, 194, 268, 281, 272, 275, 283,
	0, 286, 0, 277, 281, 297, 0, 42, 187, 188,
	184, 0, 0, 0, 0, 0, 25, 0, 0, 0,
	0, 0, 294, 0, 14, 14, 14, 14, 0, 0,
	80, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	191, 0, 0, 265, 0, 271, 0, 0, 0, 0,
	0, 291, 0, 280, 0, 307, 0, 0, 4, 6,
	8, 0, 24, 13, 16, 15, 0, 29, 0, 293,
	0, 44, 45, 46, 47, 0, 51, 75, 0, 86,
	93, 95, 97, 99, 0, 103, 105, 0, 111, 113,
	115, 117, 0, 0, 125, 127, 129, 131, 0, 0,
	195, 199, 200, 201, 202, 203, 204, 205, 206, 207,
	208, 209, 210, 211, 212, 213, 214, 215, 216, 217,
	218, 219, 220, 221, 222, 223, 224, 225, 226, 227,
	228, 229, 230, 231, 232, 233, 234, 235, 236, 237,
	238, 239, 240, 241, 242, 243, 244, 245, 246, 247,
	248, 249, 250, 251, 252, 253, 254, 255, 256, 257,
	258, 259, 260, 261, 263, 0, 0, 282, 0, 0,
	0, 285, 36, 292, 0, 298, 0, 185, 0, 0,
	0, 30, 10, 0, 48, 0, 61, 0, 76, 77,
	86, 0, 88, 101, 0, 0, 194, 0, 0, 36,
	0, 134, 0, 0, 0, 269, 0, 36, 0, 18,
	0, 0, 0, 0, -2, 9, 14, 36, 14, 36,
	14, 52, 60, 63, 68, 73, 0, 79, 82, 83,
	87, 90, 106, 0, -2, 196, 197, 36, 36, 126,
	0, 0, 264, 0, 0, 273, 276, 284, 287, 17,
	0, 37, 36, 299, 301, 302, 43, 186, -2, 38,
	22, 27, 31, 33, 49, 62, 65, 71, 0, 71,
	0, 81, 84, 85, 89, 0, 0, 198, 11, 123,
	132, 0, 0, 0, 296, 0, 289, 20, 19, 278,
	305, 39, 64, 66, 67, 72, 69, 70, 74, 91,
	108, 120, 0, 0, 35, 34, 0, 0, 274, 288,
	300, 0, 194, 12, 0, 0, 0, 290, 306, 303,
	304, 109, -2, 192, 266, 0, 0, 0, 270, 14,
	14, 193, 267,
}
var yyTok1 = []int{

	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	88, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 92, 3, 93, 89, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 90, 3, 3, 3, 3, 96,
	3, 3, 3, 3, 3, 3, 3, 3, 94, 3,
	3, 3, 3, 95, 3, 3, 3, 97, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 91,
}
var yyTok2 = []int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
	72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
	82, 83, 84, 85, 86, 87,
}
var yyTok3 = []int{
	0,
}

/*	parser for yacc output	*/

var yyDebug = 0

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c > 0 && c <= len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return fmt.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return fmt.Sprintf("state-%v", s)
}

func yylex1(lex yyLexer, lval *yySymType) int {
	c := 0
	char := lex.Lex(lval)
	if char <= 0 {
		c = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		c = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			c = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		c = yyTok3[i+0]
		if c == char {
			c = yyTok3[i+1]
			goto out
		}
	}

out:
	if c == 0 {
		c = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		fmt.Printf("lex %U %s\n", uint(char), yyTokname(c))
	}
	return c
}

func yyParse(yylex *lex) int {
	var yyn int
	var yylval yySymType
	var yyVAL yySymType
	yyS := make([]yySymType, yyMaxDepth)

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yychar := -1
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		fmt.Printf("char %v in %v\n", yyTokname(yychar), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yychar < 0 {
		yychar = yylex1(yylex, &yylval)
	}
	yyn += yychar
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yychar { /* valid shift */
		yychar = -1
		yyVAL = yylval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yychar < 0 {
			yychar = yylex1(yylex, &yylval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yychar {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error("syntax error")
			Nerrs++
			if yyDebug >= 1 {
				fmt.Printf("%s", yyStatname(yystate))
				fmt.Printf("saw %s\n", yyTokname(yychar))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					fmt.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				fmt.Printf("error recovery discards %s\n", yyTokname(yychar))
			}
			if yychar == yyEofCode {
				goto ret1
			}
			yychar = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		fmt.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 3:
		{
			yylex.begin(sc_IPV4)
		}
	case 4:
		{
			yyVAL.rrData = &rr.A{yyS[yypt-0].ip}
		}
	case 5:
		{
			yylex.begin(sc_IPV6)
		}
	case 6:
		{
			yyVAL.rrData = &rr.AAAA{yyS[yypt-0].ip}
		}
	case 7:
		{
			yylex.begin(sc_NUM)
		}
	case 8:
		{
			yylex.begin(sc_DOMAIN)
		}
	case 9:
		{
			yyVAL.rrData = &rr.AFSDB{uint16(yyS[yypt-2].uint), yyS[yypt-0].str}
		}
	case 10:
		{
			yyVAL.alg = rr.AlgorithmType(yyS[yypt-0].uint)
		}
	case 11:
		{
			yylex.begin(sc_BASE32EXT)
		}
	case 12:
		{
			yylex.begin(sc_INITIAL)
			if data, err := strutil.Base32ExtDecode([]byte(yyS[yypt-0].str)); err != nil {
				yylex.Error(err.Error())
			} else {
				yyVAL.data = data
			}
		}
	case 13:
		{
			yylex.begin(sc_INITIAL)
			if data, err := strutil.Base64Decode([]byte(yyS[yypt-1].str)); err != nil {
				yylex.Error(err.Error())
			} else {
				yyVAL.data = data
			}
		}
	case 14:
		{
			yylex.begin(sc_BASE64)
		}
	case 15:
		{
			yyVAL.str = yyS[yypt-0].str
		}
	case 16:
		{
			yyVAL.str += yyS[yypt-0].str
		}
	case 17:
		{
			yylex.begin(sc_INITIAL)
			if data, err := strutil.Base64Decode([]byte(yyS[yypt-0].str)); err != nil {
				yylex.Error(err.Error())
			} else {
				yyVAL.data = data
			}
		}
	case 18:
		{
			yylex.begin(sc_DOMAIN2)
		}
	case 19:
		{
			yyVAL.str = yyS[yypt-0].str
		}
	case 20:
		{
			yyVAL.str += yyS[yypt-0].str
		}
	case 21:
		{
			yylex.begin(sc_NUM)
		}
	case 22:
		{
			yyVAL.rrData = &rr.CERT{rr.CertType(yyS[yypt-3].uint), uint16(yyS[yypt-2].uint), yyS[yypt-1].alg, yyS[yypt-0].data}
		}
	case 23:
		{
			yylex.begin(sc_DOMAIN)
		}
	case 24:
		{
			yyVAL.rrData = &rr.CNAME{yyS[yypt-0].str}
		}
	case 25:
		{
			yyVAL.rrData = &rr.DHCID{yyS[yypt-0].data}
		}
	case 26:
		{
			yylex.begin(sc_NUM)
		}
	case 27:
		{
			if yyS[yypt-1].uint != 1 || len(yyS[yypt-0].data) != 20 {
				yylex.Error(`digest type must be "1" and digest must be exactly 20 bytes (40 hex chars)`)
			} else {
				yyVAL.rrData = &rr.DS{uint16(yyS[yypt-3].uint), rr.AlgorithmType(yyS[yypt-2].uint), rr.HashAlgorithm(yyS[yypt-1].uint), yyS[yypt-0].data}
			}
		}
	case 28:
		{
			yylex.begin(sc_DOMAIN)
		}
	case 29:
		{
			yyVAL.rrData = &rr.DNAME{yyS[yypt-0].str}
		}
	case 30:
		{
			if yyS[yypt-1].uint != 3 {
				yylex.Error(`protocol must be "3"`)
			}
		}
	case 31:
		{
			yyVAL.rrData = &rr.DNSKEY{uint16(yyS[yypt-4].uint), byte(yyS[yypt-3].uint), yyS[yypt-2].alg, yyS[yypt-0].data}
		}
	case 32:
		{
			yylex.begin(sc_NUM)
		}
	case 33:
		{
			if yyS[yypt-1].uint != 1 || len(yyS[yypt-0].data) != 20 {
				yylex.Error(`digest type must be "1" and digest must be exactly 20 bytes (40 hex chars)`)
			} else {
				yyVAL.rrData = &rr.DS{uint16(yyS[yypt-3].uint), rr.AlgorithmType(yyS[yypt-2].uint), rr.HashAlgorithm(yyS[yypt-1].uint), yyS[yypt-0].data}
			}
		}
	case 34:
		{
			if t, err := dns.String2Seconds(yyS[yypt-0].str); err != nil {
				yylex.Error(err.Error())
			} else {
				yyVAL.u64 = uint64(t)
			}
		}
	case 35:
		{
			yyVAL.uint = uint(yyS[yypt-0].u64)
		}
	case 36:
		{
			yylex.begin(sc_HEX)
		}
	case 37:
		{
			yyVAL.data = yyS[yypt-0].data
		}
	case 38:
		yyVAL.data = yyS[yypt-0].data
	case 39:
		{
			yyVAL.data = append(yyS[yypt-1].data, yyS[yypt-0].data...)
		}
	case 40:
		{
			yyVAL.data = nil
		}
	case 41:
		yyVAL.data = yyS[yypt-0].data
	case 42:
		{
			yylex.begin(sc_NUM)
		}
	case 43:
		{
			x := &rr.IPSECKEY{Precedence: byte(yyS[yypt-2].uint), GatewayType: rr.GatewayType(yyS[yypt-1].uint), Algorithm: rr.IPSECKEYAlgorithm(yyS[yypt-0].uint)}
			yyVAL.rrData = x
			switch x.GatewayType {
			default:
				yylex.Error("Unknown gateway type")
			case rr.GatewayNone, rr.GatewayIPV4, rr.GatewayIPV6, rr.GatewayDomain:
				// OK
			}

			switch x.Algorithm {
			default:
				yylex.Error("Unknown algorithm")
			case rr.IPSECKEYAlgorithmDSA, rr.IPSECKEYAlgorithmRSA:
				// OK
			}

			yylex.begin(sc_IPSSECKEY)
		}
	case 44:
		{
			x := yyS[yypt-2].rrData.(*rr.IPSECKEY)
			x.PublicKey = yyS[yypt-0].data
			yyVAL.rrData = x
			switch x.GatewayType {
			case rr.GatewayNone:
				// OK
			case rr.GatewayIPV4:
				yylex.Error("missing gateway IPv4 address")
			case rr.GatewayIPV6:
				yylex.Error("missing gateway IPv6 address")
			case rr.GatewayDomain:
				yylex.Error("missing gateway <domain-name>")
			}
		}
	case 45:
		{
			x := yyS[yypt-2].rrData.(*rr.IPSECKEY)
			x.Gateway = yyS[yypt-1].ip
			x.PublicKey = yyS[yypt-0].data
			yyVAL.rrData = x
			if x.GatewayType != rr.GatewayIPV4 {
				yylex.Error("expected IPv4 gateway")
			}
		}
	case 46:
		{
			x := yyS[yypt-2].rrData.(*rr.IPSECKEY)
			x.Gateway = yyS[yypt-1].ip
			x.PublicKey = yyS[yypt-0].data
			yyVAL.rrData = x
			if x.GatewayType != rr.GatewayIPV6 {
				yylex.Error("expected IPv6 gateway")
			}
		}
	case 47:
		{
			x := yyS[yypt-2].rrData.(*rr.IPSECKEY)
			x.PublicKey = yyS[yypt-0].data
			switch x.GatewayType {
			default:
				yylex.Error("unexpected <domain-name> gateway")
			case rr.GatewayIPV4:
				ip := net.ParseIP(yyS[yypt-1].str)
				if ip == nil {
					ip = errIP
					yylex.Error("expected IPv4 gateway")
				}
				x.Gateway = ip
			case rr.GatewayDomain:
				x.Gateway = yyS[yypt-1].str
			}
			yyVAL.rrData = x
		}
	case 48:
		{
			if yyS[yypt-1].uint != 3 {
				yylex.Error(`protocol must be "3"`)
			}
		}
	case 49:
		{
			yyVAL.rrData = &rr.KEY{uint16(yyS[yypt-4].uint), byte(yyS[yypt-3].uint), yyS[yypt-2].alg, yyS[yypt-0].data}
		}
	case 50:
		{
			yylex.begin(sc_NUM)
		}
	case 51:
		{
			yylex.begin(sc_DOMAIN)
		}
	case 52:
		{
			yyVAL.rrData = &rr.KX{uint16(yyS[yypt-2].uint), yyS[yypt-0].str}
		}
	case 53:
		{
			yylex.begin(sc_INITIAL)
		}
	case 54:
		{
			yylex.begin(sc_NUM)
		}
	case 56:
		{
			yylex.begin(sc_RRHEAD)
		}
	case 57:
		{
			yyS[yypt-0].rr.Name = yyS[yypt-2].str
			if !yylex.rrHandler(yyS[yypt-0].rr) {
				goto ret0
			}
		}
	case 58:
		{
			if !yylex.rrHandler(yyS[yypt-0].rr) {
				goto ret0
			}
		}
	case 59:
		{
			yyS[yypt-0].rr.Name = "@"
			if !yylex.rrHandler(yyS[yypt-0].rr) {
				goto ret0
			}
		}
	case 60:
		{
			yyVAL.rrData = &rr.LOC{0, byte(yyS[yypt-0].uint >> 16), byte(yyS[yypt-0].uint >> 8), byte(yyS[yypt-0].uint), uint32(yyS[yypt-3].u64), uint32(yyS[yypt-2].u64), uint32(yyS[yypt-1].u64)}
		}
	case 61:
		{
			yyVAL.uint = uint((*rr.LOC)(nil).EncPrec(100))<<16 | uint((*rr.LOC)(nil).EncPrec(1000000))<<8 | uint((*rr.LOC)(nil).EncPrec(1000))

		}
	case 62:
		{
			yyVAL.uint = uint((*rr.LOC)(nil).EncPrec(yyS[yypt-1].u64))<<16 | yyS[yypt-0].uint
		}
	case 63:
		{
			yyVAL.uint = uint((*rr.LOC)(nil).EncPrec(1000000))<<8 | uint((*rr.LOC)(nil).EncPrec(1000))
		}
	case 64:
		{
			yyVAL.uint = uint((*rr.LOC)(nil).EncPrec(yyS[yypt-1].u64))<<8 | yyS[yypt-0].uint
		}
	case 65:
		{
			yyVAL.uint = uint((*rr.LOC)(nil).EncPrec(1000))
		}
	case 66:
		{
			yyVAL.uint = uint((*rr.LOC)(nil).EncPrec(yyS[yypt-0].u64))
		}
	case 67:
		{
			yyVAL.u64 = 100*yyS[yypt-2].u64 + yyS[yypt-1].u64
		}
	case 68:
		{
			yyVAL.u64 = 0
		}
	case 69:
		{
			for yyVAL.u64 = uint64(yyS[yypt-0].uint); yyVAL.u64 != 0 && yyVAL.u64 < 10; yyVAL.u64 *= 10 {
			}
		}
	case 70:
		{
			x := (int64(yyS[yypt-1].u64) + 100*int64(yyS[yypt-2].int)) * int64(yyS[yypt-3].int)
			yyVAL.u64 = uint64(x + 10000000)
		}
	case 73:
		{
			yyVAL.u64 = 0
		}
	case 74:
		{
			for yyVAL.u64 = uint64(yyS[yypt-0].uint); yyVAL.u64 != 0 && yyVAL.u64 < 10; yyVAL.u64 *= 10 {
			}
		}
	case 75:
		{
			yyVAL.int = 1
		}
	case 76:
		{
			yyVAL.int = 1
		}
	case 77:
		{
			yyVAL.int = -1
		}
	case 78:
		{
			yylex.begin(sc_NUM)
		}
	case 79:
		{
			ts := yyS[yypt-1].u64 % 60000
			m := (yyS[yypt-1].u64 / 60000) % 60
			yyVAL.u64 = uint64((*rr.LOC)(nil).EncDMTS(int(yyS[yypt-2].uint), int(m), int(ts), yyS[yypt-0].int != 0))
		}
	case 80:
		{
			yylex.begin(sc_NUM)
		}
	case 81:
		{
			ts := yyS[yypt-1].u64 % 60000
			m := (yyS[yypt-1].u64 / 60000) % 60
			yyVAL.u64 = uint64((*rr.LOC)(nil).EncDMTS(int(yyS[yypt-2].uint), int(m), int(ts), yyS[yypt-0].int != 0))
		}
	case 82:
		{
			yyVAL.int = 1
		}
	case 83:
		{
			yyVAL.int = 0
		}
	case 84:
		{
			yyVAL.int = 1
		}
	case 85:
		{
			yyVAL.int = 0
		}
	case 86:
		{
			yyVAL.u64 = 0
		}
	case 87:
		{
			yyVAL.u64 = 60000*uint64(yyS[yypt-1].uint) + yyS[yypt-0].u64
		}
	case 88:
		{
			yyVAL.u64 = 0
		}
	case 89:
		{
			yyVAL.u64 = 1000*uint64(yyS[yypt-1].uint) + yyS[yypt-0].u64
		}
	case 90:
		{
			yyVAL.u64 = 0
		}
	case 91:
		{
			for yyVAL.u64 = uint64(yyS[yypt-0].uint); yyVAL.u64 != 0 && yyVAL.u64 < 100; yyVAL.u64 *= 10 {
			}
		}
	case 92:
		{
			yylex.begin(sc_DOMAIN)
		}
	case 93:
		{
			yyVAL.rrData = &rr.MB{yyS[yypt-0].str}
		}
	case 94:
		{
			yylex.begin(sc_DOMAIN)
		}
	case 95:
		{
			yyVAL.rrData = &rr.MD{yyS[yypt-0].str}
		}
	case 96:
		{
			yylex.begin(sc_DOMAIN)
		}
	case 97:
		{
			yyVAL.rrData = &rr.MF{yyS[yypt-0].str}
		}
	case 98:
		{
			yylex.begin(sc_DOMAIN)
		}
	case 99:
		{
			yyVAL.rrData = &rr.MG{yyS[yypt-0].str}
		}
	case 100:
		{
			yylex.begin(sc_DOMAIN)
		}
	case 101:
		{
			yyVAL.rrData = &rr.MINFO{yyS[yypt-1].str, yyS[yypt-0].str}
		}
	case 102:
		{
			yylex.begin(sc_DOMAIN)
		}
	case 103:
		{
			yyVAL.rrData = &rr.MR{yyS[yypt-0].str}
		}
	case 104:
		{
			yylex.begin(sc_NUM)
		}
	case 105:
		{
			yylex.begin(sc_DOMAIN)
		}
	case 106:
		{
			yyVAL.rrData = &rr.MX{uint16(yyS[yypt-2].uint), yyS[yypt-0].str}
		}
	case 107:
		{
			yylex.begin(sc_NUM)
		}
	case 108:
		{
			yylex.begin(sc_DOMAIN)
		}
	case 109:
		{
			yyVAL.rrData = &rr.NAPTR{uint16(yyS[yypt-6].uint), uint16(yyS[yypt-5].uint), yyS[yypt-4].str, yyS[yypt-3].str, yyS[yypt-2].str, yyS[yypt-0].str}
		}
	case 110:
		{
			yylex.begin(sc_DOMAIN)
		}
	case 111:
		{
			yyVAL.rrData = &rr.NS{yyS[yypt-0].str}
		}
	case 112:
		{
			yylex.begin(sc_0XHEX)
		}
	case 113:
		{
			yyVAL.rrData = &rr.NSAP{yyS[yypt-0].data}
		}
	case 114:
		{
			yylex.begin(sc_DOMAIN)
		}
	case 115:
		{
			yyVAL.rrData = &rr.NSAP_PTR{yyS[yypt-0].str}
		}
	case 116:
		{
			yylex.begin(sc_DOMAIN)
		}
	case 117:
		{
			yylex.begin(sc_TYPE)
		}
	case 118:
		{
			yyVAL.rrData = &rr.NSEC{yyS[yypt-2].str, rr.TypesEncode(yyS[yypt-0].types)}
		}
	case 119:
		{
			yylex.begin(sc_NUM)
		}
	case 120:
		{
			yylex.begin(sc_TYPE)
		}
	case 121:
		{
			yyVAL.rrData = &rr.NSEC3{rr.NSEC3PARAM{rr.HashAlgorithm(yyS[yypt-6].uint), byte(yyS[yypt-5].uint), uint16(yyS[yypt-4].uint), yyS[yypt-3].data}, yyS[yypt-2].data, rr.TypesEncode(yyS[yypt-0].types)}
		}
	case 122:
		{
			yylex.begin(sc_NUM)
		}
	case 123:
		{
			yyVAL.rrData = &rr.NSEC3PARAM{rr.HashAlgorithm(yyS[yypt-3].uint), byte(yyS[yypt-2].uint), uint16(yyS[yypt-1].uint), yyS[yypt-0].data}
		}
	case 124:
		{
			yylex.begin(sc_NUM)
		}
	case 125:
		{
			yyVAL.rrData = yyS[yypt-0].rrData
		}
	case 126:
		{
			if int(yyS[yypt-1].uint) != len(yyS[yypt-0].data) {
				yylex.Error(fmt.Sprintf("mismatched data len: %d != %d", yyS[yypt-1].uint, len(yyS[yypt-0].data)))
			}
			yyVAL.rrData = &rr.NULL{yyS[yypt-0].data}
		}
	case 127:
		{
			yyVAL.rrData = &rr.NULL{[]byte{}}
		}
	case 128:
		{
			yylex.begin(sc_DOMAIN)
		}
	case 129:
		{
			yyVAL.rrData = &rr.PTR{yyS[yypt-0].str}
		}
	case 130:
		{
			yylex.begin(sc_NUM)
		}
	case 131:
		{
			yylex.begin(sc_DOMAIN)
		}
	case 132:
		{
			yyVAL.rrData = &rr.PX{uint16(yyS[yypt-3].uint), yyS[yypt-1].str, yyS[yypt-0].str}
		}
	case 133:
		{
			yylex.begin(sc_DOMAIN)
		}
	case 134:
		{
			yyVAL.rrData = &rr.RP{yyS[yypt-1].str, yyS[yypt-0].str}
		}
	case 135:
		{
			yylex.begin(sc_RRHEAD)
		}
	case 136:
		{
			yyVAL.rr = yyS[yypt-0].rr
		}
	case 137:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_A, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 138:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_AAAA, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 139:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_AFSDB, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 140:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_CERT, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 141:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_CNAME, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 142:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_DHCID, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 143:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_DLV, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 144:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_DNAME, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 145:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_DNSKEY, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 146:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_DS, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 147:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_IPSECKEY, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 148:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_KEY, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 149:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_KX, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 150:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_LOC, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 151:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_MB, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 152:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_MD, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 153:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_MF, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 154:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_MG, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 155:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_MINFO, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 156:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_MR, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 157:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_MX, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 158:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_NAPTR, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 159:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_NS, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 160:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_NSAP, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 161:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_NSAP_PTR, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 162:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_NSEC, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 163:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_NSEC3, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 164:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_NSEC3PARAM, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 165:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_NULL, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 166:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_PTR, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 167:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_PX, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 168:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_RP, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 169:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_RRSIG, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 170:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_RT, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 171:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_SIG, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 172:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_SOA, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 173:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_SPF, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 174:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_SRV, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 175:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_SSHFP, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 176:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_GPOS, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 177:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_HINFO, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 178:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_HIP, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 179:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_ISDN, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 180:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_TA, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 181:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_TXT, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 182:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_WKS, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 183:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_X25, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 184:
		{
			yylex.begin(sc_NUM)
		}
	case 185:
		{
			yylex.begin(sc_HEX)
		}
	case 186:
		{
			rdata := rr.RDATA(yyS[yypt-0].data)
			yyVAL.rr = &rr.RR{"", yyS[yypt-5].typ, yyS[yypt-6].rrh.class, yyS[yypt-6].rrh.ttl, &rdata}
			if len(yyS[yypt-0].data) != int(yyS[yypt-2].uint) {
				yylex.Error(fmt.Sprintf("mismatched rdata len: %d != %d", yyS[yypt-2].uint, len(yyS[yypt-0].data)))
			}
		}
	case 187:
		{
			yyVAL.rrh = rrHead{int32(yyS[yypt-1].int), yyS[yypt-0].class}
		}
	case 188:
		{
			yyVAL.rrh = rrHead{int32(yyS[yypt-0].int), yyS[yypt-1].class}
		}
	case 189:
		{
			yyVAL.rrh = rrHead{int32(yyS[yypt-0].int), 0}
		}
	case 190:
		{
			yyVAL.rrh = rrHead{-1, yyS[yypt-0].class}
		}
	case 191:
		{
			yylex.begin(sc_NUM)
		}
	case 192:
		{
			yylex.begin(sc_DOMAIN)
		}
	case 193:
		{
			yyVAL.rrData = &rr.RRSIG{yyS[yypt-10].typ, yyS[yypt-8].alg, byte(yyS[yypt-7].uint), int32(yyS[yypt-6].int), uint32(yyS[yypt-5].uint), uint32(yyS[yypt-4].uint), uint16(yyS[yypt-3].uint), yyS[yypt-1].str, yyS[yypt-0].data}
		}
	case 194:
		{
			yylex.begin(sc_TYPE)
		}
	case 195:
		{
			yyVAL.typ = yyS[yypt-0].typ
		}
	case 196:
		{
			yyVAL.types = nil
			yylex.begin(sc_INITIAL)
		}
	case 197:
		{
			yyVAL.types = []rr.Type{yyS[yypt-0].typ}
		}
	case 198:
		{
			yyVAL.types = append(yyVAL.types, yyS[yypt-0].typ)
		}
	case 199:
		{
			yyVAL.typ = rr.TYPE_A
		}
	case 200:
		{
			yyVAL.typ = rr.TYPE_A6
		}
	case 201:
		{
			yyVAL.typ = rr.TYPE_AAAA
		}
	case 202:
		{
			yyVAL.typ = rr.TYPE_AFSDB
		}
	case 203:
		{
			yyVAL.typ = rr.TYPE_ATMA
		}
	case 204:
		{
			yyVAL.typ = rr.TYPE_APL
		}
	case 205:
		{
			yyVAL.typ = rr.TYPE_CDS
		}
	case 206:
		{
			yyVAL.typ = rr.TYPE_CERT
		}
	case 207:
		{
			yyVAL.typ = rr.TYPE_CNAME
		}
	case 208:
		{
			yyVAL.typ = rr.TYPE_DHCID
		}
	case 209:
		{
			yyVAL.typ = rr.TYPE_DLV
		}
	case 210:
		{
			yyVAL.typ = rr.TYPE_DNAME
		}
	case 211:
		{
			yyVAL.typ = rr.TYPE_DNSKEY
		}
	case 212:
		{
			yyVAL.typ = rr.TYPE_DS
		}
	case 213:
		{
			yyVAL.typ = rr.TYPE_EID
		}
	case 214:
		{
			yyVAL.typ = rr.TYPE_GID
		}
	case 215:
		{
			yyVAL.typ = rr.TYPE_GPOS
		}
	case 216:
		{
			yyVAL.typ = rr.TYPE_HINFO
		}
	case 217:
		{
			yyVAL.typ = rr.TYPE_MINFO
		}
	case 218:
		{
			yyVAL.typ = rr.TYPE_HIP
		}
	case 219:
		{
			yyVAL.typ = rr.TYPE_IPSECKEY
		}
	case 220:
		{
			yyVAL.typ = rr.TYPE_ISDN
		}
	case 221:
		{
			yyVAL.typ = rr.TYPE_KEY
		}
	case 222:
		{
			yyVAL.typ = rr.TYPE_KX
		}
	case 223:
		{
			yyVAL.typ = rr.TYPE_LOC
		}
	case 224:
		{
			yyVAL.typ = rr.TYPE_MB
		}
	case 225:
		{
			yyVAL.typ = rr.TYPE_MD
		}
	case 226:
		{
			yyVAL.typ = rr.TYPE_MF
		}
	case 227:
		{
			yyVAL.typ = rr.TYPE_MR
		}
	case 228:
		{
			yyVAL.typ = rr.TYPE_MX
		}
	case 229:
		{
			yyVAL.typ = rr.TYPE_NAPTR
		}
	case 230:
		{
			yyVAL.typ = rr.TYPE_NIMLOC
		}
	case 231:
		{
			yyVAL.typ = rr.TYPE_NINFO
		}
	case 232:
		{
			yyVAL.typ = rr.TYPE_NS
		}
	case 233:
		{
			yyVAL.typ = rr.TYPE_NSAP
		}
	case 234:
		{
			yyVAL.typ = rr.TYPE_NSAP_PTR
		}
	case 235:
		{
			yyVAL.typ = rr.TYPE_NSEC
		}
	case 236:
		{
			yyVAL.typ = rr.TYPE_NSEC3
		}
	case 237:
		{
			yyVAL.typ = rr.TYPE_NSEC3PARAM
		}
	case 238:
		{
			yyVAL.typ = rr.TYPE_DS
		}
	case 239:
		{
			yyVAL.typ = rr.TYPE_NXT
		}
	case 240:
		{
			yyVAL.typ = rr.TYPE_NULL
		}
	case 241:
		{
			yyVAL.typ = rr.TYPE_PTR
		}
	case 242:
		{
			yyVAL.typ = rr.TYPE_PX
		}
	case 243:
		{
			yyVAL.typ = rr.TYPE_RRSIG
		}
	case 244:
		{
			yyVAL.typ = rr.TYPE_RKEY
		}
	case 245:
		{
			yyVAL.typ = rr.TYPE_RP
		}
	case 246:
		{
			yyVAL.typ = rr.TYPE_RT
		}
	case 247:
		{
			yyVAL.typ = rr.TYPE_SIG
		}
	case 248:
		{
			yyVAL.typ = rr.TYPE_SOA
		}
	case 249:
		{
			yyVAL.typ = rr.TYPE_SPF
		}
	case 250:
		{
			yyVAL.typ = rr.TYPE_SRV
		}
	case 251:
		{
			yyVAL.typ = rr.TYPE_SSHFP
		}
	case 252:
		{
			yyVAL.typ = rr.TYPE_TALINK
		}
	case 253:
		{
			yyVAL.typ = rr.TYPE_TKEY
		}
	case 254:
		{
			yyVAL.typ = rr.TYPE_TSIG
		}
	case 255:
		{
			yyVAL.typ = rr.TYPE_TXT
		}
	case 256:
		{
			yyVAL.typ = rr.TYPE_UID
		}
	case 257:
		{
			yyVAL.typ = rr.TYPE_UINFO
		}
	case 258:
		{
			yyVAL.typ = rr.TYPE_UNSPEC
		}
	case 259:
		{
			yyVAL.typ = rr.TYPE_WKS
		}
	case 260:
		{
			yyVAL.typ = rr.TYPE_X25
		}
	case 261:
		yyVAL.typ = yyS[yypt-0].typ
	case 262:
		{
			yylex.begin(sc_NUM)
		}
	case 263:
		{
			yylex.begin(sc_DOMAIN)
		}
	case 264:
		{
			yyVAL.rrData = &rr.RT{uint16(yyS[yypt-2].uint), yyS[yypt-0].str}
		}
	case 265:
		{
			yylex.begin(sc_NUM)
		}
	case 266:
		{
			yylex.begin(sc_DOMAIN)
		}
	case 267:
		{
			yyVAL.rrData = &rr.SIG{yyS[yypt-10].typ, yyS[yypt-8].alg, byte(yyS[yypt-7].uint), int32(yyS[yypt-6].int), uint32(yyS[yypt-5].uint), uint32(yyS[yypt-4].uint), uint16(yyS[yypt-3].uint), yyS[yypt-1].str, yyS[yypt-0].data}
		}
	case 268:
		{
			yylex.begin(sc_DOMAIN)
		}
	case 269:
		{
			yylex.begin(sc_NUM)
		}
	case 270:
		{
			yyVAL.rrData = &rr.SOA{yyS[yypt-7].str, yyS[yypt-6].str, uint32(yyS[yypt-4].uint), uint32(yyS[yypt-3].uint), uint32(yyS[yypt-2].uint), uint32(yyS[yypt-1].uint), uint32(yyS[yypt-0].uint)}
		}
	case 271:
		{
			yyVAL.rrData = &rr.SPF{yyS[yypt-0].strs}
		}
	case 272:
		{
			yylex.begin(sc_NUM)
		}
	case 273:
		{
			yylex.begin(sc_DOMAIN)
		}
	case 274:
		{
			yyVAL.rrData = &rr.SRV{uint16(yyS[yypt-4].uint), uint16(yyS[yypt-3].uint), uint16(yyS[yypt-2].uint), yyS[yypt-0].str}
		}
	case 275:
		{
			yylex.begin(sc_NUM)
		}
	case 276:
		{
			yyVAL.rrData = &rr.SSHFP{rr.SSHFPAlgorithm(yyS[yypt-2].uint), rr.SSHFPType(yyS[yypt-1].uint), yyS[yypt-0].data}
		}
	case 277:
		{
			yylex.begin(sc_NUM)
		}
	case 278:
		{
			if yyS[yypt-1].uint != 1 || len(yyS[yypt-0].data) != 20 {
				yylex.Error(`digest type must be "1" and digest must be exactly 20 bytes (40 hex chars)`)
			} else {
				yyVAL.rrData = &rr.DS{uint16(yyS[yypt-3].uint), rr.AlgorithmType(yyS[yypt-2].uint), rr.HashAlgorithm(yyS[yypt-1].uint), yyS[yypt-0].data}
			}
		}
	case 279:
		yyVAL.int = yyS[yypt-0].int
	case 280:
		{
			yyVAL.rrData = &rr.TXT{yyS[yypt-0].strs}
		}
	case 281:
		{
			yyVAL.strs = nil
		}
	case 282:
		{
			yyVAL.strs = append(yyVAL.strs, yyS[yypt-0].str)
		}
	case 283:
		{
			yylex.begin(sc_FLOAT)
		}
	case 284:
		{
			yyVAL.rrData = &rr.GPOS{yyS[yypt-2].float, yyS[yypt-1].float, yyS[yypt-0].float}
		}
	case 285:
		{
			yyVAL.rrData = &rr.HINFO{yyS[yypt-1].str, yyS[yypt-0].str}
		}
	case 286:
		{
			yylex.begin(sc_NUM)
		}
	case 287:
		{
			yylex.begin(sc_DOMAIN2)
		}
	case 288:
		{
			yyVAL.rrData = &rr.HIP{rr.IPSECKEYAlgorithm(yyS[yypt-4].uint), yyS[yypt-3].data, yyS[yypt-2].data, yyS[yypt-0].strs}
		}
	case 289:
		{
			yyVAL.strs = nil
		}
	case 290:
		{
			yyVAL.strs = append(yyS[yypt-1].strs, yyS[yypt-0].str)
		}
	case 291:
		{
			yyVAL.rrData = &rr.ISDN{yyS[yypt-0].str, ""}
		}
	case 292:
		{
			yyVAL.rrData = &rr.ISDN{yyS[yypt-1].str, yyS[yypt-0].str}
		}
	case 293:
		{
			if yyS[yypt-0].u64 > math.MaxUint8 {
				yylex.Error("number out of range")
				yyVAL.uint = math.MaxUint8
			} else {
				yyVAL.uint = uint(yyS[yypt-0].u64)
			}
		}
	case 294:
		{
			if yyS[yypt-0].u64 > math.MaxUint16 {
				yylex.Error("number out of range")
				yyVAL.uint = math.MaxUint16
			} else {
				yyVAL.uint = uint(yyS[yypt-0].u64)
			}
		}
	case 295:
		{
			if yyS[yypt-0].u64 > math.MaxInt32 {
				yylex.Error("number out of range")
				yyVAL.int = math.MaxInt32
			} else {
				yyVAL.int = int(yyS[yypt-0].u64)
			}
		}
	case 296:
		{
			if yyS[yypt-0].u64 > math.MaxUint32 {
				yylex.Error("number out of range")
				yyVAL.uint = math.MaxUint32
			} else {
				yyVAL.uint = uint(yyS[yypt-0].u64)
			}
		}
	case 297:
		{
			yylex.begin(sc_IPV4)
		}
	case 298:
		{
			yylex.begin(sc_PROTO)
		}
	case 299:
		{
			yylex.begin(sc_PORT)
		}
	case 300:
		{
			x := &rr.WKS{yyS[yypt-4].ip, rr.IP_Protocol(yyS[yypt-2].int), map[rr.IP_Port]struct{}{}}
			for i, v := range yyS[yypt-0].data {
				for j := 8 * i; v != 0; j, v = j+1, v>>1 {
					if v&1 != 0 {
						x.Ports[rr.IP_Port(j)] = struct{}{}
					}
				}
			}
			yyVAL.rrData = x
		}
	case 305:
		{
			yyVAL.data = make([]byte, 128)
		}
	case 306:
		{
			i := rr.IP_Port(yyS[yypt-0].int)
			yyVAL.data[i>>3] |= 1 << uint(i&7)
		}
	case 307:
		{
			yyVAL.rrData = &rr.X25{yyS[yypt-0].str}
		}
	}
	goto yystack /* stack new state and value */
}
