// Copyright (c) 2011 CZ.NIC z.s.p.o. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// blame: jnml, labs.nic.cz

// WARNING: If this file is parser.go then DO NOT EDIT.
// parser.go is generated by goyacc from parser.y (see the Makefile).

package zone

import (
	"fmt"
	"github.com/cznic/dns"
	"github.com/cznic/dns/rr"
	"github.com/cznic/strutil"
	"math"
	"net"
)

type rrHead struct {
	ttl   int32
	class rr.Class
}

type yySymType struct {
	yys    int
	alg    rr.AlgorithmType
	class  rr.Class
	data   []byte
	str    string
	u64    uint64
	int    int
	float  float64
	uint   uint
	ip     net.IP
	rrh    rrHead
	rrData dns.Wirer
	rr     *rr.RR
	typ    rr.Type
	types  []rr.Type
}

const tA = 57346
const tA6 = 57347
const tAAAA = 57348
const tAFSDB = 57349
const tAPL = 57350
const tATMA = 57351
const tBACKSLASH_HASH = 57352
const tBLANK_START = 57353
const tCDS = 57354
const tCERT = 57355
const tCNAME = 57356
const tDHCID = 57357
const tDLR_TTL = 57358
const tDNAME = 57359
const tDNSKEY = 57360
const tDNS_PORT = 57361
const tDS = 57362
const tEID = 57363
const tGID = 57364
const tGPOS = 57365
const tHINFO = 57366
const tHIP = 57367
const tIPSECKEY = 57368
const tISDN = 57369
const tKEY = 57370
const tKX = 57371
const tLOC = 57372
const tMB = 57373
const tMD = 57374
const tMF = 57375
const tMG = 57376
const tMINFO = 57377
const tMR = 57378
const tMX = 57379
const tNAPTR = 57380
const tNIMLOC = 57381
const tNINFO = 57382
const tNS = 57383
const tNSAP = 57384
const tNSAP_PTR = 57385
const tNSEC = 57386
const tNSEC3 = 57387
const tNSEC3PARAM = 57388
const tNULL = 57389
const tNXT = 57390
const tPTR = 57391
const tPX = 57392
const tRKEY = 57393
const tRP = 57394
const tRRSIG = 57395
const tRT = 57396
const tSIG = 57397
const tSMTP_PORT = 57398
const tSOA = 57399
const tSPF = 57400
const tSRV = 57401
const tSSHFP = 57402
const tTALINK = 57403
const tTCP_PROTO = 57404
const tTKEY = 57405
const tTSIG = 57406
const tTXT = 57407
const tUDP_PROTO = 57408
const tUID = 57409
const tUINFO = 57410
const tUNSPEC = 57411
const tWKS = 57412
const tX25 = 57413
const tHEX = 57414
const t0xHEX = 57415
const tBASE32EXT = 57416
const tBASE64 = 57417
const tDOMAIN_NAME = 57418
const tSRV_DOMAIN = 57419
const tQSTR = 57420
const tFLOAT = 57421
const tCLASS = 57422
const tIPV4 = 57423
const tIPV6 = 57424
const tDECADIC = 57425

var yyToknames = []string{
	"tA",
	"tA6",
	"tAAAA",
	"tAFSDB",
	"tAPL",
	"tATMA",
	"tBACKSLASH_HASH",
	"tBLANK_START",
	"tCDS",
	"tCERT",
	"tCNAME",
	"tDHCID",
	"tDLR_TTL",
	"tDNAME",
	"tDNSKEY",
	"tDNS_PORT",
	"tDS",
	"tEID",
	"tGID",
	"tGPOS",
	"tHINFO",
	"tHIP",
	"tIPSECKEY",
	"tISDN",
	"tKEY",
	"tKX",
	"tLOC",
	"tMB",
	"tMD",
	"tMF",
	"tMG",
	"tMINFO",
	"tMR",
	"tMX",
	"tNAPTR",
	"tNIMLOC",
	"tNINFO",
	"tNS",
	"tNSAP",
	"tNSAP_PTR",
	"tNSEC",
	"tNSEC3",
	"tNSEC3PARAM",
	"tNULL",
	"tNXT",
	"tPTR",
	"tPX",
	"tRKEY",
	"tRP",
	"tRRSIG",
	"tRT",
	"tSIG",
	"tSMTP_PORT",
	"tSOA",
	"tSPF",
	"tSRV",
	"tSSHFP",
	"tTALINK",
	"tTCP_PROTO",
	"tTKEY",
	"tTSIG",
	"tTXT",
	"tUDP_PROTO",
	"tUID",
	"tUINFO",
	"tUNSPEC",
	"tWKS",
	"tX25",
	"tHEX",
	"t0xHEX",
	"tBASE32EXT",
	"tBASE64",
	"tDOMAIN_NAME",
	"tSRV_DOMAIN",
	"tQSTR",
	"tFLOAT",
	"tCLASS",
	"tIPV4",
	"tIPV6",
	"tDECADIC",
}
var yyStatenames = []string{}

const yyEofCode = 1
const yyErrCode = 2
const yyMaxDepth = 200

var yyExca = []int{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 394,
	1, 109,
	11, 109,
	16, 109,
	76, 109,
	77, 109,
	84, 109,
	86, 109,
	-2, 175,
}

const yyNprod = 278
const yyPrivate = 57344

var yyTokenNames []string
var yyStates []string

const yyLast = 475

var yyAct = []int{

	170, 119, 362, 368, 377, 147, 24, 313, 326, 287,
	351, 352, 274, 17, 275, 318, 319, 16, 369, 7,
	68, 354, 69, 70, 4, 284, 285, 349, 347, 71,
	72, 395, 110, 73, 74, 25, 75, 363, 18, 102,
	103, 120, 108, 104, 77, 78, 79, 80, 81, 82,
	83, 84, 85, 86, 87, 278, 379, 88, 89, 90,
	168, 91, 92, 93, 277, 94, 95, 314, 96, 97,
	98, 99, 18, 100, 162, 269, 101, 161, 109, 126,
	334, 105, 302, 265, 5, 6, 106, 107, 374, 355,
	125, 323, 3, 268, 8, 123, 124, 267, 266, 122,
	158, 155, 154, 405, 404, 150, 393, 383, 359, 330,
	328, 322, 311, 306, 300, 296, 289, 163, 164, 263,
	198, 196, 191, 169, 173, 174, 175, 189, 186, 177,
	185, 184, 183, 182, 167, 181, 166, 165, 187, 188,
	279, 176, 386, 190, 180, 358, 336, 197, 112, 392,
	337, 261, 13, 23, 195, 390, 192, 193, 2, 364,
	9, 15, 271, 335, 19, 303, 273, 264, 157, 153,
	152, 365, 160, 332, 270, 27, 151, 402, 262, 298,
	149, 148, 401, 199, 276, 14, 391, 21, 146, 280,
	291, 295, 145, 144, 286, 288, 143, 294, 142, 385,
	141, 140, 139, 138, 384, 137, 290, 292, 293, 136,
	135, 134, 297, 133, 132, 131, 130, 179, 129, 12,
	11, 10, 281, 127, 310, 159, 327, 121, 308, 118,
	117, 116, 172, 376, 272, 115, 114, 113, 1, 366,
	344, 312, 346, 348, 282, 353, 320, 178, 128, 378,
	394, 200, 156, 171, 26, 22, 20, 67, 66, 65,
	61, 111, 60, 59, 58, 57, 56, 55, 54, 194,
	53, 52, 51, 305, 50, 299, 49, 48, 47, 301,
	46, 45, 44, 43, 42, 304, 307, 41, 40, 39,
	38, 309, 37, 64, 324, 325, 316, 315, 76, 36,
	63, 288, 62, 321, 35, 34, 33, 339, 340, 341,
	333, 343, 329, 32, 331, 31, 30, 29, 342, 338,
	28, 345, 283, 350, 317, 382, 375, 0, 0, 0,
	0, 0, 0, 356, 357, 0, 360, 0, 361, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 371, 367, 0, 0, 373, 0, 0, 0,
	0, 0, 370, 0, 372, 381, 380, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 387, 0, 389, 388, 0, 0, 0, 397,
	398, 396, 399, 0, 0, 0, 0, 0, 0, 0,
	400, 0, 403, 0, 0, 406, 407, 201, 202, 203,
	204, 206, 205, 0, 0, 207, 208, 209, 210, 0,
	211, 212, 0, 213, 214, 215, 216, 217, 219, 220,
	221, 222, 223, 224, 225, 226, 227, 0, 218, 228,
	229, 230, 231, 232, 233, 234, 235, 236, 237, 238,
	240, 239, 241, 242, 244, 245, 243, 246, 247, 0,
	248, 249, 250, 251, 252, 0, 253, 254, 255, 0,
	256, 257, 258, 259, 260,
}
var yyPact = []int{

	8, 8, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-11, -1000, -1000, -1000, -45, -1000, -1000, -1000, -1000, -1000,
	-1000, -45, -1000, 16, -2, -11, -1000, 89, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -42, -1000, 14, -42, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, 24, 23, -1000, -1000, 22, -1000, -1000,
	-1000, -1000, -1000, -4, -8, -42, -42, 61, 60, -23,
	-1000, -42, -1000, -1000, -1000, -1000, -23, -42, -1000, -23,
	59, 57, 56, 55, 54, 52, -42, -42, 51, 70,
	46, -23, -23, 144, 45, -42, 44, -1000, 403, -42,
	-1000, 43, -23, 4, 20, 19, 15, -6, -1000, -23,
	-42, -1000, -1000, -1000, -42, -1000, -1000, -23, -1000, -23,
	-1000, -20, 65, -1000, -1000, -1000, -23, -1000, -63, -23,
	-23, -1000, -1000, -1000, -1000, 40, -1000, -1000, -42, -1000,
	-1000, -1000, -23, -23, -1000, -42, -1000, -1000, 39, -23,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -23, 38, -23, 3, -1000, -1000, -1000, -1000,
	-23, -42, 37, -23, -1000, -1000, -23, -1000, -1000, -1000,
	-1000, 36, -16, -11, -1000, -1000, -23, -75, -23, -1000,
	35, 13, -42, -42, -1000, 34, -1000, -23, 33, -23,
	-1000, -1000, 1, 84, -23, -42, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -16, -57, -58, -82, -1000, -1000, -1000,
	-1000, -64, -1000, 11, -1000, -1000, -1000, 73, 32, -11,
	-1000, -11, -46, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -16, -69, -23, -69, -23,
	-1000, -1000, -1000, -1000, -42, 10, -1000, -1000, -1000, -1000,
	-27, -27, -46, -1000, -1000, 31, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, 68, -27, -1000, -1000,
	-27, -46, 130, -1000, 30, -53, -1000, -42, -42, -46,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -46,
	-1000, 28, 27, -1000, -1000, -1000, -1000, -1000,
}
var yyPgo = []int{

	0, 12, 326, 0, 8, 325, 6, 13, 324, 323,
	322, 320, 317, 316, 315, 313, 306, 305, 304, 302,
	300, 299, 298, 293, 292, 290, 289, 288, 287, 284,
	283, 282, 281, 280, 278, 277, 276, 274, 272, 271,
	270, 269, 268, 267, 266, 265, 264, 263, 262, 261,
	260, 259, 258, 257, 152, 256, 255, 254, 153, 253,
	252, 5, 251, 250, 249, 248, 247, 9, 246, 245,
	244, 243, 242, 7, 4, 14, 1, 2, 241, 240,
	239, 238, 158, 237, 236, 235, 234, 233, 232, 231,
	230, 229, 228, 227, 226, 225, 224, 223, 222, 221,
	220, 219, 3, 218, 217, 216, 215, 214, 213, 211,
	210, 209, 206, 205, 204, 203, 202, 201, 200, 199,
	198, 196, 193, 192, 191, 188, 187, 185, 183, 182,
	181, 180, 179, 178, 177, 176, 173, 172, 171, 170,
	169, 168, 165, 163, 159, 155,
}
var yyR1 = []int{

	0, 81, 81, 83, 11, 84, 12, 85, 86, 13,
	1, 87, 2, 3, 88, 59, 59, 89, 14, 90,
	15, 91, 16, 92, 17, 93, 18, 64, 74, 94,
	4, 95, 22, 21, 21, 21, 21, 96, 24, 97,
	98, 25, 82, 99, 82, 100, 82, 101, 82, 82,
	82, 26, 78, 78, 79, 79, 80, 80, 73, 72,
	72, 70, 102, 102, 71, 71, 10, 10, 10, 103,
	65, 104, 66, 8, 8, 9, 9, 67, 67, 68,
	68, 69, 69, 105, 27, 106, 28, 107, 29, 108,
	30, 109, 31, 110, 32, 111, 112, 33, 113, 114,
	34, 115, 35, 116, 36, 117, 37, 118, 119, 38,
	120, 39, 121, 40, 41, 41, 122, 42, 123, 124,
	43, 125, 44, 126, 55, 57, 127, 54, 56, 56,
	56, 56, 56, 56, 56, 56, 56, 56, 56, 56,
	56, 56, 56, 56, 56, 56, 56, 56, 56, 56,
	56, 56, 56, 56, 56, 56, 56, 56, 56, 56,
	56, 56, 56, 56, 56, 56, 56, 56, 58, 58,
	58, 58, 128, 129, 45, 130, 61, 63, 63, 63,
	62, 62, 62, 62, 62, 62, 62, 62, 62, 62,
	62, 62, 62, 62, 62, 62, 62, 62, 62, 62,
	62, 62, 62, 62, 62, 62, 62, 62, 62, 62,
	62, 62, 62, 62, 62, 62, 62, 62, 62, 62,
	62, 62, 62, 62, 62, 62, 62, 62, 62, 62,
	62, 62, 62, 62, 62, 62, 62, 62, 62, 62,
	131, 132, 46, 133, 134, 47, 135, 136, 48, 137,
	138, 49, 139, 50, 6, 51, 60, 60, 140, 19,
	20, 23, 23, 75, 76, 7, 77, 141, 142, 144,
	52, 143, 143, 145, 145, 5, 5, 53,
}
var yyR2 = []int{

	0, 1, 2, 0, 3, 0, 3, 0, 0, 5,
	1, 0, 2, 2, 0, 2, 2, 0, 6, 0,
	3, 0, 3, 0, 6, 0, 6, 1, 1, 0,
	2, 0, 5, 3, 3, 3, 3, 0, 6, 0,
	0, 5, 1, 0, 3, 0, 3, 0, 3, 2,
	2, 5, 0, 2, 0, 2, 0, 1, 3, 0,
	2, 4, 0, 1, 0, 2, 0, 1, 1, 0,
	4, 0, 4, 1, 1, 1, 1, 0, 2, 0,
	2, 0, 2, 0, 3, 0, 3, 0, 3, 0,
	3, 0, 4, 0, 3, 0, 0, 5, 0, 0,
	9, 0, 3, 0, 3, 0, 3, 0, 0, 9,
	0, 6, 0, 3, 3, 1, 0, 3, 0, 0,
	6, 0, 4, 0, 2, 2, 0, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	1, 1, 0, 0, 12, 0, 2, 1, 1, 2,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	0, 0, 5, 0, 0, 12, 0, 0, 10, 0,
	0, 7, 0, 5, 1, 2, 0, 2, 0, 5,
	3, 2, 3, 1, 1, 1, 1, 0, 0, 0,
	7, 1, 1, 1, 1, 0, 2, 2,
}
var yyChk = []int{

	-1000, -81, -82, 84, 16, 76, 77, 11, 86, -82,
	-99, -100, -101, -54, -127, -54, -6, -7, 83, -54,
	-55, -126, -56, -58, -6, 80, -57, -58, -11, -12,
	-13, -14, -15, -16, -17, -18, -21, -24, -25, -26,
	-27, -28, -29, -30, -31, -32, -33, -34, -35, -36,
	-37, -38, -39, -40, -42, -43, -44, -45, -46, -47,
	-48, -50, -19, -20, -23, -51, -52, -53, 4, 6,
	7, 13, 14, 17, 18, 20, -22, 28, 29, 30,
	31, 32, 33, 34, 35, 36, 37, 38, 41, 42,
	43, 45, 46, 47, 49, 50, 52, 53, 54, 55,
	57, 60, 23, 24, 27, 65, 70, 71, 26, 80,
	-6, -49, 59, -83, -84, -85, -89, -90, -91, -76,
	83, -93, 85, 81, 82, 76, -76, -97, -65, -103,
	-105, -106, -107, -108, -109, -110, -111, -113, -115, -116,
	-117, -118, -120, -121, -122, -123, -125, -61, -130, -131,
	-61, -135, -139, -140, 78, 78, -60, -141, 78, -95,
	-137, 81, 82, -76, -76, 76, 76, -75, 83, -76,
	-3, -59, -88, -3, -3, -3, -75, -76, -66, -104,
	-75, 76, 76, 76, 76, 76, 76, -76, -76, 76,
	73, 76, -75, -75, -41, 10, 76, -76, 76, -128,
	-62, 4, 5, 6, 7, 9, 8, 12, 13, 14,
	15, 17, 18, 20, 21, 22, 23, 24, 35, 25,
	26, 27, 28, 29, 30, 31, 32, 33, 36, 37,
	38, 39, 40, 41, 42, 43, 44, 45, 46, 48,
	47, 49, 50, 53, 51, 52, 54, 55, 57, 58,
	59, 60, 61, 63, 64, 65, 67, 68, 69, 70,
	71, -76, -133, 76, -75, 79, 78, 78, 78, 81,
	-75, -76, -86, -76, -1, -75, -75, 84, 75, 75,
	-1, -98, -70, -10, 88, 89, -75, -67, -75, 76,
	-112, -76, -75, -75, -76, -124, 76, -1, -132, -1,
	76, -75, 79, -142, -75, -76, 76, -1, -92, -75,
	-96, 76, -78, -73, 83, -7, -67, -8, 90, 91,
	-68, -75, 76, 78, -76, -76, -4, -94, 76, -75,
	76, -75, -136, -4, 79, -143, 62, 66, -75, -76,
	-3, -3, -4, -3, -79, -73, -72, 85, -71, 85,
	-9, 92, 93, -69, 85, 78, -4, -4, 72, 76,
	-6, -6, -77, 83, -144, -138, -80, -73, -102, 87,
	-75, -102, -75, -76, 78, -2, -87, -74, -64, 83,
	-74, -77, -5, 76, -114, -119, 74, -74, -74, -77,
	-145, 56, 19, 76, -63, 84, -61, -76, -76, -77,
	-61, -129, -134, -77, 76, 76, -3, -3,
}
var yyDef = []int{

	0, -2, 1, 42, 43, 45, 47, 126, 126, 2,
	0, 126, 123, 49, 0, 50, 44, 254, 265, 46,
	48, 0, 127, 0, 170, 171, 124, 0, 128, 129,
	130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
	140, 141, 142, 143, 144, 145, 146, 147, 148, 149,
	150, 151, 152, 153, 154, 155, 156, 157, 158, 159,
	160, 161, 162, 163, 164, 165, 166, 167, 3, 5,
	7, 17, 19, 21, 0, 25, 0, 0, 39, 69,
	83, 85, 87, 89, 91, 93, 95, 98, 101, 103,
	105, 107, 110, 112, 116, 118, 121, 175, 240, 175,
	246, 252, 258, 0, 0, 256, 267, 0, 31, 168,
	169, 125, 249, 0, 0, 0, 0, 0, 0, 0,
	264, 0, 14, 14, 14, 14, 0, 0, 71, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 172, 0, 0,
	243, 0, 0, 0, 0, 261, 255, 0, 277, 0,
	0, 4, 6, 8, 0, 20, 22, 0, 263, 0,
	33, 0, 0, 34, 35, 36, 0, 40, 66, 0,
	77, 84, 86, 88, 90, 0, 94, 96, 0, 102,
	104, 106, 0, 0, 113, 115, 117, 119, 0, 0,
	176, 180, 181, 182, 183, 184, 185, 186, 187, 188,
	189, 190, 191, 192, 193, 194, 195, 196, 197, 198,
	199, 200, 201, 202, 203, 204, 205, 206, 207, 208,
	209, 210, 211, 212, 213, 214, 215, 216, 217, 218,
	219, 220, 221, 222, 223, 224, 225, 226, 227, 228,
	229, 230, 231, 232, 233, 234, 235, 236, 237, 238,
	239, 241, 0, 0, 0, 0, 260, 262, 257, 268,
	0, 0, 0, 0, 23, 10, 0, 13, 16, 15,
	37, 0, 52, 0, 67, 68, 77, 0, 79, 92,
	0, 0, 0, 0, 29, 0, 122, 0, 0, 0,
	247, 29, 0, 0, 0, 0, 9, 14, 14, 29,
	14, 41, 51, 54, 59, 64, 0, 70, 73, 74,
	78, 81, 97, 0, 29, 29, 114, 0, 0, 0,
	242, 0, 0, 253, 259, 269, 271, 272, 32, 250,
	18, 24, 26, 38, 53, 56, 62, 0, 62, 0,
	72, 75, 76, 80, 0, 0, 11, 111, 30, 120,
	0, 0, 0, 266, 275, 0, 55, 57, 58, 63,
	60, 61, 65, 82, 99, 108, 0, 0, 28, 27,
	0, 0, 270, 251, 0, 175, 12, 0, 0, 0,
	276, 273, 274, 100, -2, 177, 178, 173, 244, 0,
	179, 0, 0, 248, 14, 14, 174, 245,
}
var yyTok1 = []int{

	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	84, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 88, 3, 89, 85, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 86, 3, 3, 3, 3, 92,
	3, 3, 3, 3, 3, 3, 3, 3, 90, 3,
	3, 3, 3, 91, 3, 3, 3, 93, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 87,
}
var yyTok2 = []int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
	72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
	82, 83,
}
var yyTok3 = []int{
	0,
}

/*	parser for yacc output	*/

var yyDebug = 0

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c > 0 && c <= len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return fmt.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return fmt.Sprintf("state-%v", s)
}

func yylex1(lex yyLexer, lval *yySymType) int {
	c := 0
	char := lex.Lex(lval)
	if char <= 0 {
		c = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		c = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			c = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		c = yyTok3[i+0]
		if c == char {
			c = yyTok3[i+1]
			goto out
		}
	}

out:
	if c == 0 {
		c = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		fmt.Printf("lex %U %s\n", uint(char), yyTokname(c))
	}
	return c
}

func yyParse(yylex *lex) int {
	var yyn int
	var yylval yySymType
	var yyVAL yySymType
	yyS := make([]yySymType, yyMaxDepth)

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yychar := -1
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		fmt.Printf("char %v in %v\n", yyTokname(yychar), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yychar < 0 {
		yychar = yylex1(yylex, &yylval)
	}
	yyn += yychar
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yychar { /* valid shift */
		yychar = -1
		yyVAL = yylval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yychar < 0 {
			yychar = yylex1(yylex, &yylval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yychar {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error("syntax error")
			Nerrs++
			if yyDebug >= 1 {
				fmt.Printf("%s", yyStatname(yystate))
				fmt.Printf("saw %s\n", yyTokname(yychar))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					fmt.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				fmt.Printf("error recovery discards %s\n", yyTokname(yychar))
			}
			if yychar == yyEofCode {
				goto ret1
			}
			yychar = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		fmt.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 3:
		{
			yylex.begin(sc_IPV4)
		}
	case 4:
		{
			yyVAL.rrData = &rr.A{yyS[yypt-0].ip}
		}
	case 5:
		{
			yylex.begin(sc_IPV6)
		}
	case 6:
		{
			yyVAL.rrData = &rr.AAAA{yyS[yypt-0].ip}
		}
	case 7:
		{
			yylex.begin(sc_NUM)
		}
	case 8:
		{
			yylex.begin(sc_DOMAIN)
		}
	case 9:
		{
			yyVAL.rrData = &rr.AFSDB{uint16(yyS[yypt-2].uint), yyS[yypt-0].str}
		}
	case 10:
		{
			yyVAL.alg = rr.AlgorithmType(yyS[yypt-0].uint)
		}
	case 11:
		{
			yylex.begin(sc_BASE32EXT)
		}
	case 12:
		{
			yylex.begin(sc_INITIAL)
			if data, err := strutil.Base32ExtDecode([]byte(yyS[yypt-0].str)); err != nil {
				yylex.Error(err.Error())
			} else {
				yyVAL.data = data
			}
		}
	case 13:
		{
			yylex.begin(sc_INITIAL)
			if data, err := strutil.Base64Decode([]byte(yyS[yypt-1].str)); err != nil {
				yylex.Error(err.Error())
			} else {
				yyVAL.data = data
			}
		}
	case 14:
		{
			yylex.begin(sc_BASE64)
		}
	case 15:
		{
			yyVAL.str = yyS[yypt-0].str
		}
	case 16:
		{
			yyVAL.str += yyS[yypt-0].str
		}
	case 17:
		{
			yylex.begin(sc_NUM)
		}
	case 18:
		{
			yyVAL.rrData = &rr.CERT{rr.CertType(yyS[yypt-3].uint), uint16(yyS[yypt-2].uint), yyS[yypt-1].alg, yyS[yypt-0].data}
		}
	case 19:
		{
			yylex.begin(sc_DOMAIN)
		}
	case 20:
		{
			yyVAL.rrData = &rr.CNAME{yyS[yypt-0].str}
		}
	case 21:
		{
			yylex.begin(sc_DOMAIN)
		}
	case 22:
		{
			yyVAL.rrData = &rr.DNAME{yyS[yypt-0].str}
		}
	case 23:
		{
			if yyS[yypt-1].uint != 3 {
				yylex.Error(`protocol must be "3"`)
			}
		}
	case 24:
		{
			yyVAL.rrData = &rr.DNSKEY{uint16(yyS[yypt-4].uint), byte(yyS[yypt-3].uint), yyS[yypt-2].alg, yyS[yypt-0].data}
		}
	case 25:
		{
			yylex.begin(sc_NUM)
		}
	case 26:
		{
			if yyS[yypt-1].uint != 1 || len(yyS[yypt-0].data) != 20 {
				yylex.Error(`digest type must be "1" and digest must be exactly 20 bytes (40 hex chars)`)
			} else {
				yyVAL.rrData = &rr.DS{uint16(yyS[yypt-3].uint), rr.AlgorithmType(yyS[yypt-2].uint), rr.HashAlgorithm(yyS[yypt-1].uint), yyS[yypt-0].data}
			}
		}
	case 27:
		{
			if t, err := dns.String2Seconds(yyS[yypt-0].str); err != nil {
				yylex.Error(err.Error())
			} else {
				yyVAL.u64 = uint64(t)
			}
		}
	case 28:
		{
			yyVAL.uint = uint(yyS[yypt-0].u64)
		}
	case 29:
		{
			yylex.begin(sc_HEX)
		}
	case 30:
		{
			yyVAL.data = yyS[yypt-0].data
		}
	case 31:
		{
			yylex.begin(sc_NUM)
		}
	case 32:
		{
			x := &rr.IPSECKEY{Precedence: byte(yyS[yypt-2].uint), GatewayType: rr.GatewayType(yyS[yypt-1].uint), Algorithm: rr.IPSECKEYAlgorithm(yyS[yypt-0].uint)}
			yyVAL.rrData = x
			switch x.GatewayType {
			default:
				yylex.Error("Unknown gateway type")
			case rr.GatewayNone, rr.GatewayIPV4, rr.GatewayIPV6, rr.GatewayDomain:
				// OK
			}

			switch x.Algorithm {
			default:
				yylex.Error("Unknown algorithm")
			case rr.IPSECKEYAlgorithmDSA, rr.IPSECKEYAlgorithmRSA:
				// OK
			}

			yylex.begin(sc_IPSSECKEY)
		}
	case 33:
		{
			x := yyS[yypt-2].rrData.(*rr.IPSECKEY)
			x.PublicKey = yyS[yypt-0].data
			yyVAL.rrData = x
			switch x.GatewayType {
			case rr.GatewayNone:
				// OK
			case rr.GatewayIPV4:
				yylex.Error("missing gateway IPv4 address")
			case rr.GatewayIPV6:
				yylex.Error("missing gateway IPv6 address")
			case rr.GatewayDomain:
				yylex.Error("missing gateway <domain-name>")
			}
		}
	case 34:
		{
			x := yyS[yypt-2].rrData.(*rr.IPSECKEY)
			x.Gateway = yyS[yypt-1].ip
			x.PublicKey = yyS[yypt-0].data
			yyVAL.rrData = x
			if x.GatewayType != rr.GatewayIPV4 {
				yylex.Error("expected IPv4 gateway")
			}
		}
	case 35:
		{
			x := yyS[yypt-2].rrData.(*rr.IPSECKEY)
			x.Gateway = yyS[yypt-1].ip
			x.PublicKey = yyS[yypt-0].data
			yyVAL.rrData = x
			if x.GatewayType != rr.GatewayIPV6 {
				yylex.Error("expected IPv6 gateway")
			}
		}
	case 36:
		{
			x := yyS[yypt-2].rrData.(*rr.IPSECKEY)
			x.Gateway = yyS[yypt-1].str
			x.PublicKey = yyS[yypt-0].data
			yyVAL.rrData = x
			if x.GatewayType != rr.GatewayDomain {
				println(yyS[yypt-1].str)
				yylex.Error("expected <domain-name> gateway")
			}
		}
	case 37:
		{
			if yyS[yypt-1].uint != 3 {
				yylex.Error(`protocol must be "3"`)
			}
		}
	case 38:
		{
			yyVAL.rrData = &rr.KEY{uint16(yyS[yypt-4].uint), byte(yyS[yypt-3].uint), yyS[yypt-2].alg, yyS[yypt-0].data}
		}
	case 39:
		{
			yylex.begin(sc_NUM)
		}
	case 40:
		{
			yylex.begin(sc_DOMAIN)
		}
	case 41:
		{
			yyVAL.rrData = &rr.KX{uint16(yyS[yypt-2].uint), yyS[yypt-0].str}
		}
	case 42:
		{
			yylex.begin(sc_INITIAL)
		}
	case 43:
		{
			yylex.begin(sc_NUM)
		}
	case 45:
		{
			yylex.begin(sc_RRHEAD)
		}
	case 46:
		{
			yyS[yypt-0].rr.Name = yyS[yypt-2].str
			if !yylex.rrHandler(yyS[yypt-0].rr) {
				goto ret0
			}
		}
	case 47:
		{
			yylex.begin(sc_RRHEAD)
		}
	case 48:
		{
			yyS[yypt-0].rr.Name = yyS[yypt-2].str
			if !yylex.rrHandler(yyS[yypt-0].rr) {
				goto ret0
			}
		}
	case 49:
		{
			if !yylex.rrHandler(yyS[yypt-0].rr) {
				goto ret0
			}
		}
	case 50:
		{
			yyS[yypt-0].rr.Name = "@"
			if !yylex.rrHandler(yyS[yypt-0].rr) {
				goto ret0
			}
		}
	case 51:
		{
			yyVAL.rrData = &rr.LOC{0, byte(yyS[yypt-0].uint >> 16), byte(yyS[yypt-0].uint >> 8), byte(yyS[yypt-0].uint), uint32(yyS[yypt-3].u64), uint32(yyS[yypt-2].u64), uint32(yyS[yypt-1].u64)}
		}
	case 52:
		{
			yyVAL.uint = uint((*rr.LOC)(nil).EncPrec(100))<<16 | uint((*rr.LOC)(nil).EncPrec(1000000))<<8 | uint((*rr.LOC)(nil).EncPrec(1000))

		}
	case 53:
		{
			yyVAL.uint = uint((*rr.LOC)(nil).EncPrec(yyS[yypt-1].u64))<<16 | yyS[yypt-0].uint
		}
	case 54:
		{
			yyVAL.uint = uint((*rr.LOC)(nil).EncPrec(1000000))<<8 | uint((*rr.LOC)(nil).EncPrec(1000))
		}
	case 55:
		{
			yyVAL.uint = uint((*rr.LOC)(nil).EncPrec(yyS[yypt-1].u64))<<8 | yyS[yypt-0].uint
		}
	case 56:
		{
			yyVAL.uint = uint((*rr.LOC)(nil).EncPrec(1000))
		}
	case 57:
		{
			yyVAL.uint = uint((*rr.LOC)(nil).EncPrec(yyS[yypt-0].u64))
		}
	case 58:
		{
			yyVAL.u64 = 100*yyS[yypt-2].u64 + yyS[yypt-1].u64
		}
	case 59:
		{
			yyVAL.u64 = 0
		}
	case 60:
		{
			for yyVAL.u64 = uint64(yyS[yypt-0].uint); yyVAL.u64 != 0 && yyVAL.u64 < 10; yyVAL.u64 *= 10 {
			}
		}
	case 61:
		{
			x := (int64(yyS[yypt-1].u64) + 100*int64(yyS[yypt-2].int)) * int64(yyS[yypt-3].int)
			yyVAL.u64 = uint64(x + 10000000)
		}
	case 64:
		{
			yyVAL.u64 = 0
		}
	case 65:
		{
			for yyVAL.u64 = uint64(yyS[yypt-0].uint); yyVAL.u64 != 0 && yyVAL.u64 < 10; yyVAL.u64 *= 10 {
			}
		}
	case 66:
		{
			yyVAL.int = 1
		}
	case 67:
		{
			yyVAL.int = 1
		}
	case 68:
		{
			yyVAL.int = -1
		}
	case 69:
		{
			yylex.begin(sc_NUM)
		}
	case 70:
		{
			ts := yyS[yypt-1].u64 % 60000
			m := (yyS[yypt-1].u64 / 60000) % 60
			yyVAL.u64 = uint64((*rr.LOC)(nil).EncDMTS(int(yyS[yypt-2].uint), int(m), int(ts), yyS[yypt-0].int != 0))
		}
	case 71:
		{
			yylex.begin(sc_NUM)
		}
	case 72:
		{
			ts := yyS[yypt-1].u64 % 60000
			m := (yyS[yypt-1].u64 / 60000) % 60
			yyVAL.u64 = uint64((*rr.LOC)(nil).EncDMTS(int(yyS[yypt-2].uint), int(m), int(ts), yyS[yypt-0].int != 0))
		}
	case 73:
		{
			yyVAL.int = 1
		}
	case 74:
		{
			yyVAL.int = 0
		}
	case 75:
		{
			yyVAL.int = 1
		}
	case 76:
		{
			yyVAL.int = 0
		}
	case 77:
		{
			yyVAL.u64 = 0
		}
	case 78:
		{
			yyVAL.u64 = 60000*uint64(yyS[yypt-1].uint) + yyS[yypt-0].u64
		}
	case 79:
		{
			yyVAL.u64 = 0
		}
	case 80:
		{
			yyVAL.u64 = 1000*uint64(yyS[yypt-1].uint) + yyS[yypt-0].u64
		}
	case 81:
		{
			yyVAL.u64 = 0
		}
	case 82:
		{
			for yyVAL.u64 = uint64(yyS[yypt-0].uint); yyVAL.u64 != 0 && yyVAL.u64 < 100; yyVAL.u64 *= 10 {
			}
		}
	case 83:
		{
			yylex.begin(sc_DOMAIN)
		}
	case 84:
		{
			yyVAL.rrData = &rr.MB{yyS[yypt-0].str}
		}
	case 85:
		{
			yylex.begin(sc_DOMAIN)
		}
	case 86:
		{
			yyVAL.rrData = &rr.MD{yyS[yypt-0].str}
		}
	case 87:
		{
			yylex.begin(sc_DOMAIN)
		}
	case 88:
		{
			yyVAL.rrData = &rr.MF{yyS[yypt-0].str}
		}
	case 89:
		{
			yylex.begin(sc_DOMAIN)
		}
	case 90:
		{
			yyVAL.rrData = &rr.MG{yyS[yypt-0].str}
		}
	case 91:
		{
			yylex.begin(sc_DOMAIN)
		}
	case 92:
		{
			yyVAL.rrData = &rr.MINFO{yyS[yypt-1].str, yyS[yypt-0].str}
		}
	case 93:
		{
			yylex.begin(sc_DOMAIN)
		}
	case 94:
		{
			yyVAL.rrData = &rr.MR{yyS[yypt-0].str}
		}
	case 95:
		{
			yylex.begin(sc_NUM)
		}
	case 96:
		{
			yylex.begin(sc_DOMAIN)
		}
	case 97:
		{
			yyVAL.rrData = &rr.MX{uint16(yyS[yypt-2].uint), yyS[yypt-0].str}
		}
	case 98:
		{
			yylex.begin(sc_NUM)
		}
	case 99:
		{
			yylex.begin(sc_ANY_DOMAIN)
		}
	case 100:
		{
			yyVAL.rrData = &rr.NAPTR{uint16(yyS[yypt-6].uint), uint16(yyS[yypt-5].uint), yyS[yypt-4].str, yyS[yypt-3].str, yyS[yypt-2].str, yyS[yypt-0].str}
		}
	case 101:
		{
			yylex.begin(sc_DOMAIN)
		}
	case 102:
		{
			yyVAL.rrData = &rr.NS{yyS[yypt-0].str}
		}
	case 103:
		{
			yylex.begin(sc_0XHEX)
		}
	case 104:
		{
			yyVAL.rrData = &rr.NSAP{yyS[yypt-0].data}
		}
	case 105:
		{
			yylex.begin(sc_DOMAIN)
		}
	case 106:
		{
			yyVAL.rrData = &rr.NSAP_PTR{yyS[yypt-0].str}
		}
	case 107:
		{
			yylex.begin(sc_NUM)
		}
	case 108:
		{
			yylex.begin(sc_TYPE)
		}
	case 109:
		{
			yyVAL.rrData = &rr.NSEC3{rr.NSEC3PARAM{rr.HashAlgorithm(yyS[yypt-6].uint), byte(yyS[yypt-5].uint), uint16(yyS[yypt-4].uint), yyS[yypt-3].data}, yyS[yypt-2].data, rr.TypesEncode(yyS[yypt-0].types)}
		}
	case 110:
		{
			yylex.begin(sc_NUM)
		}
	case 111:
		{
			yyVAL.rrData = &rr.NSEC3PARAM{rr.HashAlgorithm(yyS[yypt-3].uint), byte(yyS[yypt-2].uint), uint16(yyS[yypt-1].uint), yyS[yypt-0].data}
		}
	case 112:
		{
			yylex.begin(sc_NUM)
		}
	case 113:
		{
			yyVAL.rrData = yyS[yypt-0].rrData
		}
	case 114:
		{
			if int(yyS[yypt-1].uint) != len(yyS[yypt-0].data) {
				yylex.Error(fmt.Sprintf("mismatched data len: %d != %d", yyS[yypt-1].uint, len(yyS[yypt-0].data)))
			}
			yyVAL.rrData = &rr.NULL{yyS[yypt-0].data}
		}
	case 115:
		{
			yyVAL.rrData = &rr.NULL{[]byte{}}
		}
	case 116:
		{
			yylex.begin(sc_DOMAIN)
		}
	case 117:
		{
			yyVAL.rrData = &rr.PTR{yyS[yypt-0].str}
		}
	case 118:
		{
			yylex.begin(sc_NUM)
		}
	case 119:
		{
			yylex.begin(sc_DOMAIN)
		}
	case 120:
		{
			yyVAL.rrData = &rr.PX{uint16(yyS[yypt-3].uint), yyS[yypt-1].str, yyS[yypt-0].str}
		}
	case 121:
		{
			yylex.begin(sc_DOMAIN)
		}
	case 122:
		{
			yyVAL.rrData = &rr.RP{yyS[yypt-1].str, yyS[yypt-0].str}
		}
	case 123:
		{
			yylex.begin(sc_RRHEAD)
		}
	case 124:
		{
			yyVAL.rr = yyS[yypt-0].rr
		}
	case 125:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_SRV, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 126:
		{
			yylex.begin(sc_RRHEAD)
		}
	case 127:
		{
			yyVAL.rr = yyS[yypt-0].rr
		}
	case 128:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_A, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 129:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_AAAA, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 130:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_AFSDB, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 131:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_CERT, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 132:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_CNAME, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 133:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_DNAME, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 134:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_DNSKEY, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 135:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_DS, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 136:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_IPSECKEY, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 137:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_KEY, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 138:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_KX, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 139:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_LOC, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 140:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_MB, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 141:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_MD, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 142:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_MF, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 143:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_MG, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 144:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_MINFO, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 145:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_MR, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 146:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_MX, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 147:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_NAPTR, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 148:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_NS, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 149:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_NSAP, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 150:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_NSAP_PTR, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 151:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_NSEC3, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 152:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_NSEC3PARAM, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 153:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_NULL, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 154:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_PTR, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 155:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_PX, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 156:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_RP, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 157:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_RRSIG, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 158:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_RT, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 159:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_SIG, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 160:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_SOA, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 161:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_SSHFP, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 162:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_GPOS, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 163:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_HINFO, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 164:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_ISDN, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 165:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_TXT, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 166:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_WKS, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 167:
		{
			yyVAL.rr = &rr.RR{"", rr.TYPE_X25, yyS[yypt-1].rrh.class, yyS[yypt-1].rrh.ttl, yyS[yypt-0].rrData}
		}
	case 168:
		{
			yyVAL.rrh = rrHead{int32(yyS[yypt-1].int), yyS[yypt-0].class}
		}
	case 169:
		{
			yyVAL.rrh = rrHead{int32(yyS[yypt-0].int), yyS[yypt-1].class}
		}
	case 170:
		{
			yyVAL.rrh = rrHead{int32(yyS[yypt-0].int), 0}
		}
	case 171:
		{
			yyVAL.rrh = rrHead{-1, yyS[yypt-0].class}
		}
	case 172:
		{
			yylex.begin(sc_NUM)
		}
	case 173:
		{
			yylex.begin(sc_DOMAIN)
		}
	case 174:
		{
			yyVAL.rrData = &rr.RRSIG{yyS[yypt-10].typ, yyS[yypt-8].alg, byte(yyS[yypt-7].uint), int32(yyS[yypt-6].int), uint32(yyS[yypt-5].uint), uint32(yyS[yypt-4].uint), uint16(yyS[yypt-3].uint), yyS[yypt-1].str, yyS[yypt-0].data}
		}
	case 175:
		{
			yylex.begin(sc_TYPE)
		}
	case 176:
		{
			yyVAL.typ = yyS[yypt-0].typ
		}
	case 177:
		{
			yyVAL.types = nil
			yylex.begin(sc_INITIAL)
		}
	case 178:
		{
			yyVAL.types = []rr.Type{yyS[yypt-0].typ}
		}
	case 179:
		{
			yyVAL.types = append(yyVAL.types, yyS[yypt-0].typ)
		}
	case 180:
		{
			yyVAL.typ = rr.TYPE_A
		}
	case 181:
		{
			yyVAL.typ = rr.TYPE_A6
		}
	case 182:
		{
			yyVAL.typ = rr.TYPE_AAAA
		}
	case 183:
		{
			yyVAL.typ = rr.TYPE_AFSDB
		}
	case 184:
		{
			yyVAL.typ = rr.TYPE_ATMA
		}
	case 185:
		{
			yyVAL.typ = rr.TYPE_APL
		}
	case 186:
		{
			yyVAL.typ = rr.TYPE_CDS
		}
	case 187:
		{
			yyVAL.typ = rr.TYPE_CERT
		}
	case 188:
		{
			yyVAL.typ = rr.TYPE_CNAME
		}
	case 189:
		{
			yyVAL.typ = rr.TYPE_DHCID
		}
	case 190:
		{
			yyVAL.typ = rr.TYPE_DNAME
		}
	case 191:
		{
			yyVAL.typ = rr.TYPE_DNSKEY
		}
	case 192:
		{
			yyVAL.typ = rr.TYPE_DS
		}
	case 193:
		{
			yyVAL.typ = rr.TYPE_EID
		}
	case 194:
		{
			yyVAL.typ = rr.TYPE_GID
		}
	case 195:
		{
			yyVAL.typ = rr.TYPE_GPOS
		}
	case 196:
		{
			yyVAL.typ = rr.TYPE_HINFO
		}
	case 197:
		{
			yyVAL.typ = rr.TYPE_MINFO
		}
	case 198:
		{
			yyVAL.typ = rr.TYPE_HIP
		}
	case 199:
		{
			yyVAL.typ = rr.TYPE_IPSECKEY
		}
	case 200:
		{
			yyVAL.typ = rr.TYPE_ISDN
		}
	case 201:
		{
			yyVAL.typ = rr.TYPE_KEY
		}
	case 202:
		{
			yyVAL.typ = rr.TYPE_KX
		}
	case 203:
		{
			yyVAL.typ = rr.TYPE_LOC
		}
	case 204:
		{
			yyVAL.typ = rr.TYPE_MB
		}
	case 205:
		{
			yyVAL.typ = rr.TYPE_MD
		}
	case 206:
		{
			yyVAL.typ = rr.TYPE_MF
		}
	case 207:
		{
			yyVAL.typ = rr.TYPE_MR
		}
	case 208:
		{
			yyVAL.typ = rr.TYPE_MX
		}
	case 209:
		{
			yyVAL.typ = rr.TYPE_NAPTR
		}
	case 210:
		{
			yyVAL.typ = rr.TYPE_NIMLOC
		}
	case 211:
		{
			yyVAL.typ = rr.TYPE_NINFO
		}
	case 212:
		{
			yyVAL.typ = rr.TYPE_NS
		}
	case 213:
		{
			yyVAL.typ = rr.TYPE_NSAP
		}
	case 214:
		{
			yyVAL.typ = rr.TYPE_NSAP_PTR
		}
	case 215:
		{
			yyVAL.typ = rr.TYPE_NSEC
		}
	case 216:
		{
			yyVAL.typ = rr.TYPE_NSEC3
		}
	case 217:
		{
			yyVAL.typ = rr.TYPE_NSEC3PARAM
		}
	case 218:
		{
			yyVAL.typ = rr.TYPE_NXT
		}
	case 219:
		{
			yyVAL.typ = rr.TYPE_NULL
		}
	case 220:
		{
			yyVAL.typ = rr.TYPE_PTR
		}
	case 221:
		{
			yyVAL.typ = rr.TYPE_PX
		}
	case 222:
		{
			yyVAL.typ = rr.TYPE_RRSIG
		}
	case 223:
		{
			yyVAL.typ = rr.TYPE_RKEY
		}
	case 224:
		{
			yyVAL.typ = rr.TYPE_RP
		}
	case 225:
		{
			yyVAL.typ = rr.TYPE_RT
		}
	case 226:
		{
			yyVAL.typ = rr.TYPE_SIG
		}
	case 227:
		{
			yyVAL.typ = rr.TYPE_SOA
		}
	case 228:
		{
			yyVAL.typ = rr.TYPE_SPF
		}
	case 229:
		{
			yyVAL.typ = rr.TYPE_SRV
		}
	case 230:
		{
			yyVAL.typ = rr.TYPE_SSHFP
		}
	case 231:
		{
			yyVAL.typ = rr.TYPE_TALINK
		}
	case 232:
		{
			yyVAL.typ = rr.TYPE_TKEY
		}
	case 233:
		{
			yyVAL.typ = rr.TYPE_TSIG
		}
	case 234:
		{
			yyVAL.typ = rr.TYPE_TXT
		}
	case 235:
		{
			yyVAL.typ = rr.TYPE_UID
		}
	case 236:
		{
			yyVAL.typ = rr.TYPE_UINFO
		}
	case 237:
		{
			yyVAL.typ = rr.TYPE_UNSPEC
		}
	case 238:
		{
			yyVAL.typ = rr.TYPE_WKS
		}
	case 239:
		{
			yyVAL.typ = rr.TYPE_X25
		}
	case 240:
		{
			yylex.begin(sc_NUM)
		}
	case 241:
		{
			yylex.begin(sc_DOMAIN)
		}
	case 242:
		{
			yyVAL.rrData = &rr.RT{uint16(yyS[yypt-2].uint), yyS[yypt-0].str}
		}
	case 243:
		{
			yylex.begin(sc_NUM)
		}
	case 244:
		{
			yylex.begin(sc_DOMAIN)
		}
	case 245:
		{
			yyVAL.rrData = &rr.SIG{yyS[yypt-10].typ, yyS[yypt-8].alg, byte(yyS[yypt-7].uint), int32(yyS[yypt-6].int), uint32(yyS[yypt-5].uint), uint32(yyS[yypt-4].uint), uint16(yyS[yypt-3].uint), yyS[yypt-1].str, yyS[yypt-0].data}
		}
	case 246:
		{
			yylex.begin(sc_DOMAIN)
		}
	case 247:
		{
			yylex.begin(sc_NUM)
		}
	case 248:
		{
			yyVAL.rrData = &rr.SOA{yyS[yypt-7].str, yyS[yypt-6].str, uint32(yyS[yypt-4].uint), uint32(yyS[yypt-3].uint), uint32(yyS[yypt-2].uint), uint32(yyS[yypt-1].uint), uint32(yyS[yypt-0].uint)}
		}
	case 249:
		{
			yylex.begin(sc_NUM)
		}
	case 250:
		{
			yylex.begin(sc_DOMAIN)
		}
	case 251:
		{
			yyVAL.rrData = &rr.SRV{uint16(yyS[yypt-4].uint), uint16(yyS[yypt-3].uint), uint16(yyS[yypt-2].uint), yyS[yypt-0].str}
		}
	case 252:
		{
			yylex.begin(sc_NUM)
		}
	case 253:
		{
			yyVAL.rrData = &rr.SSHFP{rr.SSHFPAlgorithm(yyS[yypt-2].uint), rr.SSHFPType(yyS[yypt-1].uint), yyS[yypt-0].data}
		}
	case 254:
		yyVAL.int = yyS[yypt-0].int
	case 255:
		{
			yyVAL.rrData = &rr.TXT{yyS[yypt-0].str}
		}
	case 256:
		{
			yyVAL.str = ""
		}
	case 257:
		{
			yyVAL.str += yyS[yypt-0].str
		}
	case 258:
		{
			yylex.begin(sc_FLOAT)
		}
	case 259:
		{
			yyVAL.rrData = &rr.GPOS{yyS[yypt-2].float, yyS[yypt-1].float, yyS[yypt-0].float}
		}
	case 260:
		{
			yyVAL.rrData = &rr.HINFO{yyS[yypt-1].str, yyS[yypt-0].str}
		}
	case 261:
		{
			yyVAL.rrData = &rr.ISDN{yyS[yypt-0].str, ""}
		}
	case 262:
		{
			yyVAL.rrData = &rr.ISDN{yyS[yypt-1].str, yyS[yypt-0].str}
		}
	case 263:
		{
			if yyS[yypt-0].u64 > math.MaxUint8 {
				yylex.Error("number out of range")
				yyVAL.uint = math.MaxUint8
			} else {
				yyVAL.uint = uint(yyS[yypt-0].u64)
			}
		}
	case 264:
		{
			if yyS[yypt-0].u64 > math.MaxUint16 {
				yylex.Error("number out of range")
				yyVAL.uint = math.MaxUint16
			} else {
				yyVAL.uint = uint(yyS[yypt-0].u64)
			}
		}
	case 265:
		{
			if yyS[yypt-0].u64 > math.MaxInt32 {
				yylex.Error("number out of range")
				yyVAL.int = math.MaxInt32
			} else {
				yyVAL.int = int(yyS[yypt-0].u64)
			}
		}
	case 266:
		{
			if yyS[yypt-0].u64 > math.MaxUint32 {
				yylex.Error("number out of range")
				yyVAL.uint = math.MaxUint32
			} else {
				yyVAL.uint = uint(yyS[yypt-0].u64)
			}
		}
	case 267:
		{
			yylex.begin(sc_IPV4)
		}
	case 268:
		{
			yylex.begin(sc_PROTO)
		}
	case 269:
		{
			yylex.begin(sc_PORT)
		}
	case 270:
		{
			x := &rr.WKS{yyS[yypt-4].ip, rr.IP_Protocol(yyS[yypt-2].int), map[rr.IP_Port]struct{}{}}
			for i, v := range yyS[yypt-0].data {
				for j := 8 * i; v != 0; j, v = j+1, v>>1 {
					if v&1 != 0 {
						x.Ports[rr.IP_Port(j)] = struct{}{}
					}
				}
			}
			yyVAL.rrData = x
		}
	case 275:
		{
			yyVAL.data = make([]byte, 128)
		}
	case 276:
		{
			i := rr.IP_Port(yyS[yypt-0].int)
			yyVAL.data[i>>3] |= 1 << uint(i&7)
		}
	case 277:
		{
			yyVAL.rrData = &rr.X25{yyS[yypt-0].str}
		}
	}
	goto yystack /* stack new state and value */
}
