// Copyright (c) 2011 CZ.NIC z.s.p.o. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// blame: jnml, labs.nic.cz

// WARNING: If this file is scanner.go then DO NOT EDIT.
// scanner.go is generated by golex from scanner.l (see the Makefile).

package zone

import (
	"bufio"
	"bytes"
	"encoding/hex"
	"errors"
	"fmt"
	"github.com/cznic/dns/rr"
	"io"
	"net"
	"strconv"
	"strings"
	"unicode"
)

type lexStackItem struct {
	rrHandler  func(*rr.RR) bool
	errHandler func(e string) bool
	startCond  int
	buf        []byte
	last       byte
	peek       byte
	line       int
	column     int
	name       string
	src        *bufio.Reader
	prev       *lexStackItem
	inParen    bool
}

type lex struct {
	lexStackItem
}

func (l *lex) include(name string, source *bufio.Reader) {
	push := &lexStackItem{}
	*push = l.lexStackItem
	l.buf = nil
	l.line = 1
	l.column = 0
	l.name = name
	l.src = source
	l.prev = push
	l.getc(0)
}

func (l *lex) getc(c byte) byte {
	if c != 0 {
		l.buf = append(l.buf, c)
	}
	l.last = l.peek
	if b, err := l.src.ReadByte(); err == nil {
		if b == '\n' {
			l.line++
			l.column = 0
		} else {
			l.column++
		}
		l.peek = b
		return b
	} else {
		if err == io.EOF {
			l.peek = 0
			return 0
		}
		panic(err)
	}

	panic("unreachable")
}

func newLex(name string, source *bufio.Reader, errHandler func(e string) bool, rrHandler func(*rr.RR) bool) (l *lex) {
	l = &lex{}
	l.errHandler = errHandler
	l.rrHandler = rrHandler
	l.line = 1
	l.name = name
	l.src = source
	l.getc(0)
	return
}

func (l *lex) Error(e string) {
	e = fmt.Sprintf("%s:%d:%d - %s", l.name, l.line, l.column, e)
	if l.errHandler != nil {
		if l.errHandler(e) {
			return
		}
	}
	panic(errors.New(e))
}

func (l *lex) begin(sc int) {
	l.startCond = sc
}

const (
	sc_INITIAL    = iota // 0
	sc_RRHEAD            // 1
	sc_DOMAIN            // 2
	sc_NUM               // 3
	sc_IPV4              // 4
	sc_IPV6              // 5
	sc_BASE32EXT         // 6
	sc_BASE64            // 7
	sc_TYPE              // 8
	sc_HEX               // 9
	sc_PROTO             // 10
	sc_PORT              // 11
	sc_0XHEX             // 12
	sc_FLOAT             // 13
	sc_ANY_DOMAIN        // 14
)

func (l *lex) Lex(lval *yySymType) (ret int) {
	var err error

	/* debug helper
	defer func(sc0 int) {
		var s string
		switch {
		case ret < 127:
			s = fmt.Sprintf("%q", rune(ret))
		default:
			i := ret-0xe002
			if i < len(yyToknames) {
				s = yyToknames[ret-0xe002]
				break
			}
			s = fmt.Sprintf("?%d?", ret)
		}
		fmt.Printf("*lex.Lex() %s:%d:%d - %d %q %s buf %q, sc %d->%d\n", l.name, l.line, l.column, ret, string(ret), s, l.buf, sc0, l.startCond)
	}(l.startCond) //*/

	c := l.peek
	ret = -1

yystate0:

	if ret >= 0 {
		lval.str = string(l.buf)
		return
	}
	l.buf = l.buf[:0]

	switch yyt, yyb := l.startCond, l.last == '\n' || l.last == 0; yyt {
	default:
		panic(fmt.Errorf(`invalid start condition %d`, yyt))
	case 6: // start condition: base32ext
		if yyb {
			goto yystart287
		}
		goto yystart310
	case 10: // start condition: proto
		if yyb {
			goto yystart289
		}
		goto yystart311
	case 14: // start condition: anydomain
		if yyb {
			goto yystart296
		}
		goto yystart312
	case 3: // start condition: num
		if yyb {
			goto yystart313
		}
		goto yystart324
	case 7: // start condition: base64
		if yyb {
			goto yystart314
		}
		goto yystart325
	case 11: // start condition: port
		if yyb {
			goto yystart316
		}
		goto yystart326
	case 0: // start condition: INITIAL
		if yyb {
			goto yystart1
		}
		goto yystart242
	case 4: // start condition: ipv4
		if yyb {
			goto yystart46
		}
		goto yystart243
	case 8: // start condition: type
		if yyb {
			goto yystart64
		}
		goto yystart244
	case 12: // start condition: xhex
		if yyb {
			goto yystart238
		}
		goto yystart245
	case 1: // start condition: rrHead
		if yyb {
			goto yystart246
		}
		goto yystart278
	case 5: // start condition: ipv6
		if yyb {
			goto yystart254
		}
		goto yystart279
	case 9: // start condition: hex
		if yyb {
			goto yystart267
		}
		goto yystart280
	case 13: // start condition: float
		if yyb {
			goto yystart270
		}
		goto yystart281
	case 2: // start condition: domain
		if yyb {
			goto yystart282
		}
		goto yystart309
	}

	goto yystate1 // silence unused label error
yystate1:
	c = l.getc(c)
yystart1:
	switch {
	default:
		goto yyabort
	case c == '(':
		goto yystate44
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate2
	case c == '"':
		goto yystate5
	case c == ')':
		goto yystate45
	case c == ';':
		goto yystate10
	case c == '\t' || c == ' ':
		goto yystate8
	case c == '_':
		goto yystate13
	case c == '\n' || c == '\r':
		goto yystate11
	case c == '\\':
		goto yystate25
	case c == '.':
		goto yystate12
	case c == '$':
		goto yystate27
	}

yystate2:
	c = l.getc(c)
	switch {
	default:
		goto yyrule10
	case c == '.':
		goto yystate4
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate2
	case c == '-':
		goto yystate3
	}

yystate3:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate2
	case c == '-':
		goto yystate3
	}

yystate4:
	c = l.getc(c)
	switch {
	default:
		goto yyrule10
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate2
	}

yystate5:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == '"':
		goto yystate6
	case c == '\\':
		goto yystate7
	case c >= '\x01' && c <= '\t' || c == '\v' || c == '\f' || c >= '\x0e' && c <= '!' || c >= '#' && c <= '[' || c >= ']' && c <= 'ÿ':
		goto yystate5
	}

yystate6:
	c = l.getc(c)
	goto yyrule15

yystate7:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c >= '\x01' && c <= '\t' || c >= '\v' && c <= 'ÿ':
		goto yystate5
	}

yystate8:
	c = l.getc(c)
	switch {
	default:
		goto yyrule13
	case c == '\x00' || c == '\n':
		goto yystate9
	case c == ';':
		goto yystate10
	case c == '\t' || c == ' ':
		goto yystate8
	}

yystate9:
	goto yyrule1

yystate10:
	c = l.getc(c)
	switch {
	default:
		goto yyrule3
	case c >= '\x01' && c <= '\t' || c >= '\v' && c <= 'ÿ':
		goto yystate10
	}

yystate11:
	c = l.getc(c)
	goto yyrule7

yystate12:
	c = l.getc(c)
	goto yyrule10

yystate13:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate14
	}

yystate14:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == '.':
		goto yystate15
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate14
	case c == '-':
		goto yystate24
	}

yystate15:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == '_':
		goto yystate16
	}

yystate16:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate17
	}

yystate17:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == '-':
		goto yystate23
	case c == '.':
		goto yystate18
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate17
	}

yystate18:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == '.':
		goto yystate22
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate19
	}

yystate19:
	c = l.getc(c)
	switch {
	default:
		goto yyrule11
	case c == '.':
		goto yystate21
	case c == '-':
		goto yystate20
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate19
	}

yystate20:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate19
	case c == '-':
		goto yystate20
	}

yystate21:
	c = l.getc(c)
	switch {
	default:
		goto yyrule11
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate19
	}

yystate22:
	c = l.getc(c)
	goto yyrule11

yystate23:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate17
	case c == '-':
		goto yystate23
	}

yystate24:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate14
	case c == '-':
		goto yystate24
	}

yystate25:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == '#':
		goto yystate26
	}

yystate26:
	c = l.getc(c)
	goto yyrule14

yystate27:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'O':
		goto yystate28
	case c == 'I':
		goto yystate37
	case c == 'T':
		goto yystate34
	}

yystate28:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'R':
		goto yystate29
	}

yystate29:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'I':
		goto yystate30
	}

yystate30:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'G':
		goto yystate31
	}

yystate31:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'I':
		goto yystate32
	}

yystate32:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'N':
		goto yystate33
	}

yystate33:
	c = l.getc(c)
	goto yyrule5

yystate34:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'T':
		goto yystate35
	}

yystate35:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'L':
		goto yystate36
	}

yystate36:
	c = l.getc(c)
	goto yyrule6

yystate37:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'N':
		goto yystate38
	}

yystate38:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'C':
		goto yystate39
	}

yystate39:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'L':
		goto yystate40
	}

yystate40:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'U':
		goto yystate41
	}

yystate41:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'D':
		goto yystate42
	}

yystate42:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'E':
		goto yystate43
	}

yystate43:
	c = l.getc(c)
	goto yyrule4

yystate44:
	c = l.getc(c)
	goto yyrule8

yystate45:
	c = l.getc(c)
	goto yyrule9

	goto yystate46 // silence unused label error
yystate46:
	c = l.getc(c)
yystart46:
	switch {
	default:
		goto yyabort
	case c == '(':
		goto yystate44
	case c == '"':
		goto yystate5
	case c == ')':
		goto yystate45
	case c == ';':
		goto yystate10
	case c >= '0' && c <= '9':
		goto yystate47
	case c == '\n' || c == '\r':
		goto yystate11
	case c == '\t' || c == ' ':
		goto yystate62
	case c == '\\':
		goto yystate25
	}

yystate47:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == '.':
		goto yystate50
	case c >= '0' && c <= '9':
		goto yystate48
	}

yystate48:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == '.':
		goto yystate50
	case c >= '0' && c <= '9':
		goto yystate49
	}

yystate49:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == '.':
		goto yystate50
	}

yystate50:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9':
		goto yystate51
	}

yystate51:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == '.':
		goto yystate54
	case c >= '0' && c <= '9':
		goto yystate52
	}

yystate52:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9':
		goto yystate53
	case c == '.':
		goto yystate54
	}

yystate53:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == '.':
		goto yystate54
	}

yystate54:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9':
		goto yystate55
	}

yystate55:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == '.':
		goto yystate57
	case c >= '0' && c <= '9':
		goto yystate56
	}

yystate56:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == '.':
		goto yystate57
	case c >= '0' && c <= '9':
		goto yystate61
	}

yystate57:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9':
		goto yystate58
	}

yystate58:
	c = l.getc(c)
	switch {
	default:
		goto yyrule83
	case c >= '0' && c <= '9':
		goto yystate59
	}

yystate59:
	c = l.getc(c)
	switch {
	default:
		goto yyrule83
	case c >= '0' && c <= '9':
		goto yystate60
	}

yystate60:
	c = l.getc(c)
	goto yyrule83

yystate61:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == '.':
		goto yystate57
	}

yystate62:
	c = l.getc(c)
	switch {
	default:
		goto yyrule17
	case c == '\t' || c == ' ':
		goto yystate62
	case c == '\x00' || c == '\n':
		goto yystate63
	case c == ';':
		goto yystate10
	}

yystate63:
	goto yyrule2

	goto yystate64 // silence unused label error
yystate64:
	c = l.getc(c)
yystart64:
	switch {
	default:
		goto yyabort
	case c == 'A':
		goto yystate109
	case c == 'U':
		goto yystate148
	case c == 'G':
		goto yystate212
	case c == '"':
		goto yystate5
	case c == 'N':
		goto yystate159
	case c == 'P':
		goto yystate88
	case c == 'I':
		goto yystate126
	case c == 'H':
		goto yystate79
	case c == 'S':
		goto yystate222
	case c == 'T':
		goto yystate92
	case c == 'L':
		goto yystate85
	case c == 'K':
		goto yystate218
	case c == 'D':
		goto yystate65
	case c == ')':
		goto yystate45
	case c == 'W':
		goto yystate235
	case c == ';':
		goto yystate10
	case c == 'C':
		goto yystate202
	case c == 'M':
		goto yystate137
	case c == '\n' || c == '\r':
		goto yystate11
	case c == 'E':
		goto yystate123
	case c == 'X':
		goto yystate106
	case c == '\t' || c == ' ':
		goto yystate62
	case c == '\\':
		goto yystate25
	case c == 'R':
		goto yystate192
	case c == '(':
		goto yystate44
	}

yystate65:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'S':
		goto yystate78
	case c == 'N':
		goto yystate70
	case c == 'H':
		goto yystate66
	}

yystate66:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'C':
		goto yystate67
	}

yystate67:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'I':
		goto yystate68
	}

yystate68:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'D':
		goto yystate69
	}

yystate69:
	c = l.getc(c)
	goto yyrule31

yystate70:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'S':
		goto yystate71
	case c == 'A':
		goto yystate75
	}

yystate71:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'K':
		goto yystate72
	}

yystate72:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'E':
		goto yystate73
	}

yystate73:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'Y':
		goto yystate74
	}

yystate74:
	c = l.getc(c)
	goto yyrule33

yystate75:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'M':
		goto yystate76
	}

yystate76:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'E':
		goto yystate77
	}

yystate77:
	c = l.getc(c)
	goto yyrule32

yystate78:
	c = l.getc(c)
	goto yyrule34

yystate79:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'I':
		goto yystate80
	}

yystate80:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'N':
		goto yystate81
	case c == 'P':
		goto yystate84
	}

yystate81:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'F':
		goto yystate82
	}

yystate82:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'O':
		goto yystate83
	}

yystate83:
	c = l.getc(c)
	goto yyrule38

yystate84:
	c = l.getc(c)
	goto yyrule39

yystate85:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'O':
		goto yystate86
	}

yystate86:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'C':
		goto yystate87
	}

yystate87:
	c = l.getc(c)
	goto yyrule44

yystate88:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'T':
		goto yystate89
	case c == 'X':
		goto yystate91
	}

yystate89:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'R':
		goto yystate90
	}

yystate90:
	c = l.getc(c)
	goto yyrule63

yystate91:
	c = l.getc(c)
	goto yyrule64

yystate92:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'S':
		goto yystate103
	case c == 'A':
		goto yystate95
	case c == 'K':
		goto yystate100
	case c == 'X':
		goto yystate93
	}

yystate93:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'T':
		goto yystate94
	}

yystate94:
	c = l.getc(c)
	goto yyrule77

yystate95:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'L':
		goto yystate96
	}

yystate96:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'I':
		goto yystate97
	}

yystate97:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'N':
		goto yystate98
	}

yystate98:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'K':
		goto yystate99
	}

yystate99:
	c = l.getc(c)
	goto yyrule74

yystate100:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'E':
		goto yystate101
	}

yystate101:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'Y':
		goto yystate102
	}

yystate102:
	c = l.getc(c)
	goto yyrule75

yystate103:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'I':
		goto yystate104
	}

yystate104:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'G':
		goto yystate105
	}

yystate105:
	c = l.getc(c)
	goto yyrule76

yystate106:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == '2':
		goto yystate107
	}

yystate107:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == '5':
		goto yystate108
	}

yystate108:
	c = l.getc(c)
	goto yyrule82

yystate109:
	c = l.getc(c)
	switch {
	default:
		goto yyrule22
	case c == 'P':
		goto yystate111
	case c == '6':
		goto yystate110
	case c == 'T':
		goto yystate113
	case c == 'A':
		goto yystate116
	case c == 'F':
		goto yystate119
	}

yystate110:
	c = l.getc(c)
	goto yyrule23

yystate111:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'L':
		goto yystate112
	}

yystate112:
	c = l.getc(c)
	goto yyrule26

yystate113:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'M':
		goto yystate114
	}

yystate114:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'A':
		goto yystate115
	}

yystate115:
	c = l.getc(c)
	goto yyrule27

yystate116:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'A':
		goto yystate117
	}

yystate117:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'A':
		goto yystate118
	}

yystate118:
	c = l.getc(c)
	goto yyrule24

yystate119:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'S':
		goto yystate120
	}

yystate120:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'D':
		goto yystate121
	}

yystate121:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'B':
		goto yystate122
	}

yystate122:
	c = l.getc(c)
	goto yyrule25

yystate123:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'I':
		goto yystate124
	}

yystate124:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'D':
		goto yystate125
	}

yystate125:
	c = l.getc(c)
	goto yyrule35

yystate126:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'P':
		goto yystate130
	case c == 'S':
		goto yystate127
	}

yystate127:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'D':
		goto yystate128
	}

yystate128:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'N':
		goto yystate129
	}

yystate129:
	c = l.getc(c)
	goto yyrule41

yystate130:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'S':
		goto yystate131
	}

yystate131:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'E':
		goto yystate132
	}

yystate132:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'C':
		goto yystate133
	}

yystate133:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'K':
		goto yystate134
	}

yystate134:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'E':
		goto yystate135
	}

yystate135:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'Y':
		goto yystate136
	}

yystate136:
	c = l.getc(c)
	goto yyrule40

yystate137:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'I':
		goto yystate141
	case c == 'X':
		goto yystate140
	case c == 'D':
		goto yystate139
	case c == 'G':
		goto yystate138
	case c == 'R':
		goto yystate147
	case c == 'F':
		goto yystate146
	case c == 'B':
		goto yystate145
	}

yystate138:
	c = l.getc(c)
	goto yyrule48

yystate139:
	c = l.getc(c)
	goto yyrule46

yystate140:
	c = l.getc(c)
	goto yyrule51

yystate141:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'N':
		goto yystate142
	}

yystate142:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'F':
		goto yystate143
	}

yystate143:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'O':
		goto yystate144
	}

yystate144:
	c = l.getc(c)
	goto yyrule49

yystate145:
	c = l.getc(c)
	goto yyrule45

yystate146:
	c = l.getc(c)
	goto yyrule47

yystate147:
	c = l.getc(c)
	goto yyrule50

yystate148:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'I':
		goto yystate154
	case c == 'N':
		goto yystate149
	}

yystate149:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'S':
		goto yystate150
	}

yystate150:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'P':
		goto yystate151
	}

yystate151:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'E':
		goto yystate152
	}

yystate152:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'C':
		goto yystate153
	}

yystate153:
	c = l.getc(c)
	goto yyrule80

yystate154:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'D':
		goto yystate158
	case c == 'N':
		goto yystate155
	}

yystate155:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'F':
		goto yystate156
	}

yystate156:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'O':
		goto yystate157
	}

yystate157:
	c = l.getc(c)
	goto yyrule79

yystate158:
	c = l.getc(c)
	goto yyrule78

yystate159:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'X':
		goto yystate175
	case c == 'I':
		goto yystate181
	case c == 'S':
		goto yystate160
	case c == 'U':
		goto yystate189
	case c == 'A':
		goto yystate177
	}

yystate160:
	c = l.getc(c)
	switch {
	default:
		goto yyrule55
	case c == 'A':
		goto yystate161
	case c == 'E':
		goto yystate167
	}

yystate161:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'P':
		goto yystate162
	}

yystate162:
	c = l.getc(c)
	switch {
	default:
		goto yyrule56
	case c == '-':
		goto yystate163
	}

yystate163:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'P':
		goto yystate164
	}

yystate164:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'T':
		goto yystate165
	}

yystate165:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'R':
		goto yystate166
	}

yystate166:
	c = l.getc(c)
	goto yyrule57

yystate167:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'C':
		goto yystate168
	}

yystate168:
	c = l.getc(c)
	switch {
	default:
		goto yyrule58
	case c == '3':
		goto yystate169
	}

yystate169:
	c = l.getc(c)
	switch {
	default:
		goto yyrule59
	case c == 'P':
		goto yystate170
	}

yystate170:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'A':
		goto yystate171
	}

yystate171:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'R':
		goto yystate172
	}

yystate172:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'A':
		goto yystate173
	}

yystate173:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'M':
		goto yystate174
	}

yystate174:
	c = l.getc(c)
	goto yyrule60

yystate175:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'T':
		goto yystate176
	}

yystate176:
	c = l.getc(c)
	goto yyrule62

yystate177:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'P':
		goto yystate178
	}

yystate178:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'T':
		goto yystate179
	}

yystate179:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'R':
		goto yystate180
	}

yystate180:
	c = l.getc(c)
	goto yyrule52

yystate181:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'M':
		goto yystate185
	case c == 'N':
		goto yystate182
	}

yystate182:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'F':
		goto yystate183
	}

yystate183:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'O':
		goto yystate184
	}

yystate184:
	c = l.getc(c)
	goto yyrule54

yystate185:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'L':
		goto yystate186
	}

yystate186:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'O':
		goto yystate187
	}

yystate187:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'C':
		goto yystate188
	}

yystate188:
	c = l.getc(c)
	goto yyrule53

yystate189:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'L':
		goto yystate190
	}

yystate190:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'L':
		goto yystate191
	}

yystate191:
	c = l.getc(c)
	goto yyrule61

yystate192:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'R':
		goto yystate195
	case c == 'P':
		goto yystate193
	case c == 'K':
		goto yystate199
	case c == 'T':
		goto yystate194
	}

yystate193:
	c = l.getc(c)
	goto yyrule66

yystate194:
	c = l.getc(c)
	goto yyrule68

yystate195:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'S':
		goto yystate196
	}

yystate196:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'I':
		goto yystate197
	}

yystate197:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'G':
		goto yystate198
	}

yystate198:
	c = l.getc(c)
	goto yyrule67

yystate199:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'E':
		goto yystate200
	}

yystate200:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'Y':
		goto yystate201
	}

yystate201:
	c = l.getc(c)
	goto yyrule65

yystate202:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'D':
		goto yystate210
	case c == 'N':
		goto yystate206
	case c == 'E':
		goto yystate203
	}

yystate203:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'R':
		goto yystate204
	}

yystate204:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'T':
		goto yystate205
	}

yystate205:
	c = l.getc(c)
	goto yyrule29

yystate206:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'A':
		goto yystate207
	}

yystate207:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'M':
		goto yystate208
	}

yystate208:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'E':
		goto yystate209
	}

yystate209:
	c = l.getc(c)
	goto yyrule30

yystate210:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'S':
		goto yystate211
	}

yystate211:
	c = l.getc(c)
	goto yyrule28

yystate212:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'I':
		goto yystate216
	case c == 'P':
		goto yystate213
	}

yystate213:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'O':
		goto yystate214
	}

yystate214:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'S':
		goto yystate215
	}

yystate215:
	c = l.getc(c)
	goto yyrule37

yystate216:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'D':
		goto yystate217
	}

yystate217:
	c = l.getc(c)
	goto yyrule36

yystate218:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'E':
		goto yystate220
	case c == 'X':
		goto yystate219
	}

yystate219:
	c = l.getc(c)
	goto yyrule43

yystate220:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'Y':
		goto yystate221
	}

yystate221:
	c = l.getc(c)
	goto yyrule42

yystate222:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'I':
		goto yystate223
	case c == 'P':
		goto yystate233
	case c == 'O':
		goto yystate227
	case c == 'R':
		goto yystate225
	case c == 'S':
		goto yystate229
	}

yystate223:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'G':
		goto yystate224
	}

yystate224:
	c = l.getc(c)
	goto yyrule69

yystate225:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'V':
		goto yystate226
	}

yystate226:
	c = l.getc(c)
	goto yyrule72

yystate227:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'A':
		goto yystate228
	}

yystate228:
	c = l.getc(c)
	goto yyrule70

yystate229:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'H':
		goto yystate230
	}

yystate230:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'F':
		goto yystate231
	}

yystate231:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'P':
		goto yystate232
	}

yystate232:
	c = l.getc(c)
	goto yyrule73

yystate233:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'F':
		goto yystate234
	}

yystate234:
	c = l.getc(c)
	goto yyrule71

yystate235:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'K':
		goto yystate236
	}

yystate236:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'S':
		goto yystate237
	}

yystate237:
	c = l.getc(c)
	goto yyrule81

	goto yystate238 // silence unused label error
yystate238:
	c = l.getc(c)
yystart238:
	switch {
	default:
		goto yyabort
	case c == ')':
		goto yystate45
	case c == ';':
		goto yystate10
	case c == '\n' || c == '\r':
		goto yystate11
	case c == '\t' || c == ' ':
		goto yystate62
	case c == '\\':
		goto yystate25
	case c == '(':
		goto yystate44
	case c == '"':
		goto yystate5
	case c == '0':
		goto yystate239
	}

yystate239:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'x':
		goto yystate240
	}

yystate240:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == '.' || c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate241
	}

yystate241:
	c = l.getc(c)
	switch {
	default:
		goto yyrule87
	case c == '.' || c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate241
	}

	goto yystate242 // silence unused label error
yystate242:
	c = l.getc(c)
yystart242:
	switch {
	default:
		goto yyabort
	case c == ')':
		goto yystate45
	case c == ';':
		goto yystate10
	case c == '\n' || c == '\r':
		goto yystate11
	case c == '\t' || c == ' ':
		goto yystate62
	case c == '\\':
		goto yystate25
	case c == '(':
		goto yystate44
	case c == '"':
		goto yystate5
	}

	goto yystate243 // silence unused label error
yystate243:
	c = l.getc(c)
yystart243:
	switch {
	default:
		goto yyabort
	case c == ')':
		goto yystate45
	case c == ';':
		goto yystate10
	case c >= '0' && c <= '9':
		goto yystate47
	case c == '\n' || c == '\r':
		goto yystate11
	case c == '\t' || c == ' ':
		goto yystate62
	case c == '\\':
		goto yystate25
	case c == '(':
		goto yystate44
	case c == '"':
		goto yystate5
	}

	goto yystate244 // silence unused label error
yystate244:
	c = l.getc(c)
yystart244:
	switch {
	default:
		goto yyabort
	case c == '"':
		goto yystate5
	case c == 'N':
		goto yystate159
	case c == 'P':
		goto yystate88
	case c == 'I':
		goto yystate126
	case c == 'H':
		goto yystate79
	case c == 'S':
		goto yystate222
	case c == 'T':
		goto yystate92
	case c == 'L':
		goto yystate85
	case c == 'K':
		goto yystate218
	case c == 'D':
		goto yystate65
	case c == ')':
		goto yystate45
	case c == 'W':
		goto yystate235
	case c == ';':
		goto yystate10
	case c == 'C':
		goto yystate202
	case c == 'M':
		goto yystate137
	case c == '\n' || c == '\r':
		goto yystate11
	case c == 'E':
		goto yystate123
	case c == 'X':
		goto yystate106
	case c == '\t' || c == ' ':
		goto yystate62
	case c == '\\':
		goto yystate25
	case c == 'R':
		goto yystate192
	case c == '(':
		goto yystate44
	case c == 'A':
		goto yystate109
	case c == 'U':
		goto yystate148
	case c == 'G':
		goto yystate212
	}

	goto yystate245 // silence unused label error
yystate245:
	c = l.getc(c)
yystart245:
	switch {
	default:
		goto yyabort
	case c == '\n' || c == '\r':
		goto yystate11
	case c == '\t' || c == ' ':
		goto yystate62
	case c == '\\':
		goto yystate25
	case c == '(':
		goto yystate44
	case c == '"':
		goto yystate5
	case c == '0':
		goto yystate239
	case c == ')':
		goto yystate45
	case c == ';':
		goto yystate10
	}

	goto yystate246 // silence unused label error
yystate246:
	c = l.getc(c)
yystart246:
	switch {
	default:
		goto yyabort
	case c == 'W':
		goto yystate235
	case c == ';':
		goto yystate10
	case c >= '0' && c <= '9':
		goto yystate247
	case c == 'M':
		goto yystate137
	case c == '\n' || c == '\r':
		goto yystate11
	case c == 'E':
		goto yystate123
	case c == 'X':
		goto yystate106
	case c == '\t' || c == ' ':
		goto yystate62
	case c == '\\':
		goto yystate25
	case c == 'R':
		goto yystate192
	case c == '(':
		goto yystate44
	case c == 'H':
		goto yystate250
	case c == 'A':
		goto yystate109
	case c == 'U':
		goto yystate148
	case c == 'G':
		goto yystate212
	case c == 'C':
		goto yystate248
	case c == '"':
		goto yystate5
	case c == 'N':
		goto yystate159
	case c == 'I':
		goto yystate252
	case c == 'P':
		goto yystate88
	case c == 'S':
		goto yystate222
	case c == 'T':
		goto yystate92
	case c == 'L':
		goto yystate85
	case c == 'K':
		goto yystate218
	case c == 'D':
		goto yystate65
	case c == ')':
		goto yystate45
	}

yystate247:
	c = l.getc(c)
	switch {
	default:
		goto yyrule18
	case c >= '0' && c <= '9':
		goto yystate247
	}

yystate248:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'E':
		goto yystate203
	case c == 'D':
		goto yystate210
	case c == 'H':
		goto yystate249
	case c == 'N':
		goto yystate206
	}

yystate249:
	c = l.getc(c)
	goto yyrule20

yystate250:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'S':
		goto yystate251
	case c == 'I':
		goto yystate80
	}

yystate251:
	c = l.getc(c)
	goto yyrule21

yystate252:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'S':
		goto yystate127
	case c == 'N':
		goto yystate253
	case c == 'P':
		goto yystate130
	}

yystate253:
	c = l.getc(c)
	goto yyrule19

	goto yystate254 // silence unused label error
yystate254:
	c = l.getc(c)
yystart254:
	switch {
	default:
		goto yyabort
	case c == ')':
		goto yystate45
	case c == ';':
		goto yystate10
	case c == ':':
		goto yystate266
	case c == '\n' || c == '\r':
		goto yystate11
	case c == '\t' || c == ' ':
		goto yystate62
	case c == '\\':
		goto yystate25
	case c == '(':
		goto yystate44
	case c == '"':
		goto yystate5
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate255
	}

yystate255:
	c = l.getc(c)
	switch {
	default:
		goto yyrule84
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate256
	case c == ':':
		goto yystate258
	}

yystate256:
	c = l.getc(c)
	switch {
	default:
		goto yyrule84
	case c == ':':
		goto yystate258
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate257
	}

yystate257:
	c = l.getc(c)
	switch {
	default:
		goto yyrule84
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate265
	case c == ':':
		goto yystate258
	}

yystate258:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate255
	case c == ':':
		goto yystate259
	}

yystate259:
	c = l.getc(c)
	switch {
	default:
		goto yyrule84
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate260
	}

yystate260:
	c = l.getc(c)
	switch {
	default:
		goto yyrule84
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate261
	case c == ':':
		goto yystate264
	}

yystate261:
	c = l.getc(c)
	switch {
	default:
		goto yyrule84
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate262
	case c == ':':
		goto yystate264
	}

yystate262:
	c = l.getc(c)
	switch {
	default:
		goto yyrule84
	case c == ':':
		goto yystate264
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate263
	}

yystate263:
	c = l.getc(c)
	switch {
	default:
		goto yyrule84
	case c == ':':
		goto yystate264
	}

yystate264:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate260
	}

yystate265:
	c = l.getc(c)
	switch {
	default:
		goto yyrule84
	case c == ':':
		goto yystate258
	}

yystate266:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == ':':
		goto yystate259
	}

	goto yystate267 // silence unused label error
yystate267:
	c = l.getc(c)
yystart267:
	switch {
	default:
		goto yyabort
	case c == ')':
		goto yystate45
	case c == ';':
		goto yystate10
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate268
	case c == '\n' || c == '\r':
		goto yystate11
	case c == '\t' || c == ' ':
		goto yystate62
	case c == '-':
		goto yystate269
	case c == '\\':
		goto yystate25
	case c == '(':
		goto yystate44
	case c == '"':
		goto yystate5
	}

yystate268:
	c = l.getc(c)
	switch {
	default:
		goto yyrule88
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate268
	}

yystate269:
	c = l.getc(c)
	goto yyrule89

	goto yystate270 // silence unused label error
yystate270:
	c = l.getc(c)
yystart270:
	switch {
	default:
		goto yyabort
	case c == ')':
		goto yystate45
	case c == ';':
		goto yystate10
	case c == '+' || c == '-':
		goto yystate276
	case c == '\n' || c == '\r':
		goto yystate11
	case c == '\t' || c == ' ':
		goto yystate62
	case c == '\\':
		goto yystate25
	case c == '(':
		goto yystate44
	case c == '"':
		goto yystate5
	case c >= '0' && c <= '9':
		goto yystate271
	case c == '.':
		goto yystate277
	}

yystate271:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'E' || c == 'e':
		goto yystate272
	case c == '.':
		goto yystate275
	case c >= '0' && c <= '9':
		goto yystate271
	}

yystate272:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == '+' || c == '-':
		goto yystate274
	case c >= '0' && c <= '9':
		goto yystate273
	}

yystate273:
	c = l.getc(c)
	switch {
	default:
		goto yyrule94
	case c >= '0' && c <= '9':
		goto yystate273
	}

yystate274:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9':
		goto yystate273
	}

yystate275:
	c = l.getc(c)
	switch {
	default:
		goto yyrule94
	case c == 'E' || c == 'e':
		goto yystate272
	case c >= '0' && c <= '9':
		goto yystate275
	}

yystate276:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9':
		goto yystate271
	case c == '.':
		goto yystate277
	}

yystate277:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9':
		goto yystate275
	}

	goto yystate278 // silence unused label error
yystate278:
	c = l.getc(c)
yystart278:
	switch {
	default:
		goto yyabort
	case c == '(':
		goto yystate44
	case c == 'H':
		goto yystate250
	case c == 'A':
		goto yystate109
	case c == 'U':
		goto yystate148
	case c == 'G':
		goto yystate212
	case c == 'C':
		goto yystate248
	case c == '"':
		goto yystate5
	case c == 'N':
		goto yystate159
	case c == 'I':
		goto yystate252
	case c == 'P':
		goto yystate88
	case c == 'S':
		goto yystate222
	case c == 'T':
		goto yystate92
	case c == 'L':
		goto yystate85
	case c == 'K':
		goto yystate218
	case c == 'D':
		goto yystate65
	case c == ')':
		goto yystate45
	case c == 'W':
		goto yystate235
	case c == ';':
		goto yystate10
	case c >= '0' && c <= '9':
		goto yystate247
	case c == 'M':
		goto yystate137
	case c == '\n' || c == '\r':
		goto yystate11
	case c == 'E':
		goto yystate123
	case c == 'X':
		goto yystate106
	case c == '\t' || c == ' ':
		goto yystate62
	case c == '\\':
		goto yystate25
	case c == 'R':
		goto yystate192
	}

	goto yystate279 // silence unused label error
yystate279:
	c = l.getc(c)
yystart279:
	switch {
	default:
		goto yyabort
	case c == ')':
		goto yystate45
	case c == ';':
		goto yystate10
	case c == ':':
		goto yystate266
	case c == '\n' || c == '\r':
		goto yystate11
	case c == '\t' || c == ' ':
		goto yystate62
	case c == '\\':
		goto yystate25
	case c == '(':
		goto yystate44
	case c == '"':
		goto yystate5
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate255
	}

	goto yystate280 // silence unused label error
yystate280:
	c = l.getc(c)
yystart280:
	switch {
	default:
		goto yyabort
	case c == '\t' || c == ' ':
		goto yystate62
	case c == '-':
		goto yystate269
	case c == '\\':
		goto yystate25
	case c == '(':
		goto yystate44
	case c == '"':
		goto yystate5
	case c == ')':
		goto yystate45
	case c == ';':
		goto yystate10
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate268
	case c == '\n' || c == '\r':
		goto yystate11
	}

	goto yystate281 // silence unused label error
yystate281:
	c = l.getc(c)
yystart281:
	switch {
	default:
		goto yyabort
	case c == ')':
		goto yystate45
	case c == ';':
		goto yystate10
	case c == '+' || c == '-':
		goto yystate276
	case c == '\n' || c == '\r':
		goto yystate11
	case c == '\t' || c == ' ':
		goto yystate62
	case c == '\\':
		goto yystate25
	case c == '(':
		goto yystate44
	case c == '"':
		goto yystate5
	case c >= '0' && c <= '9':
		goto yystate271
	case c == '.':
		goto yystate277
	}

	goto yystate282 // silence unused label error
yystate282:
	c = l.getc(c)
yystart282:
	switch {
	default:
		goto yyabort
	case c == ')':
		goto yystate45
	case c == ';':
		goto yystate10
	case c == '.':
		goto yystate286
	case c == '\n' || c == '\r':
		goto yystate11
	case c == '\t' || c == ' ':
		goto yystate62
	case c == '\\':
		goto yystate25
	case c == '(':
		goto yystate44
	case c == '"':
		goto yystate5
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate283
	}

yystate283:
	c = l.getc(c)
	switch {
	default:
		goto yyrule16
	case c == '.':
		goto yystate285
	case c == '-':
		goto yystate284
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate283
	}

yystate284:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == '-':
		goto yystate284
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate283
	}

yystate285:
	c = l.getc(c)
	switch {
	default:
		goto yyrule16
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate283
	}

yystate286:
	c = l.getc(c)
	goto yyrule16

	goto yystate287 // silence unused label error
yystate287:
	c = l.getc(c)
yystart287:
	switch {
	default:
		goto yyabort
	case c == '\n' || c == '\r':
		goto yystate11
	case c == '\t' || c == ' ':
		goto yystate62
	case c == '\\':
		goto yystate25
	case c >= '0' && c <= '9' || c == '=' || c >= 'A' && c <= 'V':
		goto yystate288
	case c == '(':
		goto yystate44
	case c == '"':
		goto yystate5
	case c == ')':
		goto yystate45
	case c == ';':
		goto yystate10
	}

yystate288:
	c = l.getc(c)
	switch {
	default:
		goto yyrule85
	case c >= '0' && c <= '9' || c == '=' || c >= 'A' && c <= 'V':
		goto yystate288
	}

	goto yystate289 // silence unused label error
yystate289:
	c = l.getc(c)
yystart289:
	switch {
	default:
		goto yyabort
	case c == 'U':
		goto yystate293
	case c == ')':
		goto yystate45
	case c == ';':
		goto yystate10
	case c == '\n' || c == '\r':
		goto yystate11
	case c == '\t' || c == ' ':
		goto yystate62
	case c == '\\':
		goto yystate25
	case c == '(':
		goto yystate44
	case c == '"':
		goto yystate5
	case c == 'T':
		goto yystate290
	}

yystate290:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'C':
		goto yystate291
	}

yystate291:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'P':
		goto yystate292
	}

yystate292:
	c = l.getc(c)
	goto yyrule91

yystate293:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'D':
		goto yystate294
	}

yystate294:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'P':
		goto yystate295
	}

yystate295:
	c = l.getc(c)
	goto yyrule90

	goto yystate296 // silence unused label error
yystate296:
	c = l.getc(c)
yystart296:
	switch {
	default:
		goto yyabort
	case c == '\t' || c == ' ':
		goto yystate62
	case c == '\\':
		goto yystate25
	case c == '.':
		goto yystate297
	case c == '(':
		goto yystate44
	case c == '"':
		goto yystate5
	case c == ')':
		goto yystate45
	case c == ';':
		goto yystate10
	case c == '_':
		goto yystate302
	case c == '\n' || c == '\r':
		goto yystate11
	}

yystate297:
	c = l.getc(c)
	switch {
	default:
		goto yyrule12
	case c == '.':
		goto yystate301
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate298
	}

yystate298:
	c = l.getc(c)
	switch {
	default:
		goto yyrule12
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate298
	case c == '.':
		goto yystate299
	case c == '-':
		goto yystate300
	}

yystate299:
	c = l.getc(c)
	switch {
	default:
		goto yyrule12
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate298
	}

yystate300:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate298
	case c == '-':
		goto yystate300
	}

yystate301:
	c = l.getc(c)
	goto yyrule12

yystate302:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate303
	}

yystate303:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == '-':
		goto yystate304
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate303
	case c == '.':
		goto yystate305
	}

yystate304:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == '-':
		goto yystate304
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate303
	}

yystate305:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == '_':
		goto yystate306
	}

yystate306:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate307
	}

yystate307:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == '-':
		goto yystate308
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate307
	case c == '.':
		goto yystate297
	}

yystate308:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == '-':
		goto yystate308
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate307
	}

	goto yystate309 // silence unused label error
yystate309:
	c = l.getc(c)
yystart309:
	switch {
	default:
		goto yyabort
	case c == ')':
		goto yystate45
	case c == ';':
		goto yystate10
	case c == '.':
		goto yystate286
	case c == '\n' || c == '\r':
		goto yystate11
	case c == '\t' || c == ' ':
		goto yystate62
	case c == '\\':
		goto yystate25
	case c == '(':
		goto yystate44
	case c == '"':
		goto yystate5
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate283
	}

	goto yystate310 // silence unused label error
yystate310:
	c = l.getc(c)
yystart310:
	switch {
	default:
		goto yyabort
	case c == '"':
		goto yystate5
	case c == ')':
		goto yystate45
	case c == ';':
		goto yystate10
	case c == '\n' || c == '\r':
		goto yystate11
	case c == '\t' || c == ' ':
		goto yystate62
	case c == '\\':
		goto yystate25
	case c >= '0' && c <= '9' || c == '=' || c >= 'A' && c <= 'V':
		goto yystate288
	case c == '(':
		goto yystate44
	}

	goto yystate311 // silence unused label error
yystate311:
	c = l.getc(c)
yystart311:
	switch {
	default:
		goto yyabort
	case c == ')':
		goto yystate45
	case c == ';':
		goto yystate10
	case c == '\n' || c == '\r':
		goto yystate11
	case c == '\t' || c == ' ':
		goto yystate62
	case c == '\\':
		goto yystate25
	case c == '(':
		goto yystate44
	case c == '"':
		goto yystate5
	case c == 'T':
		goto yystate290
	case c == 'U':
		goto yystate293
	}

	goto yystate312 // silence unused label error
yystate312:
	c = l.getc(c)
yystart312:
	switch {
	default:
		goto yyabort
	case c == ';':
		goto yystate10
	case c == '_':
		goto yystate302
	case c == '\n' || c == '\r':
		goto yystate11
	case c == '\t' || c == ' ':
		goto yystate62
	case c == '\\':
		goto yystate25
	case c == '.':
		goto yystate297
	case c == '(':
		goto yystate44
	case c == '"':
		goto yystate5
	case c == ')':
		goto yystate45
	}

	goto yystate313 // silence unused label error
yystate313:
	c = l.getc(c)
yystart313:
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9':
		goto yystate247
	case c == '\n' || c == '\r':
		goto yystate11
	case c == '\t' || c == ' ':
		goto yystate62
	case c == '\\':
		goto yystate25
	case c == '(':
		goto yystate44
	case c == '"':
		goto yystate5
	case c == ')':
		goto yystate45
	case c == ';':
		goto yystate10
	}

	goto yystate314 // silence unused label error
yystate314:
	c = l.getc(c)
yystart314:
	switch {
	default:
		goto yyabort
	case c == '(':
		goto yystate44
	case c == '"':
		goto yystate5
	case c == '+' || c >= '/' && c <= '9' || c == '=' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate315
	case c == ')':
		goto yystate45
	case c == ';':
		goto yystate10
	case c == '\n' || c == '\r':
		goto yystate11
	case c == '\t' || c == ' ':
		goto yystate62
	case c == '\\':
		goto yystate25
	}

yystate315:
	c = l.getc(c)
	switch {
	default:
		goto yyrule86
	case c == '+' || c >= '/' && c <= '9' || c == '=' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate315
	}

	goto yystate316 // silence unused label error
yystate316:
	c = l.getc(c)
yystart316:
	switch {
	default:
		goto yyabort
	case c == ')':
		goto yystate45
	case c == ';':
		goto yystate10
	case c == '\n' || c == '\r':
		goto yystate11
	case c == '\t' || c == ' ':
		goto yystate62
	case c == '\\':
		goto yystate25
	case c == '(':
		goto yystate44
	case c == 'S':
		goto yystate320
	case c == '"':
		goto yystate5
	case c == 'D':
		goto yystate317
	}

yystate317:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'N':
		goto yystate318
	}

yystate318:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'S':
		goto yystate319
	}

yystate319:
	c = l.getc(c)
	goto yyrule93

yystate320:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'M':
		goto yystate321
	}

yystate321:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'T':
		goto yystate322
	}

yystate322:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'P':
		goto yystate323
	}

yystate323:
	c = l.getc(c)
	goto yyrule92

	goto yystate324 // silence unused label error
yystate324:
	c = l.getc(c)
yystart324:
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9':
		goto yystate247
	case c == '\n' || c == '\r':
		goto yystate11
	case c == '\t' || c == ' ':
		goto yystate62
	case c == '\\':
		goto yystate25
	case c == '(':
		goto yystate44
	case c == '"':
		goto yystate5
	case c == ')':
		goto yystate45
	case c == ';':
		goto yystate10
	}

	goto yystate325 // silence unused label error
yystate325:
	c = l.getc(c)
yystart325:
	switch {
	default:
		goto yyabort
	case c == '"':
		goto yystate5
	case c == '+' || c >= '/' && c <= '9' || c == '=' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate315
	case c == ')':
		goto yystate45
	case c == ';':
		goto yystate10
	case c == '\n' || c == '\r':
		goto yystate11
	case c == '\t' || c == ' ':
		goto yystate62
	case c == '\\':
		goto yystate25
	case c == '(':
		goto yystate44
	}

	goto yystate326 // silence unused label error
yystate326:
	c = l.getc(c)
yystart326:
	switch {
	default:
		goto yyabort
	case c == '\n' || c == '\r':
		goto yystate11
	case c == '\t' || c == ' ':
		goto yystate62
	case c == '\\':
		goto yystate25
	case c == '(':
		goto yystate44
	case c == 'S':
		goto yystate320
	case c == '"':
		goto yystate5
	case c == 'D':
		goto yystate317
	case c == ')':
		goto yystate45
	case c == ';':
		goto yystate10
	}

yyrule1: // ^[ \t]+$
yyrule2: // [ \t]+$
yyrule3: // [ \t]*;.*
	{
		// ignored
		goto yystate0
	}
yyrule4: // ^$INCLUDE

	goto yystate0
yyrule5: // ^$ORIGIN

	goto yystate0
yyrule6: // ^$TTL
	{

		ret = tDLR_TTL
		goto yystate0
	}
yyrule7: // \n|\r
	{

		if !l.inParen {
			ret = '\n'
		}
		goto yystate0
	}
yyrule8: // \(
	{

		if l.inParen {
			l.Error("nested parenthesis")
		}
		l.inParen = true
		goto yystate0
	}
yyrule9: // \)
	{

		if !l.inParen {
			l.Error(`unexpected ")"`)
		}
		l.inParen = false
		ret = '\n'
		goto yystate0
	}
yyrule10: // ^{domain-name}
	{

		ret = tDOMAIN_NAME
		goto yystate0
	}
yyrule11: // ^{srv-domain}
	{

		ret = tSRV_DOMAIN
		goto yystate0
	}
yyrule12: // {any-domain}
	{

		ret = tDOMAIN_NAME
		goto yystate0
	}
yyrule13: // ^[ \t]+
	{

		ret = tBLANK_START
		goto yystate0
	}
yyrule14: // \\#
	{

		ret = tBACKSLASH_HASH
		goto yystate0
	}
yyrule15: // \"(\\.|[^\\"\n\r])*\"
	{

		lval.str = string(bytes.Replace(l.buf[1:len(l.buf)-1], []byte(`\"`), []byte(`"`), -1))
		return tQSTR
	}
yyrule16: // {domain-name}
	{

		ret = tDOMAIN_NAME
		goto yystate0
	}
yyrule17: // [ \t]+
	{

		/* RR TTL */
		goto yystate0
	}
yyrule18: // [0-9]+
	{

		lval.str = string(l.buf)
		lval.u64, err = strconv.ParseUint(lval.str, 10, 64)
		if err != nil {
			panic(fmt.Errorf("invalid number %q", l.buf))
		}
		ret = tDECADIC
		/* RR class */
		goto yystate0
	}
yyrule19: // IN
	{

		lval.class = rr.CLASS_IN
		ret = tCLASS
		goto yystate0
	}
yyrule20: // CH
	{

		lval.class = rr.CLASS_CH
		ret = tCLASS
		goto yystate0
	}
yyrule21: // HS
	{

		lval.class = rr.CLASS_HS
		ret = tCLASS
		/* RR types */
		goto yystate0
	}
yyrule22: // A
	{
		ret = tA
		goto yystate0
	}
yyrule23: // A6
	{
		ret = tA6
		goto yystate0
	}
yyrule24: // AAAA
	{
		ret = tAAAA
		goto yystate0
	}
yyrule25: // AFSDB
	{
		ret = tAFSDB
		goto yystate0
	}
yyrule26: // APL
	{
		ret = tAPL
		goto yystate0
	}
yyrule27: // ATMA
	{
		ret = tATMA
		goto yystate0
	}
yyrule28: // CDS
	{
		ret = tCDS
		goto yystate0
	}
yyrule29: // CERT
	{
		ret = tCERT
		goto yystate0
	}
yyrule30: // CNAME
	{
		ret = tCNAME
		goto yystate0
	}
yyrule31: // DHCID
	{
		ret = tDHCID
		goto yystate0
	}
yyrule32: // DNAME
	{
		ret = tDNAME
		goto yystate0
	}
yyrule33: // DNSKEY
	{
		ret = tDNSKEY
		goto yystate0
	}
yyrule34: // DS
	{
		ret = tDS
		goto yystate0
	}
yyrule35: // EID
	{
		ret = tEID
		goto yystate0
	}
yyrule36: // GID
	{
		ret = tGID
		goto yystate0
	}
yyrule37: // GPOS
	{
		ret = tGPOS
		goto yystate0
	}
yyrule38: // HINFO
	{
		ret = tHINFO
		goto yystate0
	}
yyrule39: // HIP
	{
		ret = tHIP
		goto yystate0
	}
yyrule40: // IPSECKEY
	{
		ret = tIPSECKEY
		goto yystate0
	}
yyrule41: // ISDN
	{
		ret = tISDN
		goto yystate0
	}
yyrule42: // KEY
	{
		ret = tKEY
		goto yystate0
	}
yyrule43: // KX
	{
		ret = tKX
		goto yystate0
	}
yyrule44: // LOC
	{
		ret = tLOC
		goto yystate0
	}
yyrule45: // MB
	{
		ret = tMB
		goto yystate0
	}
yyrule46: // MD
	{
		ret = tMD
		goto yystate0
	}
yyrule47: // MF
	{
		ret = tMF
		goto yystate0
	}
yyrule48: // MG
	{
		ret = tMG
		goto yystate0
	}
yyrule49: // MINFO
	{
		ret = tMINFO
		goto yystate0
	}
yyrule50: // MR
	{
		ret = tMR
		goto yystate0
	}
yyrule51: // MX
	{
		ret = tMX
		goto yystate0
	}
yyrule52: // NAPTR
	{
		ret = tNAPTR
		goto yystate0
	}
yyrule53: // NIMLOC
	{
		ret = tNIMLOC
		goto yystate0
	}
yyrule54: // NINFO
	{
		ret = tNINFO
		goto yystate0
	}
yyrule55: // NS
	{
		ret = tNS
		goto yystate0
	}
yyrule56: // NSAP
	{
		ret = tNSAP
		goto yystate0
	}
yyrule57: // NSAP-PTR
	{
		ret = tNSAP_PTR
		goto yystate0
	}
yyrule58: // NSEC
	{
		ret = tNSEC
		goto yystate0
	}
yyrule59: // NSEC3
	{
		ret = tNSEC3
		goto yystate0
	}
yyrule60: // NSEC3PARAM
	{
		ret = tNSEC3PARAM
		goto yystate0
	}
yyrule61: // NULL
	{
		ret = tNULL
		goto yystate0
	}
yyrule62: // NXT
	{
		ret = tNXT
		goto yystate0
	}
yyrule63: // PTR
	{
		ret = tPTR
		goto yystate0
	}
yyrule64: // PX
	{
		ret = tPX
		goto yystate0
	}
yyrule65: // RKEY
	{
		ret = tRKEY
		goto yystate0
	}
yyrule66: // RP
	{
		ret = tRP
		goto yystate0
	}
yyrule67: // RRSIG
	{
		ret = tRRSIG
		goto yystate0
	}
yyrule68: // RT
	{
		ret = tRT
		goto yystate0
	}
yyrule69: // SIG
	{
		ret = tSIG
		goto yystate0
	}
yyrule70: // SOA
	{
		ret = tSOA
		goto yystate0
	}
yyrule71: // SPF
	{
		ret = tSPF
		goto yystate0
	}
yyrule72: // SRV
	{
		ret = tSRV
		goto yystate0
	}
yyrule73: // SSHFP
	{
		ret = tSSHFP
		goto yystate0
	}
yyrule74: // TALINK
	{
		ret = tTALINK
		goto yystate0
	}
yyrule75: // TKEY
	{
		ret = tTKEY
		goto yystate0
	}
yyrule76: // TSIG
	{
		ret = tTSIG
		goto yystate0
	}
yyrule77: // TXT
	{
		ret = tTXT
		goto yystate0
	}
yyrule78: // UID
	{
		ret = tUID
		goto yystate0
	}
yyrule79: // UINFO
	{
		ret = tUINFO
		goto yystate0
	}
yyrule80: // UNSPEC
	{
		ret = tUNSPEC
		goto yystate0
	}
yyrule81: // WKS
	{
		ret = tWKS
		goto yystate0
	}
yyrule82: // X25
	{
		ret = tX25
		goto yystate0
	}
yyrule83: // {ipv4}
	{

		ip := net.ParseIP(string(l.buf))
		if ip == nil {
			l.Error(fmt.Sprintf("invalid IP %q", l.buf))
		}
		lval.ip = ip
		return tIPV4
	}
yyrule84: // {ipv6}
	{

		ip := net.ParseIP(string(l.buf))
		if ip == nil {
			l.Error(fmt.Sprintf("invalid IP %q", l.buf))
		}
		lval.ip = ip
		return tIPV6
	}
yyrule85: // [0-9A-V=]+
	{

		ret = tBASE32EXT
		goto yystate0
	}
yyrule86: // [A-Za-z0-9+/=]+
	{

		ret = tBASE64
		goto yystate0
	}
yyrule87: // 0x({hex}|\.)+
	{

		var err error
		s := string(l.buf[2:])
		s = strings.Replace(s, ".", "", -1)
		lval.data, err = hex.DecodeString(s)
		if err != nil {
			l.Error("expected 0x style hex string")
		}
		ret = t0xHEX
		goto yystate0
	}
yyrule88: // [0-9a-fA-F]+
	{

		var err error
		lval.data, err = hex.DecodeString(string(l.buf))
		if err != nil {
			l.Error("expected hex string")
		}
		ret = tHEX
		goto yystate0
	}
yyrule89: // -
	{

		lval.data = nil
		ret = tHEX
		goto yystate0
	}
yyrule90: // UDP
	{
		lval.int, ret = int(rr.UDP_Protocol), tUDP_PROTO
		goto yystate0
	}
yyrule91: // TCP
	{
		lval.int, ret = int(rr.TCP_Protocol), tTCP_PROTO
		goto yystate0
	}
yyrule92: // SMTP
	{
		lval.int, ret = int(rr.SMTP_Port), tSMTP_PORT
		goto yystate0
	}
yyrule93: // DNS
	{
		lval.int, ret = int(rr.DNS_Port), tDNS_PORT
		goto yystate0
	}
yyrule94: // [-+]?{float_lit}
	{

		if _, err = fmt.Sscanf(string(l.buf), "%f", &lval.float); err != nil {
			l.Error(err.Error())
		}
		ret = tFLOAT
		goto yystate0
	}
		panic("unreachable")

		goto yyabort // silence unused label error

yyabort: // no lexem recognized
	// no pattern recognized
	if len(l.buf) == 0 {
		ret = int(c)
		l.getc(0)
		return
	}

	return unicode.ReplacementChar
}
