// Copyright (c) 2011 CZ.NIC z.s.p.o. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// blame: jnml, labs.nic.cz

// WARNING: If this file is scanner.go then DO NOT EDIT.
// scanner.go is generated by golex from scanner.l (see the Makefile).


package zone

import (
	"bufio"
	"bytes"
	"github.com/cznic/dns/rr"
	"encoding/hex"
	"fmt"
	"net"
	"os"
	"strconv"
	"unicode"
)

type lexStackItem struct {
	rrHandler  func(*rr.RR) bool
	errHandler func(e string) bool
	startCond  int
	buf        []byte
	last       byte
	peek       byte
	line       int
	column     int
	name       string
	src        *bufio.Reader
	prev       *lexStackItem
	inParen    bool
}

type lex struct {
	lexStackItem
}

func (l *lex) include(name string, source *bufio.Reader) {
	push := &lexStackItem{}
	*push = l.lexStackItem
	l.buf = nil
	l.line = 1
	l.column = 0
	l.name = name
	l.src = source
	l.prev = push
	l.getc(0)
}

func (l *lex) getc(c byte) byte {
	if c != 0 {
		l.buf = append(l.buf, c)
	}
	l.last = l.peek
	if b, err := l.src.ReadByte(); err == nil {
		if b == '\n' {
			l.line++
			l.column = 0
		} else {
			l.column++
		}
		l.peek = b
		return b
	} else {
		if err == os.EOF {
			l.peek = 0
			return 0
		}
		panic(err)
	}

	panic("unreachable")
}

func newLex(name string, source *bufio.Reader, errHandler func(e string) bool, rrHandler func(*rr.RR) bool) (l *lex) {
	l = &lex{}
	l.errHandler = errHandler
	l.rrHandler = rrHandler
	l.line = 1
	l.name = name
	l.src = source
	l.getc(0)
	return
}

func (l *lex) Error(e string) {
	e = fmt.Sprintf("%s:%d:%d - %s", l.name, l.line, l.column, e)
	if l.errHandler != nil {
		if l.errHandler(e) {
			return
		}
	}
	panic(os.NewError(e))
}

func (l *lex) begin(sc int) {
	l.startCond = sc
}

const (
	sc_INITIAL = iota
	sc_RRHEAD
	sc_DOMAIN
	sc_NUM
	sc_IPV4
	sc_IPV6
	sc_BASE32EXT
	sc_BASE64
	sc_TYPE
	sc_HEX
	sc_QSTR
)

func (l *lex) Lex(lval *yySymType) (ret int) {
	var err os.Error

	/* debug helper
	defer func(sc0 int) {
		var s string
		if ret > 255 {
			if x := ret - 0xE002; x < len(yyToknames) {
				s = yyToknames[x]
			}
		}
		fmt.Printf("*lex.Lex() %s:%d:%d - %d %q %s buf %q, sc %d->%d\n", l.name, l.line, l.column, ret, string(ret), s, l.buf, sc0, l.startCond)
	}(l.startCond) //*/

	c := l.peek
	ret = -1

yystate0:

	if ret >= 0 {
		lval.str = string(l.buf)
		return
	}
	l.buf = l.buf[:0]

	switch yyt, yyb := l.startCond, l.last == '\n' || l.last == 0; yyt {
	default:
		panic(fmt.Errorf(`invalid start condition %d`, yyt))
	case 0: // start condition: INITIAL
		if yyb {
			goto yystart1
		}
		goto yystart164
	case 4: // start condition: ipv4
		if yyb {
			goto yystart32
		}
		goto yystart165
	case 8: // start condition: type
		if yyb {
			goto yystart50
		}
		goto yystart166
	case 1: // start condition: rrHead
		if yyb {
			goto yystart167
		}
		goto yystart191
	case 5: // start condition: ipv6
		if yyb {
			goto yystart175
		}
		goto yystart192
	case 9: // start condition: hex
		if yyb {
			goto yystart188
		}
		goto yystart193
	case 2: // start condition: domain
		if yyb {
			goto yystart194
		}
		goto yystart201
	case 6: // start condition: base32ext
		if yyb {
			goto yystart199
		}
		goto yystart202
	case 3: // start condition: num
		if yyb {
			goto yystart203
		}
		goto yystart206
	case 7: // start condition: base64
		if yyb {
			goto yystart204
		}
		goto yystart207
	}

	goto yystate1 // silence unused label error
yystate1:
	c = l.getc(c)
yystart1:
	switch {
	default:
		goto yyabort
	case c == '\t' || c == ' ':
		goto yystate9
	case c == '.':
		goto yystate13
	case c == '$':
		goto yystate14
	case c == '"':
		goto yystate6
	case c == ')':
		goto yystate5
	case c == '(':
		goto yystate31
	case c == '\n' || c == '\r':
		goto yystate12
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate2
	case c == ';':
		goto yystate11
	}

yystate2:
	c = l.getc(c)
	switch {
	default:
		goto yyrule10
	case c == '-':
		goto yystate3
	case c == '.':
		goto yystate4
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate2
	}

yystate3:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == '-':
		goto yystate3
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate2
	}

yystate4:
	c = l.getc(c)
	switch {
	default:
		goto yyrule10
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate2
	}

yystate5:
	c = l.getc(c)
	goto yyrule9

yystate6:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == '\\':
		goto yystate8
	case c >= '\x01' && c <= '\t' || c == '\v' || c == '\f' || c >= '\x0e' && c <= '!' || c >= '#' && c <= '[' || c >= ']' && c <= 'ÿ':
		goto yystate6
	case c == '"':
		goto yystate7
	}

yystate7:
	c = l.getc(c)
	goto yyrule12

yystate8:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c >= '\x01' && c <= '\t' || c >= '\v' && c <= 'ÿ':
		goto yystate6
	}

yystate9:
	c = l.getc(c)
	switch {
	default:
		goto yyrule11
	case c == '\t' || c == ' ':
		goto yystate9
	case c == '\x00' || c == '\n':
		goto yystate10
	case c == ';':
		goto yystate11
	}

yystate10:
	goto yyrule1

yystate11:
	c = l.getc(c)
	switch {
	default:
		goto yyrule3
	case c >= '\x01' && c <= '\t' || c >= '\v' && c <= 'ÿ':
		goto yystate11
	}

yystate12:
	c = l.getc(c)
	goto yyrule7

yystate13:
	c = l.getc(c)
	goto yyrule10

yystate14:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'I':
		goto yystate24
	case c == 'O':
		goto yystate15
	case c == 'T':
		goto yystate21
	}

yystate15:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'R':
		goto yystate16
	}

yystate16:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'I':
		goto yystate17
	}

yystate17:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'G':
		goto yystate18
	}

yystate18:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'I':
		goto yystate19
	}

yystate19:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'N':
		goto yystate20
	}

yystate20:
	c = l.getc(c)
	goto yyrule5

yystate21:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'T':
		goto yystate22
	}

yystate22:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'L':
		goto yystate23
	}

yystate23:
	c = l.getc(c)
	goto yyrule6

yystate24:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'N':
		goto yystate25
	}

yystate25:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'C':
		goto yystate26
	}

yystate26:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'L':
		goto yystate27
	}

yystate27:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'U':
		goto yystate28
	}

yystate28:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'D':
		goto yystate29
	}

yystate29:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'E':
		goto yystate30
	}

yystate30:
	c = l.getc(c)
	goto yyrule4

yystate31:
	c = l.getc(c)
	goto yyrule8

	goto yystate32 // silence unused label error
yystate32:
	c = l.getc(c)
yystart32:
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9':
		goto yystate33
	case c == '"':
		goto yystate6
	case c == ')':
		goto yystate5
	case c == '\t' || c == ' ':
		goto yystate48
	case c == '(':
		goto yystate31
	case c == '\n' || c == '\r':
		goto yystate12
	case c == ';':
		goto yystate11
	}

yystate33:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9':
		goto yystate34
	case c == '.':
		goto yystate36
	}

yystate34:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == '.':
		goto yystate36
	case c >= '0' && c <= '9':
		goto yystate35
	}

yystate35:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == '.':
		goto yystate36
	}

yystate36:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9':
		goto yystate37
	}

yystate37:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9':
		goto yystate38
	case c == '.':
		goto yystate40
	}

yystate38:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == '.':
		goto yystate40
	case c >= '0' && c <= '9':
		goto yystate39
	}

yystate39:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == '.':
		goto yystate40
	}

yystate40:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9':
		goto yystate41
	}

yystate41:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9':
		goto yystate42
	case c == '.':
		goto yystate44
	}

yystate42:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9':
		goto yystate43
	case c == '.':
		goto yystate44
	}

yystate43:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == '.':
		goto yystate44
	}

yystate44:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9':
		goto yystate45
	}

yystate45:
	c = l.getc(c)
	switch {
	default:
		goto yyrule58
	case c >= '0' && c <= '9':
		goto yystate46
	}

yystate46:
	c = l.getc(c)
	switch {
	default:
		goto yyrule58
	case c >= '0' && c <= '9':
		goto yystate47
	}

yystate47:
	c = l.getc(c)
	goto yyrule58

yystate48:
	c = l.getc(c)
	switch {
	default:
		goto yyrule14
	case c == '\t' || c == ' ':
		goto yystate48
	case c == '\x00' || c == '\n':
		goto yystate49
	case c == ';':
		goto yystate11
	}

yystate49:
	goto yyrule2

	goto yystate50 // silence unused label error
yystate50:
	c = l.getc(c)
yystart50:
	switch {
	default:
		goto yyabort
	case c == 'D':
		goto yystate108
	case c == 'A':
		goto yystate140
	case c == 'W':
		goto yystate105
	case c == 'I':
		goto yystate151
	case c == 'K':
		goto yystate88
	case c == 'R':
		goto yystate69
	case c == 'M':
		goto yystate162
	case c == '"':
		goto yystate6
	case c == 'L':
		goto yystate127
	case c == 'T':
		goto yystate134
	case c == ')':
		goto yystate5
	case c == '\t' || c == ' ':
		goto yystate48
	case c == 'G':
		goto yystate84
	case c == '(':
		goto yystate31
	case c == 'H':
		goto yystate122
	case c == 'C':
		goto yystate76
	case c == 'X':
		goto yystate137
	case c == 'S':
		goto yystate92
	case c == 'P':
		goto yystate130
	case c == 'N':
		goto yystate51
	case c == '\n' || c == '\r':
		goto yystate12
	case c == ';':
		goto yystate11
	}

yystate51:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'X':
		goto yystate63
	case c == 'A':
		goto yystate65
	case c == 'S':
		goto yystate52
	}

yystate52:
	c = l.getc(c)
	switch {
	default:
		goto yyrule40
	case c == 'E':
		goto yystate55
	case c == 'A':
		goto yystate53
	}

yystate53:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'P':
		goto yystate54
	}

yystate54:
	c = l.getc(c)
	goto yyrule39

yystate55:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'C':
		goto yystate56
	}

yystate56:
	c = l.getc(c)
	switch {
	default:
		goto yyrule41
	case c == '3':
		goto yystate57
	}

yystate57:
	c = l.getc(c)
	switch {
	default:
		goto yyrule42
	case c == 'P':
		goto yystate58
	}

yystate58:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'A':
		goto yystate59
	}

yystate59:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'R':
		goto yystate60
	}

yystate60:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'A':
		goto yystate61
	}

yystate61:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'M':
		goto yystate62
	}

yystate62:
	c = l.getc(c)
	goto yyrule43

yystate63:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'T':
		goto yystate64
	}

yystate64:
	c = l.getc(c)
	goto yyrule44

yystate65:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'P':
		goto yystate66
	}

yystate66:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'T':
		goto yystate67
	}

yystate67:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'R':
		goto yystate68
	}

yystate68:
	c = l.getc(c)
	goto yyrule38

yystate69:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'R':
		goto yystate70
	case c == 'T':
		goto yystate75
	case c == 'P':
		goto yystate74
	}

yystate70:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'S':
		goto yystate71
	}

yystate71:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'I':
		goto yystate72
	}

yystate72:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'G':
		goto yystate73
	}

yystate73:
	c = l.getc(c)
	goto yyrule48

yystate74:
	c = l.getc(c)
	goto yyrule47

yystate75:
	c = l.getc(c)
	goto yyrule49

yystate76:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'N':
		goto yystate77
	case c == 'E':
		goto yystate81
	}

yystate77:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'A':
		goto yystate78
	}

yystate78:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'M':
		goto yystate79
	}

yystate79:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'E':
		goto yystate80
	}

yystate80:
	c = l.getc(c)
	goto yyrule25

yystate81:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'R':
		goto yystate82
	}

yystate82:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'T':
		goto yystate83
	}

yystate83:
	c = l.getc(c)
	goto yyrule24

yystate84:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'P':
		goto yystate85
	}

yystate85:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'O':
		goto yystate86
	}

yystate86:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'S':
		goto yystate87
	}

yystate87:
	c = l.getc(c)
	goto yyrule30

yystate88:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'X':
		goto yystate89
	case c == 'E':
		goto yystate90
	}

yystate89:
	c = l.getc(c)
	goto yyrule35

yystate90:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'Y':
		goto yystate91
	}

yystate91:
	c = l.getc(c)
	goto yyrule34

yystate92:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'O':
		goto yystate95
	case c == 'I':
		goto yystate103
	case c == 'R':
		goto yystate93
	case c == 'S':
		goto yystate97
	case c == 'P':
		goto yystate101
	}

yystate93:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'V':
		goto yystate94
	}

yystate94:
	c = l.getc(c)
	goto yyrule53

yystate95:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'A':
		goto yystate96
	}

yystate96:
	c = l.getc(c)
	goto yyrule51

yystate97:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'H':
		goto yystate98
	}

yystate98:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'F':
		goto yystate99
	}

yystate99:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'P':
		goto yystate100
	}

yystate100:
	c = l.getc(c)
	goto yyrule54

yystate101:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'F':
		goto yystate102
	}

yystate102:
	c = l.getc(c)
	goto yyrule52

yystate103:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'G':
		goto yystate104
	}

yystate104:
	c = l.getc(c)
	goto yyrule50

yystate105:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'K':
		goto yystate106
	}

yystate106:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'S':
		goto yystate107
	}

yystate107:
	c = l.getc(c)
	goto yyrule56

yystate108:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'H':
		goto yystate118
	case c == 'S':
		goto yystate117
	case c == 'N':
		goto yystate109
	}

yystate109:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'S':
		goto yystate110
	case c == 'A':
		goto yystate114
	}

yystate110:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'K':
		goto yystate111
	}

yystate111:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'E':
		goto yystate112
	}

yystate112:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'Y':
		goto yystate113
	}

yystate113:
	c = l.getc(c)
	goto yyrule28

yystate114:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'M':
		goto yystate115
	}

yystate115:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'E':
		goto yystate116
	}

yystate116:
	c = l.getc(c)
	goto yyrule27

yystate117:
	c = l.getc(c)
	goto yyrule29

yystate118:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'C':
		goto yystate119
	}

yystate119:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'I':
		goto yystate120
	}

yystate120:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'D':
		goto yystate121
	}

yystate121:
	c = l.getc(c)
	goto yyrule26

yystate122:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'I':
		goto yystate123
	}

yystate123:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'N':
		goto yystate124
	}

yystate124:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'F':
		goto yystate125
	}

yystate125:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'O':
		goto yystate126
	}

yystate126:
	c = l.getc(c)
	goto yyrule31

yystate127:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'O':
		goto yystate128
	}

yystate128:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'C':
		goto yystate129
	}

yystate129:
	c = l.getc(c)
	goto yyrule36

yystate130:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'X':
		goto yystate133
	case c == 'T':
		goto yystate131
	}

yystate131:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'R':
		goto yystate132
	}

yystate132:
	c = l.getc(c)
	goto yyrule45

yystate133:
	c = l.getc(c)
	goto yyrule46

yystate134:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'X':
		goto yystate135
	}

yystate135:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'T':
		goto yystate136
	}

yystate136:
	c = l.getc(c)
	goto yyrule55

yystate137:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == '2':
		goto yystate138
	}

yystate138:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == '5':
		goto yystate139
	}

yystate139:
	c = l.getc(c)
	goto yyrule57

yystate140:
	c = l.getc(c)
	switch {
	default:
		goto yyrule19
	case c == '6':
		goto yystate145
	case c == 'F':
		goto yystate141
	case c == 'A':
		goto yystate148
	case c == 'P':
		goto yystate146
	}

yystate141:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'S':
		goto yystate142
	}

yystate142:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'D':
		goto yystate143
	}

yystate143:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'B':
		goto yystate144
	}

yystate144:
	c = l.getc(c)
	goto yyrule22

yystate145:
	c = l.getc(c)
	goto yyrule21

yystate146:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'L':
		goto yystate147
	}

yystate147:
	c = l.getc(c)
	goto yyrule23

yystate148:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'A':
		goto yystate149
	}

yystate149:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'A':
		goto yystate150
	}

yystate150:
	c = l.getc(c)
	goto yyrule20

yystate151:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'P':
		goto yystate155
	case c == 'S':
		goto yystate152
	}

yystate152:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'D':
		goto yystate153
	}

yystate153:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'N':
		goto yystate154
	}

yystate154:
	c = l.getc(c)
	goto yyrule33

yystate155:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'S':
		goto yystate156
	}

yystate156:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'E':
		goto yystate157
	}

yystate157:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'C':
		goto yystate158
	}

yystate158:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'K':
		goto yystate159
	}

yystate159:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'E':
		goto yystate160
	}

yystate160:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'Y':
		goto yystate161
	}

yystate161:
	c = l.getc(c)
	goto yyrule32

yystate162:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'X':
		goto yystate163
	}

yystate163:
	c = l.getc(c)
	goto yyrule37

	goto yystate164 // silence unused label error
yystate164:
	c = l.getc(c)
yystart164:
	switch {
	default:
		goto yyabort
	case c == '"':
		goto yystate6
	case c == ')':
		goto yystate5
	case c == '\t' || c == ' ':
		goto yystate48
	case c == '(':
		goto yystate31
	case c == '\n' || c == '\r':
		goto yystate12
	case c == ';':
		goto yystate11
	}

	goto yystate165 // silence unused label error
yystate165:
	c = l.getc(c)
yystart165:
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9':
		goto yystate33
	case c == '"':
		goto yystate6
	case c == ')':
		goto yystate5
	case c == '\t' || c == ' ':
		goto yystate48
	case c == '(':
		goto yystate31
	case c == '\n' || c == '\r':
		goto yystate12
	case c == ';':
		goto yystate11
	}

	goto yystate166 // silence unused label error
yystate166:
	c = l.getc(c)
yystart166:
	switch {
	default:
		goto yyabort
	case c == 'D':
		goto yystate108
	case c == 'A':
		goto yystate140
	case c == 'W':
		goto yystate105
	case c == 'I':
		goto yystate151
	case c == 'K':
		goto yystate88
	case c == 'R':
		goto yystate69
	case c == 'M':
		goto yystate162
	case c == '"':
		goto yystate6
	case c == 'L':
		goto yystate127
	case c == 'T':
		goto yystate134
	case c == ')':
		goto yystate5
	case c == '\t' || c == ' ':
		goto yystate48
	case c == 'G':
		goto yystate84
	case c == '(':
		goto yystate31
	case c == 'H':
		goto yystate122
	case c == 'C':
		goto yystate76
	case c == 'X':
		goto yystate137
	case c == 'S':
		goto yystate92
	case c == 'P':
		goto yystate130
	case c == 'N':
		goto yystate51
	case c == '\n' || c == '\r':
		goto yystate12
	case c == ';':
		goto yystate11
	}

	goto yystate167 // silence unused label error
yystate167:
	c = l.getc(c)
yystart167:
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9':
		goto yystate168
	case c == 'D':
		goto yystate108
	case c == 'A':
		goto yystate140
	case c == 'W':
		goto yystate105
	case c == 'K':
		goto yystate88
	case c == 'R':
		goto yystate69
	case c == 'M':
		goto yystate162
	case c == '"':
		goto yystate6
	case c == 'L':
		goto yystate127
	case c == 'T':
		goto yystate134
	case c == ')':
		goto yystate5
	case c == 'H':
		goto yystate171
	case c == '\t' || c == ' ':
		goto yystate48
	case c == 'G':
		goto yystate84
	case c == 'C':
		goto yystate169
	case c == '(':
		goto yystate31
	case c == 'X':
		goto yystate137
	case c == 'S':
		goto yystate92
	case c == 'P':
		goto yystate130
	case c == 'N':
		goto yystate51
	case c == 'I':
		goto yystate173
	case c == '\n' || c == '\r':
		goto yystate12
	case c == ';':
		goto yystate11
	}

yystate168:
	c = l.getc(c)
	switch {
	default:
		goto yyrule15
	case c >= '0' && c <= '9':
		goto yystate168
	}

yystate169:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'N':
		goto yystate77
	case c == 'H':
		goto yystate170
	case c == 'E':
		goto yystate81
	}

yystate170:
	c = l.getc(c)
	goto yyrule17

yystate171:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'S':
		goto yystate172
	case c == 'I':
		goto yystate123
	}

yystate172:
	c = l.getc(c)
	goto yyrule18

yystate173:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'P':
		goto yystate155
	case c == 'S':
		goto yystate152
	case c == 'N':
		goto yystate174
	}

yystate174:
	c = l.getc(c)
	goto yyrule16

	goto yystate175 // silence unused label error
yystate175:
	c = l.getc(c)
yystart175:
	switch {
	default:
		goto yyabort
	case c == '"':
		goto yystate6
	case c == ')':
		goto yystate5
	case c == '\t' || c == ' ':
		goto yystate48
	case c == '(':
		goto yystate31
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate176
	case c == ':':
		goto yystate187
	case c == '\n' || c == '\r':
		goto yystate12
	case c == ';':
		goto yystate11
	}

yystate176:
	c = l.getc(c)
	switch {
	default:
		goto yyrule59
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate177
	case c == ':':
		goto yystate180
	}

yystate177:
	c = l.getc(c)
	switch {
	default:
		goto yyrule59
	case c == ':':
		goto yystate180
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate178
	}

yystate178:
	c = l.getc(c)
	switch {
	default:
		goto yyrule59
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate179
	case c == ':':
		goto yystate180
	}

yystate179:
	c = l.getc(c)
	switch {
	default:
		goto yyrule59
	case c == ':':
		goto yystate180
	}

yystate180:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == ':':
		goto yystate181
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate176
	}

yystate181:
	c = l.getc(c)
	switch {
	default:
		goto yyrule59
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate182
	}

yystate182:
	c = l.getc(c)
	switch {
	default:
		goto yyrule59
	case c == ':':
		goto yystate186
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate183
	}

yystate183:
	c = l.getc(c)
	switch {
	default:
		goto yyrule59
	case c == ':':
		goto yystate186
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate184
	}

yystate184:
	c = l.getc(c)
	switch {
	default:
		goto yyrule59
	case c == ':':
		goto yystate186
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate185
	}

yystate185:
	c = l.getc(c)
	switch {
	default:
		goto yyrule59
	case c == ':':
		goto yystate186
	}

yystate186:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate182
	}

yystate187:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == ':':
		goto yystate181
	}

	goto yystate188 // silence unused label error
yystate188:
	c = l.getc(c)
yystart188:
	switch {
	default:
		goto yyabort
	case c == '"':
		goto yystate6
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate189
	case c == ')':
		goto yystate5
	case c == '\t' || c == ' ':
		goto yystate48
	case c == '(':
		goto yystate31
	case c == '-':
		goto yystate190
	case c == '\n' || c == '\r':
		goto yystate12
	case c == ';':
		goto yystate11
	}

yystate189:
	c = l.getc(c)
	switch {
	default:
		goto yyrule62
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate189
	}

yystate190:
	c = l.getc(c)
	goto yyrule63

	goto yystate191 // silence unused label error
yystate191:
	c = l.getc(c)
yystart191:
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9':
		goto yystate168
	case c == 'D':
		goto yystate108
	case c == 'A':
		goto yystate140
	case c == 'W':
		goto yystate105
	case c == 'K':
		goto yystate88
	case c == 'R':
		goto yystate69
	case c == 'M':
		goto yystate162
	case c == '"':
		goto yystate6
	case c == 'L':
		goto yystate127
	case c == 'T':
		goto yystate134
	case c == ')':
		goto yystate5
	case c == 'H':
		goto yystate171
	case c == '\t' || c == ' ':
		goto yystate48
	case c == 'G':
		goto yystate84
	case c == 'C':
		goto yystate169
	case c == '(':
		goto yystate31
	case c == 'X':
		goto yystate137
	case c == 'S':
		goto yystate92
	case c == 'P':
		goto yystate130
	case c == 'N':
		goto yystate51
	case c == 'I':
		goto yystate173
	case c == '\n' || c == '\r':
		goto yystate12
	case c == ';':
		goto yystate11
	}

	goto yystate192 // silence unused label error
yystate192:
	c = l.getc(c)
yystart192:
	switch {
	default:
		goto yyabort
	case c == '"':
		goto yystate6
	case c == ')':
		goto yystate5
	case c == '\t' || c == ' ':
		goto yystate48
	case c == '(':
		goto yystate31
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate176
	case c == ':':
		goto yystate187
	case c == '\n' || c == '\r':
		goto yystate12
	case c == ';':
		goto yystate11
	}

	goto yystate193 // silence unused label error
yystate193:
	c = l.getc(c)
yystart193:
	switch {
	default:
		goto yyabort
	case c == '"':
		goto yystate6
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate189
	case c == ')':
		goto yystate5
	case c == '\t' || c == ' ':
		goto yystate48
	case c == '(':
		goto yystate31
	case c == '-':
		goto yystate190
	case c == '\n' || c == '\r':
		goto yystate12
	case c == ';':
		goto yystate11
	}

	goto yystate194 // silence unused label error
yystate194:
	c = l.getc(c)
yystart194:
	switch {
	default:
		goto yyabort
	case c == '.':
		goto yystate198
	case c == '"':
		goto yystate6
	case c == ')':
		goto yystate5
	case c == '\t' || c == ' ':
		goto yystate48
	case c == '(':
		goto yystate31
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate195
	case c == '\n' || c == '\r':
		goto yystate12
	case c == ';':
		goto yystate11
	}

yystate195:
	c = l.getc(c)
	switch {
	default:
		goto yyrule13
	case c == '-':
		goto yystate196
	case c == '.':
		goto yystate197
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate195
	}

yystate196:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == '-':
		goto yystate196
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate195
	}

yystate197:
	c = l.getc(c)
	switch {
	default:
		goto yyrule13
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate195
	}

yystate198:
	c = l.getc(c)
	goto yyrule13

	goto yystate199 // silence unused label error
yystate199:
	c = l.getc(c)
yystart199:
	switch {
	default:
		goto yyabort
	case c == '"':
		goto yystate6
	case c == ')':
		goto yystate5
	case c >= '0' && c <= '9' || c == '=' || c >= 'A' && c <= 'V':
		goto yystate200
	case c == '\t' || c == ' ':
		goto yystate48
	case c == '(':
		goto yystate31
	case c == '\n' || c == '\r':
		goto yystate12
	case c == ';':
		goto yystate11
	}

yystate200:
	c = l.getc(c)
	switch {
	default:
		goto yyrule60
	case c >= '0' && c <= '9' || c == '=' || c >= 'A' && c <= 'V':
		goto yystate200
	}

	goto yystate201 // silence unused label error
yystate201:
	c = l.getc(c)
yystart201:
	switch {
	default:
		goto yyabort
	case c == '.':
		goto yystate198
	case c == '"':
		goto yystate6
	case c == ')':
		goto yystate5
	case c == '\t' || c == ' ':
		goto yystate48
	case c == '(':
		goto yystate31
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate195
	case c == '\n' || c == '\r':
		goto yystate12
	case c == ';':
		goto yystate11
	}

	goto yystate202 // silence unused label error
yystate202:
	c = l.getc(c)
yystart202:
	switch {
	default:
		goto yyabort
	case c == '"':
		goto yystate6
	case c == ')':
		goto yystate5
	case c >= '0' && c <= '9' || c == '=' || c >= 'A' && c <= 'V':
		goto yystate200
	case c == '\t' || c == ' ':
		goto yystate48
	case c == '(':
		goto yystate31
	case c == '\n' || c == '\r':
		goto yystate12
	case c == ';':
		goto yystate11
	}

	goto yystate203 // silence unused label error
yystate203:
	c = l.getc(c)
yystart203:
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9':
		goto yystate168
	case c == '"':
		goto yystate6
	case c == ')':
		goto yystate5
	case c == '\t' || c == ' ':
		goto yystate48
	case c == '(':
		goto yystate31
	case c == '\n' || c == '\r':
		goto yystate12
	case c == ';':
		goto yystate11
	}

	goto yystate204 // silence unused label error
yystate204:
	c = l.getc(c)
yystart204:
	switch {
	default:
		goto yyabort
	case c == '"':
		goto yystate6
	case c == ')':
		goto yystate5
	case c == '\t' || c == ' ':
		goto yystate48
	case c == '(':
		goto yystate31
	case c == '+' || c >= '/' && c <= '9' || c == '=' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate205
	case c == '\n' || c == '\r':
		goto yystate12
	case c == ';':
		goto yystate11
	}

yystate205:
	c = l.getc(c)
	switch {
	default:
		goto yyrule61
	case c == '+' || c >= '/' && c <= '9' || c == '=' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate205
	}

	goto yystate206 // silence unused label error
yystate206:
	c = l.getc(c)
yystart206:
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9':
		goto yystate168
	case c == '"':
		goto yystate6
	case c == ')':
		goto yystate5
	case c == '\t' || c == ' ':
		goto yystate48
	case c == '(':
		goto yystate31
	case c == '\n' || c == '\r':
		goto yystate12
	case c == ';':
		goto yystate11
	}

	goto yystate207 // silence unused label error
yystate207:
	c = l.getc(c)
yystart207:
	switch {
	default:
		goto yyabort
	case c == '"':
		goto yystate6
	case c == ')':
		goto yystate5
	case c == '\t' || c == ' ':
		goto yystate48
	case c == '(':
		goto yystate31
	case c == '+' || c >= '/' && c <= '9' || c == '=' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate205
	case c == '\n' || c == '\r':
		goto yystate12
	case c == ';':
		goto yystate11
	}

yyrule1: // ^[ \t]+$
yyrule2: // [ \t]+$
yyrule3: // [ \t]*;.*
	{
		// ignored
		goto yystate0
	}
yyrule4: // ^$INCLUDE

	goto yystate0
yyrule5: // ^$ORIGIN

	goto yystate0
yyrule6: // ^$TTL
	{

		ret = tDLR_TTL
		goto yystate0
	}
yyrule7: // \n|\r
	{

		if !l.inParen {
			ret = '\n'
		}
		goto yystate0
	}
yyrule8: // \(
	{

		if l.inParen {
			l.Error("nested parenthesis")
		}
		l.inParen = true
		goto yystate0
	}
yyrule9: // \)
	{

		if !l.inParen {
			l.Error(`enexpected ")"`)
		}
		l.inParen = false
		ret = '\n'
		goto yystate0
	}
yyrule10: // ^{domain-name}
	{

		ret = tDOMAIN_NAME
		goto yystate0
	}
yyrule11: // ^[ \t]+
	{

		ret = tBLANK_START
		goto yystate0
	}
yyrule12: // \"(\\.|[^\\"\n\r])*\"
	{

		lval.str = string(bytes.Replace(l.buf[1:len(l.buf)-1], []byte(`\"`), []byte(`"`), -1))
		return tQSTR
		goto yystate0
	}
yyrule13: // {domain-name}
	{

		ret = tDOMAIN_NAME
		goto yystate0
	}
yyrule14: // [ \t]+
	{

		/* RR TTL */
		goto yystate0
	}
yyrule15: // [0-9]+
	{

		lval.str = string(l.buf)
		lval.u64, err = strconv.Atoui64(lval.str)
		if err != nil {
			panic(fmt.Errorf("invalid number %q", l.buf))
		}
		ret = tDECADIC
		/* RR class */
		goto yystate0
	}
yyrule16: // IN
	{

		lval.class = rr.CLASS_IN
		ret = tCLASS
		goto yystate0
	}
yyrule17: // CH
	{

		lval.class = rr.CLASS_CH
		ret = tCLASS
		goto yystate0
	}
yyrule18: // HS
	{

		lval.class = rr.CLASS_HS
		ret = tCLASS
		/* RR types */
		goto yystate0
	}
yyrule19: // A
	{
		ret = tA
		goto yystate0
	}
yyrule20: // AAAA
	{
		ret = tAAAA
		goto yystate0
	}
yyrule21: // A6
	{
		ret = tA6
		goto yystate0
	}
yyrule22: // AFSDB
	{
		ret = tAFSDB
		goto yystate0
	}
yyrule23: // APL
	{
		ret = tAPL
		goto yystate0
	}
yyrule24: // CERT
	{
		ret = tCERT
		goto yystate0
	}
yyrule25: // CNAME
	{
		ret = tCNAME
		goto yystate0
	}
yyrule26: // DHCID
	{
		ret = tDHCID
		goto yystate0
	}
yyrule27: // DNAME
	{
		ret = tDNAME
		goto yystate0
	}
yyrule28: // DNSKEY
	{
		ret = tDNSKEY
		goto yystate0
	}
yyrule29: // DS
	{
		ret = tDS
		goto yystate0
	}
yyrule30: // GPOS
	{
		ret = tGPOS
		goto yystate0
	}
yyrule31: // HINFO
	{
		ret = tHINFO
		goto yystate0
	}
yyrule32: // IPSECKEY
	{
		ret = tIPSECKEY
		goto yystate0
	}
yyrule33: // ISDN
	{
		ret = tISDN
		goto yystate0
	}
yyrule34: // KEY
	{
		ret = tKEY
		goto yystate0
	}
yyrule35: // KX
	{
		ret = tKX
		goto yystate0
	}
yyrule36: // LOC
	{
		ret = tLOC
		goto yystate0
	}
yyrule37: // MX
	{
		ret = tMX
		goto yystate0
	}
yyrule38: // NAPTR
	{
		ret = tNAPTR
		goto yystate0
	}
yyrule39: // NSAP
	{
		ret = tNSAP
		goto yystate0
	}
yyrule40: // NS
	{
		ret = tNS
		goto yystate0
	}
yyrule41: // NSEC
	{
		ret = tNSEC
		goto yystate0
	}
yyrule42: // NSEC3
	{
		ret = tNSEC3
		goto yystate0
	}
yyrule43: // NSEC3PARAM
	{
		ret = tNSEC3PARAM
		goto yystate0
	}
yyrule44: // NXT
	{
		ret = tNXT
		goto yystate0
	}
yyrule45: // PTR
	{
		ret = tPTR
		goto yystate0
	}
yyrule46: // PX
	{
		ret = tPX
		goto yystate0
	}
yyrule47: // RP
	{
		ret = tRP
		goto yystate0
	}
yyrule48: // RRSIG
	{
		ret = tRRSIG
		goto yystate0
	}
yyrule49: // RT
	{
		ret = tRT
		goto yystate0
	}
yyrule50: // SIG
	{
		ret = tSIG
		goto yystate0
	}
yyrule51: // SOA
	{
		ret = tSOA
		goto yystate0
	}
yyrule52: // SPF
	{
		ret = tSPF
		goto yystate0
	}
yyrule53: // SRV
	{
		ret = tSRV
		goto yystate0
	}
yyrule54: // SSHFP
	{
		ret = tSSHFP
		goto yystate0
	}
yyrule55: // TXT
	{
		ret = tTXT
		goto yystate0
	}
yyrule56: // WKS
	{
		ret = tWKS
		goto yystate0
	}
yyrule57: // X25
	{
		ret = tX25
		goto yystate0
	}
yyrule58: // {ipv4}
	{

		ip := net.ParseIP(string(l.buf))
		if ip == nil {
			l.Error(fmt.Sprintf("invalid IP %q", l.buf))
		}
		lval.ip = ip
		return tIPV4
		goto yystate0
	}
yyrule59: // {ipv6}
	{

		ip := net.ParseIP(string(l.buf))
		if ip == nil {
			l.Error(fmt.Sprintf("invalid IP %q", l.buf))
		}
		lval.ip = ip
		return tIPV6
		goto yystate0
	}
yyrule60: // [0-9A-V=]+
	{

		ret = tBASE32EXT
		goto yystate0
	}
yyrule61: // [A-Za-z0-9+/=]+
	{

		ret = tBASE64
		goto yystate0
	}
yyrule62: // [0-9a-fA-F]+
	{

		var err os.Error
		lval.data, err = hex.DecodeString(string(l.buf))
		if err != nil {
			l.Error("expected hex string")
		}
		ret = tHEX
		goto yystate0
	}
yyrule63: // -
	{

		lval.data = nil
		ret = tHEX
		goto yystate0
	}
		panic("unreachable")

		goto yyabort // silence unused label error

yyabort: // no lexem recognized
	// no pattern recognized
	if len(l.buf) == 0 {
		ret = int(c)
		l.getc(0)
		return
	}

	return unicode.ReplacementChar
}
