// Copyright (c) 2011 CZ.NIC z.s.p.o. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// blame: jnml, labs.nic.cz

// WARNING: If this file is scanner.go then DO NOT EDIT.
// scanner.go is generated by golex from scanner.l (see the Makefile).


package zone

import (
	"bufio"
	"bytes"
	"encoding/hex"
	"errors"
	"fmt"
	"github.com/cznic/dns/rr"
	"io"
	"net"
	"strconv"
	"unicode"
)

type lexStackItem struct {
	rrHandler  func(*rr.RR) bool
	errHandler func(e string) bool
	startCond  int
	buf        []byte
	last       byte
	peek       byte
	line       int
	column     int
	name       string
	src        *bufio.Reader
	prev       *lexStackItem
	inParen    bool
}

type lex struct {
	lexStackItem
}

func (l *lex) include(name string, source *bufio.Reader) {
	push := &lexStackItem{}
	*push = l.lexStackItem
	l.buf = nil
	l.line = 1
	l.column = 0
	l.name = name
	l.src = source
	l.prev = push
	l.getc(0)
}

func (l *lex) getc(c byte) byte {
	if c != 0 {
		l.buf = append(l.buf, c)
	}
	l.last = l.peek
	if b, err := l.src.ReadByte(); err == nil {
		if b == '\n' {
			l.line++
			l.column = 0
		} else {
			l.column++
		}
		l.peek = b
		return b
	} else {
		if err == io.EOF {
			l.peek = 0
			return 0
		}
		panic(err)
	}

	panic("unreachable")
}

func newLex(name string, source *bufio.Reader, errHandler func(e string) bool, rrHandler func(*rr.RR) bool) (l *lex) {
	l = &lex{}
	l.errHandler = errHandler
	l.rrHandler = rrHandler
	l.line = 1
	l.name = name
	l.src = source
	l.getc(0)
	return
}

func (l *lex) Error(e string) {
	e = fmt.Sprintf("%s:%d:%d - %s", l.name, l.line, l.column, e)
	if l.errHandler != nil {
		if l.errHandler(e) {
			return
		}
	}
	panic(errors.New(e))
}

func (l *lex) begin(sc int) {
	l.startCond = sc
}

const (
	sc_INITIAL = iota
	sc_RRHEAD
	sc_DOMAIN
	sc_NUM
	sc_IPV4
	sc_IPV6
	sc_BASE32EXT
	sc_BASE64
	sc_TYPE
	sc_HEX
	sc_QSTR
)

func (l *lex) Lex(lval *yySymType) (ret int) {
	var err error

	/* debug helper
	defer func(sc0 int) {
		var s string
		if ret > 255 {
			if x := ret - 0xE002; x < len(yyToknames) {
				s = yyToknames[x]
			}
		}
		fmt.Printf("*lex.Lex() %s:%d:%d - %d %q %s buf %q, sc %d->%d\n", l.name, l.line, l.column, ret, string(ret), s, l.buf, sc0, l.startCond)
	}(l.startCond) //*/

	c := l.peek
	ret = -1

yystate0:

	if ret >= 0 {
		lval.str = string(l.buf)
		return
	}
	l.buf = l.buf[:0]

	switch yyt, yyb := l.startCond, l.last == '\n' || l.last == 0; yyt {
	default:
		panic(fmt.Errorf(`invalid start condition %d`, yyt))
	case 0: // start condition: INITIAL
		if yyb {
			goto yystart41
		}
		goto yystart243
	case 4: // start condition: ipv4
		if yyb {
			goto yystart65
		}
		goto yystart244
	case 8: // start condition: type
		if yyb {
			goto yystart81
		}
		goto yystart245
	case 1: // start condition: rrHead
		if yyb {
			goto yystart246
		}
		goto yystart255
	case 5: // start condition: ipv6
		if yyb {
			goto yystart253
		}
		goto yystart1
	case 9: // start condition: hex
		if yyb {
			goto yystart254
		}
		goto yystart23
	case 2: // start condition: domain
		if yyb {
			goto yystart26
		}
		goto yystart33
	case 6: // start condition: base32ext
		if yyb {
			goto yystart31
		}
		goto yystart34
	case 3: // start condition: num
		if yyb {
			goto yystart35
		}
		goto yystart39
	case 7: // start condition: base64
		if yyb {
			goto yystart37
		}
		goto yystart40
	}

	goto yystate1 // silence unused label error
yystate1:
	c = l.getc(c)
yystart1:
	switch {
	default:
		goto yyabort
	case c == ';':
		goto yystate15
	case c == '(':
		goto yystate18
	case c == '"':
		goto yystate20
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate9
	case c == '\t' || c == ' ':
		goto yystate16
	case c == ')':
		goto yystate19
	case c == ':':
		goto yystate2
	case c == '\n' || c == '\r':
		goto yystate14
	}

yystate2:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == ':':
		goto yystate3
	}

yystate3:
	c = l.getc(c)
	switch {
	default:
		goto yyrule74
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate4
	}

yystate4:
	c = l.getc(c)
	switch {
	default:
		goto yyrule74
	case c == ':':
		goto yystate8
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate5
	}

yystate5:
	c = l.getc(c)
	switch {
	default:
		goto yyrule74
	case c == ':':
		goto yystate8
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate6
	}

yystate6:
	c = l.getc(c)
	switch {
	default:
		goto yyrule74
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate7
	case c == ':':
		goto yystate8
	}

yystate7:
	c = l.getc(c)
	switch {
	default:
		goto yyrule74
	case c == ':':
		goto yystate8
	}

yystate8:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate4
	}

yystate9:
	c = l.getc(c)
	switch {
	default:
		goto yyrule74
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate10
	case c == ':':
		goto yystate13
	}

yystate10:
	c = l.getc(c)
	switch {
	default:
		goto yyrule74
	case c == ':':
		goto yystate13
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate11
	}

yystate11:
	c = l.getc(c)
	switch {
	default:
		goto yyrule74
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate12
	case c == ':':
		goto yystate13
	}

yystate12:
	c = l.getc(c)
	switch {
	default:
		goto yyrule74
	case c == ':':
		goto yystate13
	}

yystate13:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate9
	case c == ':':
		goto yystate3
	}

yystate14:
	c = l.getc(c)
	goto yyrule7

yystate15:
	c = l.getc(c)
	switch {
	default:
		goto yyrule3
	case c >= '\x01' && c <= '\t' || c >= '\v' && c <= 'ÿ':
		goto yystate15
	}

yystate16:
	c = l.getc(c)
	switch {
	default:
		goto yyrule14
	case c == ';':
		goto yystate15
	case c == '\x00' || c == '\n':
		goto yystate17
	case c == '\t' || c == ' ':
		goto yystate16
	}

yystate17:
	goto yyrule2

yystate18:
	c = l.getc(c)
	goto yyrule8

yystate19:
	c = l.getc(c)
	goto yyrule9

yystate20:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == '"':
		goto yystate22
	case c == '\\':
		goto yystate21
	case c >= '\x01' && c <= '\t' || c == '\v' || c == '\f' || c >= '\x0e' && c <= '!' || c >= '#' && c <= '[' || c >= ']' && c <= 'ÿ':
		goto yystate20
	}

yystate21:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c >= '\x01' && c <= '\t' || c >= '\v' && c <= 'ÿ':
		goto yystate20
	}

yystate22:
	c = l.getc(c)
	goto yyrule12

	goto yystate23 // silence unused label error
yystate23:
	c = l.getc(c)
yystart23:
	switch {
	default:
		goto yyabort
	case c == '\t' || c == ' ':
		goto yystate16
	case c == ')':
		goto yystate19
	case c == '\n' || c == '\r':
		goto yystate14
	case c == ';':
		goto yystate15
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate24
	case c == '(':
		goto yystate18
	case c == '"':
		goto yystate20
	case c == '-':
		goto yystate25
	}

yystate24:
	c = l.getc(c)
	switch {
	default:
		goto yyrule77
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate24
	}

yystate25:
	c = l.getc(c)
	goto yyrule78

	goto yystate26 // silence unused label error
yystate26:
	c = l.getc(c)
yystart26:
	switch {
	default:
		goto yyabort
	case c == '.':
		goto yystate30
	case c == '\t' || c == ' ':
		goto yystate16
	case c == ')':
		goto yystate19
	case c == '\n' || c == '\r':
		goto yystate14
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate27
	case c == ';':
		goto yystate15
	case c == '(':
		goto yystate18
	case c == '"':
		goto yystate20
	}

yystate27:
	c = l.getc(c)
	switch {
	default:
		goto yyrule13
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate27
	case c == '-':
		goto yystate28
	case c == '.':
		goto yystate29
	}

yystate28:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate27
	case c == '-':
		goto yystate28
	}

yystate29:
	c = l.getc(c)
	switch {
	default:
		goto yyrule13
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate27
	}

yystate30:
	c = l.getc(c)
	goto yyrule13

	goto yystate31 // silence unused label error
yystate31:
	c = l.getc(c)
yystart31:
	switch {
	default:
		goto yyabort
	case c == '"':
		goto yystate20
	case c == '\t' || c == ' ':
		goto yystate16
	case c == ')':
		goto yystate19
	case c >= '0' && c <= '9' || c == '=' || c >= 'A' && c <= 'V':
		goto yystate32
	case c == '\n' || c == '\r':
		goto yystate14
	case c == ';':
		goto yystate15
	case c == '(':
		goto yystate18
	}

yystate32:
	c = l.getc(c)
	switch {
	default:
		goto yyrule75
	case c >= '0' && c <= '9' || c == '=' || c >= 'A' && c <= 'V':
		goto yystate32
	}

	goto yystate33 // silence unused label error
yystate33:
	c = l.getc(c)
yystart33:
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate27
	case c == ';':
		goto yystate15
	case c == '(':
		goto yystate18
	case c == '"':
		goto yystate20
	case c == '.':
		goto yystate30
	case c == '\t' || c == ' ':
		goto yystate16
	case c == ')':
		goto yystate19
	case c == '\n' || c == '\r':
		goto yystate14
	}

	goto yystate34 // silence unused label error
yystate34:
	c = l.getc(c)
yystart34:
	switch {
	default:
		goto yyabort
	case c == ';':
		goto yystate15
	case c == '(':
		goto yystate18
	case c == '"':
		goto yystate20
	case c == '\t' || c == ' ':
		goto yystate16
	case c == ')':
		goto yystate19
	case c >= '0' && c <= '9' || c == '=' || c >= 'A' && c <= 'V':
		goto yystate32
	case c == '\n' || c == '\r':
		goto yystate14
	}

	goto yystate35 // silence unused label error
yystate35:
	c = l.getc(c)
yystart35:
	switch {
	default:
		goto yyabort
	case c == ';':
		goto yystate15
	case c == '(':
		goto yystate18
	case c == '"':
		goto yystate20
	case c >= '0' && c <= '9':
		goto yystate36
	case c == '\t' || c == ' ':
		goto yystate16
	case c == ')':
		goto yystate19
	case c == '\n' || c == '\r':
		goto yystate14
	}

yystate36:
	c = l.getc(c)
	switch {
	default:
		goto yyrule15
	case c >= '0' && c <= '9':
		goto yystate36
	}

	goto yystate37 // silence unused label error
yystate37:
	c = l.getc(c)
yystart37:
	switch {
	default:
		goto yyabort
	case c == '+' || c >= '/' && c <= '9' || c == '=' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate38
	case c == ';':
		goto yystate15
	case c == '(':
		goto yystate18
	case c == '"':
		goto yystate20
	case c == '\t' || c == ' ':
		goto yystate16
	case c == ')':
		goto yystate19
	case c == '\n' || c == '\r':
		goto yystate14
	}

yystate38:
	c = l.getc(c)
	switch {
	default:
		goto yyrule76
	case c == '+' || c >= '/' && c <= '9' || c == '=' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate38
	}

	goto yystate39 // silence unused label error
yystate39:
	c = l.getc(c)
yystart39:
	switch {
	default:
		goto yyabort
	case c == ';':
		goto yystate15
	case c == '(':
		goto yystate18
	case c == '"':
		goto yystate20
	case c >= '0' && c <= '9':
		goto yystate36
	case c == '\t' || c == ' ':
		goto yystate16
	case c == ')':
		goto yystate19
	case c == '\n' || c == '\r':
		goto yystate14
	}

	goto yystate40 // silence unused label error
yystate40:
	c = l.getc(c)
yystart40:
	switch {
	default:
		goto yyabort
	case c == ')':
		goto yystate19
	case c == '\n' || c == '\r':
		goto yystate14
	case c == '+' || c >= '/' && c <= '9' || c == '=' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate38
	case c == ';':
		goto yystate15
	case c == '(':
		goto yystate18
	case c == '"':
		goto yystate20
	case c == '\t' || c == ' ':
		goto yystate16
	}

	goto yystate41 // silence unused label error
yystate41:
	c = l.getc(c)
yystart41:
	switch {
	default:
		goto yyabort
	case c == '.':
		goto yystate64
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate42
	case c == ';':
		goto yystate15
	case c == '(':
		goto yystate18
	case c == '"':
		goto yystate20
	case c == ')':
		goto yystate19
	case c == '$':
		goto yystate47
	case c == '\n' || c == '\r':
		goto yystate14
	case c == '\t' || c == ' ':
		goto yystate45
	}

yystate42:
	c = l.getc(c)
	switch {
	default:
		goto yyrule10
	case c == '.':
		goto yystate44
	case c == '-':
		goto yystate43
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate42
	}

yystate43:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == '-':
		goto yystate43
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate42
	}

yystate44:
	c = l.getc(c)
	switch {
	default:
		goto yyrule10
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate42
	}

yystate45:
	c = l.getc(c)
	switch {
	default:
		goto yyrule11
	case c == ';':
		goto yystate15
	case c == '\x00' || c == '\n':
		goto yystate46
	case c == '\t' || c == ' ':
		goto yystate45
	}

yystate46:
	goto yyrule1

yystate47:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'T':
		goto yystate54
	case c == 'O':
		goto yystate48
	case c == 'I':
		goto yystate57
	}

yystate48:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'R':
		goto yystate49
	}

yystate49:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'I':
		goto yystate50
	}

yystate50:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'G':
		goto yystate51
	}

yystate51:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'I':
		goto yystate52
	}

yystate52:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'N':
		goto yystate53
	}

yystate53:
	c = l.getc(c)
	goto yyrule5

yystate54:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'T':
		goto yystate55
	}

yystate55:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'L':
		goto yystate56
	}

yystate56:
	c = l.getc(c)
	goto yyrule6

yystate57:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'N':
		goto yystate58
	}

yystate58:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'C':
		goto yystate59
	}

yystate59:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'L':
		goto yystate60
	}

yystate60:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'U':
		goto yystate61
	}

yystate61:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'D':
		goto yystate62
	}

yystate62:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'E':
		goto yystate63
	}

yystate63:
	c = l.getc(c)
	goto yyrule4

yystate64:
	c = l.getc(c)
	goto yyrule10

	goto yystate65 // silence unused label error
yystate65:
	c = l.getc(c)
yystart65:
	switch {
	default:
		goto yyabort
	case c == '\n' || c == '\r':
		goto yystate14
	case c >= '0' && c <= '9':
		goto yystate66
	case c == ';':
		goto yystate15
	case c == '(':
		goto yystate18
	case c == '"':
		goto yystate20
	case c == '\t' || c == ' ':
		goto yystate16
	case c == ')':
		goto yystate19
	}

yystate66:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == '.':
		goto yystate69
	case c >= '0' && c <= '9':
		goto yystate67
	}

yystate67:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9':
		goto yystate68
	case c == '.':
		goto yystate69
	}

yystate68:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == '.':
		goto yystate69
	}

yystate69:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9':
		goto yystate70
	}

yystate70:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9':
		goto yystate71
	case c == '.':
		goto yystate73
	}

yystate71:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9':
		goto yystate72
	case c == '.':
		goto yystate73
	}

yystate72:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == '.':
		goto yystate73
	}

yystate73:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9':
		goto yystate74
	}

yystate74:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9':
		goto yystate75
	case c == '.':
		goto yystate77
	}

yystate75:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == '.':
		goto yystate77
	case c >= '0' && c <= '9':
		goto yystate76
	}

yystate76:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == '.':
		goto yystate77
	}

yystate77:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9':
		goto yystate78
	}

yystate78:
	c = l.getc(c)
	switch {
	default:
		goto yyrule73
	case c >= '0' && c <= '9':
		goto yystate79
	}

yystate79:
	c = l.getc(c)
	switch {
	default:
		goto yyrule73
	case c >= '0' && c <= '9':
		goto yystate80
	}

yystate80:
	c = l.getc(c)
	goto yyrule73

	goto yystate81 // silence unused label error
yystate81:
	c = l.getc(c)
yystart81:
	switch {
	default:
		goto yyabort
	case c == ';':
		goto yystate15
	case c == '(':
		goto yystate18
	case c == 'X':
		goto yystate109
	case c == 'N':
		goto yystate153
	case c == '"':
		goto yystate20
	case c == 'I':
		goto yystate129
	case c == 'T':
		goto yystate95
	case c == 'P':
		goto yystate91
	case c == 'W':
		goto yystate226
	case c == 'C':
		goto yystate193
	case c == 'M':
		goto yystate140
	case c == '\t' || c == ' ':
		goto yystate16
	case c == ')':
		goto yystate19
	case c == 'U':
		goto yystate142
	case c == 'R':
		goto yystate183
	case c == 'A':
		goto yystate112
	case c == '\n' || c == '\r':
		goto yystate14
	case c == 'H':
		goto yystate82
	case c == 'E':
		goto yystate126
	case c == 'D':
		goto yystate229
	case c == 'G':
		goto yystate203
	case c == 'K':
		goto yystate209
	case c == 'L':
		goto yystate88
	case c == 'S':
		goto yystate213
	}

yystate82:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'I':
		goto yystate83
	}

yystate83:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'N':
		goto yystate85
	case c == 'P':
		goto yystate84
	}

yystate84:
	c = l.getc(c)
	goto yyrule36

yystate85:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'F':
		goto yystate86
	}

yystate86:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'O':
		goto yystate87
	}

yystate87:
	c = l.getc(c)
	goto yyrule35

yystate88:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'O':
		goto yystate89
	}

yystate89:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'C':
		goto yystate90
	}

yystate90:
	c = l.getc(c)
	goto yyrule41

yystate91:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'X':
		goto yystate94
	case c == 'T':
		goto yystate92
	}

yystate92:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'R':
		goto yystate93
	}

yystate93:
	c = l.getc(c)
	goto yyrule53

yystate94:
	c = l.getc(c)
	goto yyrule54

yystate95:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'X':
		goto yystate96
	case c == 'K':
		goto yystate103
	case c == 'A':
		goto yystate98
	case c == 'S':
		goto yystate106
	}

yystate96:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'T':
		goto yystate97
	}

yystate97:
	c = l.getc(c)
	goto yyrule67

yystate98:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'L':
		goto yystate99
	}

yystate99:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'I':
		goto yystate100
	}

yystate100:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'N':
		goto yystate101
	}

yystate101:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'K':
		goto yystate102
	}

yystate102:
	c = l.getc(c)
	goto yyrule64

yystate103:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'E':
		goto yystate104
	}

yystate104:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'Y':
		goto yystate105
	}

yystate105:
	c = l.getc(c)
	goto yyrule65

yystate106:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'I':
		goto yystate107
	}

yystate107:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'G':
		goto yystate108
	}

yystate108:
	c = l.getc(c)
	goto yyrule66

yystate109:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == '2':
		goto yystate110
	}

yystate110:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == '5':
		goto yystate111
	}

yystate111:
	c = l.getc(c)
	goto yyrule72

yystate112:
	c = l.getc(c)
	switch {
	default:
		goto yyrule19
	case c == 'P':
		goto yystate114
	case c == 'A':
		goto yystate119
	case c == '6':
		goto yystate113
	case c == 'F':
		goto yystate122
	case c == 'T':
		goto yystate116
	}

yystate113:
	c = l.getc(c)
	goto yyrule20

yystate114:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'L':
		goto yystate115
	}

yystate115:
	c = l.getc(c)
	goto yyrule23

yystate116:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'M':
		goto yystate117
	}

yystate117:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'A':
		goto yystate118
	}

yystate118:
	c = l.getc(c)
	goto yyrule24

yystate119:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'A':
		goto yystate120
	}

yystate120:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'A':
		goto yystate121
	}

yystate121:
	c = l.getc(c)
	goto yyrule21

yystate122:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'S':
		goto yystate123
	}

yystate123:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'D':
		goto yystate124
	}

yystate124:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'B':
		goto yystate125
	}

yystate125:
	c = l.getc(c)
	goto yyrule22

yystate126:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'I':
		goto yystate127
	}

yystate127:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'D':
		goto yystate128
	}

yystate128:
	c = l.getc(c)
	goto yyrule32

yystate129:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'S':
		goto yystate130
	case c == 'P':
		goto yystate133
	}

yystate130:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'D':
		goto yystate131
	}

yystate131:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'N':
		goto yystate132
	}

yystate132:
	c = l.getc(c)
	goto yyrule38

yystate133:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'S':
		goto yystate134
	}

yystate134:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'E':
		goto yystate135
	}

yystate135:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'C':
		goto yystate136
	}

yystate136:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'K':
		goto yystate137
	}

yystate137:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'E':
		goto yystate138
	}

yystate138:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'Y':
		goto yystate139
	}

yystate139:
	c = l.getc(c)
	goto yyrule37

yystate140:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'X':
		goto yystate141
	}

yystate141:
	c = l.getc(c)
	goto yyrule42

yystate142:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'N':
		goto yystate143
	case c == 'I':
		goto yystate148
	}

yystate143:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'S':
		goto yystate144
	}

yystate144:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'P':
		goto yystate145
	}

yystate145:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'E':
		goto yystate146
	}

yystate146:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'C':
		goto yystate147
	}

yystate147:
	c = l.getc(c)
	goto yyrule70

yystate148:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'N':
		goto yystate149
	case c == 'D':
		goto yystate152
	}

yystate149:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'F':
		goto yystate150
	}

yystate150:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'O':
		goto yystate151
	}

yystate151:
	c = l.getc(c)
	goto yyrule69

yystate152:
	c = l.getc(c)
	goto yyrule68

yystate153:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'I':
		goto yystate175
	case c == 'S':
		goto yystate154
	case c == 'A':
		goto yystate171
	case c == 'X':
		goto yystate169
	}

yystate154:
	c = l.getc(c)
	switch {
	default:
		goto yyrule46
	case c == 'E':
		goto yystate161
	case c == 'A':
		goto yystate155
	}

yystate155:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'P':
		goto yystate156
	}

yystate156:
	c = l.getc(c)
	switch {
	default:
		goto yyrule47
	case c == '-':
		goto yystate157
	}

yystate157:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'P':
		goto yystate158
	}

yystate158:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'T':
		goto yystate159
	}

yystate159:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'R':
		goto yystate160
	}

yystate160:
	c = l.getc(c)
	goto yyrule48

yystate161:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'C':
		goto yystate162
	}

yystate162:
	c = l.getc(c)
	switch {
	default:
		goto yyrule49
	case c == '3':
		goto yystate163
	}

yystate163:
	c = l.getc(c)
	switch {
	default:
		goto yyrule50
	case c == 'P':
		goto yystate164
	}

yystate164:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'A':
		goto yystate165
	}

yystate165:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'R':
		goto yystate166
	}

yystate166:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'A':
		goto yystate167
	}

yystate167:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'M':
		goto yystate168
	}

yystate168:
	c = l.getc(c)
	goto yyrule51

yystate169:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'T':
		goto yystate170
	}

yystate170:
	c = l.getc(c)
	goto yyrule52

yystate171:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'P':
		goto yystate172
	}

yystate172:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'T':
		goto yystate173
	}

yystate173:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'R':
		goto yystate174
	}

yystate174:
	c = l.getc(c)
	goto yyrule43

yystate175:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'M':
		goto yystate176
	case c == 'N':
		goto yystate180
	}

yystate176:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'L':
		goto yystate177
	}

yystate177:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'O':
		goto yystate178
	}

yystate178:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'C':
		goto yystate179
	}

yystate179:
	c = l.getc(c)
	goto yyrule44

yystate180:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'F':
		goto yystate181
	}

yystate181:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'O':
		goto yystate182
	}

yystate182:
	c = l.getc(c)
	goto yyrule45

yystate183:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'P':
		goto yystate191
	case c == 'R':
		goto yystate184
	case c == 'T':
		goto yystate192
	case c == 'K':
		goto yystate188
	}

yystate184:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'S':
		goto yystate185
	}

yystate185:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'I':
		goto yystate186
	}

yystate186:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'G':
		goto yystate187
	}

yystate187:
	c = l.getc(c)
	goto yyrule57

yystate188:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'E':
		goto yystate189
	}

yystate189:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'Y':
		goto yystate190
	}

yystate190:
	c = l.getc(c)
	goto yyrule55

yystate191:
	c = l.getc(c)
	goto yyrule56

yystate192:
	c = l.getc(c)
	goto yyrule58

yystate193:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'D':
		goto yystate194
	case c == 'E':
		goto yystate196
	case c == 'N':
		goto yystate199
	}

yystate194:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'S':
		goto yystate195
	}

yystate195:
	c = l.getc(c)
	goto yyrule25

yystate196:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'R':
		goto yystate197
	}

yystate197:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'T':
		goto yystate198
	}

yystate198:
	c = l.getc(c)
	goto yyrule26

yystate199:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'A':
		goto yystate200
	}

yystate200:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'M':
		goto yystate201
	}

yystate201:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'E':
		goto yystate202
	}

yystate202:
	c = l.getc(c)
	goto yyrule27

yystate203:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'P':
		goto yystate204
	case c == 'I':
		goto yystate207
	}

yystate204:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'O':
		goto yystate205
	}

yystate205:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'S':
		goto yystate206
	}

yystate206:
	c = l.getc(c)
	goto yyrule34

yystate207:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'D':
		goto yystate208
	}

yystate208:
	c = l.getc(c)
	goto yyrule33

yystate209:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'X':
		goto yystate210
	case c == 'E':
		goto yystate211
	}

yystate210:
	c = l.getc(c)
	goto yyrule40

yystate211:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'Y':
		goto yystate212
	}

yystate212:
	c = l.getc(c)
	goto yyrule39

yystate213:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'R':
		goto yystate224
	case c == 'S':
		goto yystate216
	case c == 'I':
		goto yystate222
	case c == 'P':
		goto yystate220
	case c == 'O':
		goto yystate214
	}

yystate214:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'A':
		goto yystate215
	}

yystate215:
	c = l.getc(c)
	goto yyrule60

yystate216:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'H':
		goto yystate217
	}

yystate217:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'F':
		goto yystate218
	}

yystate218:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'P':
		goto yystate219
	}

yystate219:
	c = l.getc(c)
	goto yyrule63

yystate220:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'F':
		goto yystate221
	}

yystate221:
	c = l.getc(c)
	goto yyrule61

yystate222:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'G':
		goto yystate223
	}

yystate223:
	c = l.getc(c)
	goto yyrule59

yystate224:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'V':
		goto yystate225
	}

yystate225:
	c = l.getc(c)
	goto yyrule62

yystate226:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'K':
		goto yystate227
	}

yystate227:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'S':
		goto yystate228
	}

yystate228:
	c = l.getc(c)
	goto yyrule71

yystate229:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'H':
		goto yystate231
	case c == 'S':
		goto yystate230
	case c == 'N':
		goto yystate235
	}

yystate230:
	c = l.getc(c)
	goto yyrule31

yystate231:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'C':
		goto yystate232
	}

yystate232:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'I':
		goto yystate233
	}

yystate233:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'D':
		goto yystate234
	}

yystate234:
	c = l.getc(c)
	goto yyrule28

yystate235:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'S':
		goto yystate236
	case c == 'A':
		goto yystate240
	}

yystate236:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'K':
		goto yystate237
	}

yystate237:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'E':
		goto yystate238
	}

yystate238:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'Y':
		goto yystate239
	}

yystate239:
	c = l.getc(c)
	goto yyrule30

yystate240:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'M':
		goto yystate241
	}

yystate241:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'E':
		goto yystate242
	}

yystate242:
	c = l.getc(c)
	goto yyrule29

	goto yystate243 // silence unused label error
yystate243:
	c = l.getc(c)
yystart243:
	switch {
	default:
		goto yyabort
	case c == '\t' || c == ' ':
		goto yystate16
	case c == ')':
		goto yystate19
	case c == '\n' || c == '\r':
		goto yystate14
	case c == ';':
		goto yystate15
	case c == '(':
		goto yystate18
	case c == '"':
		goto yystate20
	}

	goto yystate244 // silence unused label error
yystate244:
	c = l.getc(c)
yystart244:
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9':
		goto yystate66
	case c == ';':
		goto yystate15
	case c == '(':
		goto yystate18
	case c == '"':
		goto yystate20
	case c == '\t' || c == ' ':
		goto yystate16
	case c == ')':
		goto yystate19
	case c == '\n' || c == '\r':
		goto yystate14
	}

	goto yystate245 // silence unused label error
yystate245:
	c = l.getc(c)
yystart245:
	switch {
	default:
		goto yyabort
	case c == 'C':
		goto yystate193
	case c == 'M':
		goto yystate140
	case c == '\t' || c == ' ':
		goto yystate16
	case c == ')':
		goto yystate19
	case c == 'U':
		goto yystate142
	case c == 'R':
		goto yystate183
	case c == 'A':
		goto yystate112
	case c == '\n' || c == '\r':
		goto yystate14
	case c == 'H':
		goto yystate82
	case c == 'E':
		goto yystate126
	case c == 'D':
		goto yystate229
	case c == 'G':
		goto yystate203
	case c == 'K':
		goto yystate209
	case c == 'L':
		goto yystate88
	case c == 'S':
		goto yystate213
	case c == ';':
		goto yystate15
	case c == '(':
		goto yystate18
	case c == 'X':
		goto yystate109
	case c == 'N':
		goto yystate153
	case c == '"':
		goto yystate20
	case c == 'I':
		goto yystate129
	case c == 'T':
		goto yystate95
	case c == 'P':
		goto yystate91
	case c == 'W':
		goto yystate226
	}

	goto yystate246 // silence unused label error
yystate246:
	c = l.getc(c)
yystart246:
	switch {
	default:
		goto yyabort
	case c == 'M':
		goto yystate140
	case c == '\t' || c == ' ':
		goto yystate16
	case c == ')':
		goto yystate19
	case c == 'U':
		goto yystate142
	case c == 'R':
		goto yystate183
	case c == 'A':
		goto yystate112
	case c == '\n' || c == '\r':
		goto yystate14
	case c == 'E':
		goto yystate126
	case c == 'D':
		goto yystate229
	case c == 'G':
		goto yystate203
	case c == 'K':
		goto yystate209
	case c == 'L':
		goto yystate88
	case c == 'S':
		goto yystate213
	case c == 'H':
		goto yystate247
	case c == 'I':
		goto yystate249
	case c == ';':
		goto yystate15
	case c == '(':
		goto yystate18
	case c == 'X':
		goto yystate109
	case c == 'N':
		goto yystate153
	case c == 'C':
		goto yystate251
	case c == '"':
		goto yystate20
	case c >= '0' && c <= '9':
		goto yystate36
	case c == 'T':
		goto yystate95
	case c == 'P':
		goto yystate91
	case c == 'W':
		goto yystate226
	}

yystate247:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'S':
		goto yystate248
	case c == 'I':
		goto yystate83
	}

yystate248:
	c = l.getc(c)
	goto yyrule18

yystate249:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'P':
		goto yystate133
	case c == 'N':
		goto yystate250
	case c == 'S':
		goto yystate130
	}

yystate250:
	c = l.getc(c)
	goto yyrule16

yystate251:
	c = l.getc(c)
	switch {
	default:
		goto yyabort
	case c == 'E':
		goto yystate196
	case c == 'N':
		goto yystate199
	case c == 'H':
		goto yystate252
	case c == 'D':
		goto yystate194
	}

yystate252:
	c = l.getc(c)
	goto yyrule17

	goto yystate253 // silence unused label error
yystate253:
	c = l.getc(c)
yystart253:
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate9
	case c == '\t' || c == ' ':
		goto yystate16
	case c == ')':
		goto yystate19
	case c == ':':
		goto yystate2
	case c == '\n' || c == '\r':
		goto yystate14
	case c == ';':
		goto yystate15
	case c == '(':
		goto yystate18
	case c == '"':
		goto yystate20
	}

	goto yystate254 // silence unused label error
yystate254:
	c = l.getc(c)
yystart254:
	switch {
	default:
		goto yyabort
	case c == ';':
		goto yystate15
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate24
	case c == '(':
		goto yystate18
	case c == '"':
		goto yystate20
	case c == '-':
		goto yystate25
	case c == '\t' || c == ' ':
		goto yystate16
	case c == ')':
		goto yystate19
	case c == '\n' || c == '\r':
		goto yystate14
	}

	goto yystate255 // silence unused label error
yystate255:
	c = l.getc(c)
yystart255:
	switch {
	default:
		goto yyabort
	case c == ')':
		goto yystate19
	case c == 'U':
		goto yystate142
	case c == 'R':
		goto yystate183
	case c == 'A':
		goto yystate112
	case c == '\n' || c == '\r':
		goto yystate14
	case c == 'E':
		goto yystate126
	case c == 'D':
		goto yystate229
	case c == 'G':
		goto yystate203
	case c == 'K':
		goto yystate209
	case c == 'L':
		goto yystate88
	case c == 'S':
		goto yystate213
	case c == 'H':
		goto yystate247
	case c == 'I':
		goto yystate249
	case c == ';':
		goto yystate15
	case c == '(':
		goto yystate18
	case c == 'X':
		goto yystate109
	case c == 'N':
		goto yystate153
	case c == 'C':
		goto yystate251
	case c == '"':
		goto yystate20
	case c >= '0' && c <= '9':
		goto yystate36
	case c == 'T':
		goto yystate95
	case c == 'P':
		goto yystate91
	case c == 'W':
		goto yystate226
	case c == 'M':
		goto yystate140
	case c == '\t' || c == ' ':
		goto yystate16
	}

yyrule1: // ^[ \t]+$
yyrule2: // [ \t]+$
yyrule3: // [ \t]*;.*
	{
		// ignored
		goto yystate0
	}
yyrule4: // ^$INCLUDE

	goto yystate0
yyrule5: // ^$ORIGIN

	goto yystate0
yyrule6: // ^$TTL
	{

		ret = tDLR_TTL
		goto yystate0
	}
yyrule7: // \n|\r
	{

		if !l.inParen {
			ret = '\n'
		}
		goto yystate0
	}
yyrule8: // \(
	{

		if l.inParen {
			l.Error("nested parenthesis")
		}
		l.inParen = true
		goto yystate0
	}
yyrule9: // \)
	{

		if !l.inParen {
			l.Error(`enexpected ")"`)
		}
		l.inParen = false
		ret = '\n'
		goto yystate0
	}
yyrule10: // ^{domain-name}
	{

		ret = tDOMAIN_NAME
		goto yystate0
	}
yyrule11: // ^[ \t]+
	{

		ret = tBLANK_START
		goto yystate0
	}
yyrule12: // \"(\\.|[^\\"\n\r])*\"
	{

		lval.str = string(bytes.Replace(l.buf[1:len(l.buf)-1], []byte(`\"`), []byte(`"`), -1))
		return tQSTR
	}
yyrule13: // {domain-name}
	{

		ret = tDOMAIN_NAME
		goto yystate0
	}
yyrule14: // [ \t]+
	{

		/* RR TTL */
		goto yystate0
	}
yyrule15: // [0-9]+
	{

		lval.str = string(l.buf)
		lval.u64, err = strconv.Atoui64(lval.str)
		if err != nil {
			panic(fmt.Errorf("invalid number %q", l.buf))
		}
		ret = tDECADIC
		/* RR class */
		goto yystate0
	}
yyrule16: // IN
	{

		lval.class = rr.CLASS_IN
		ret = tCLASS
		goto yystate0
	}
yyrule17: // CH
	{

		lval.class = rr.CLASS_CH
		ret = tCLASS
		goto yystate0
	}
yyrule18: // HS
	{

		lval.class = rr.CLASS_HS
		ret = tCLASS
		/* RR types */
		goto yystate0
	}
yyrule19: // A
	{
		ret = tA
		goto yystate0
	}
yyrule20: // A6
	{
		ret = tA6
		goto yystate0
	}
yyrule21: // AAAA
	{
		ret = tAAAA
		goto yystate0
	}
yyrule22: // AFSDB
	{
		ret = tAFSDB
		goto yystate0
	}
yyrule23: // APL
	{
		ret = tAPL
		goto yystate0
	}
yyrule24: // ATMA
	{
		ret = tATMA
		goto yystate0
	}
yyrule25: // CDS
	{
		ret = tCDS
		goto yystate0
	}
yyrule26: // CERT
	{
		ret = tCERT
		goto yystate0
	}
yyrule27: // CNAME
	{
		ret = tCNAME
		goto yystate0
	}
yyrule28: // DHCID
	{
		ret = tDHCID
		goto yystate0
	}
yyrule29: // DNAME
	{
		ret = tDNAME
		goto yystate0
	}
yyrule30: // DNSKEY
	{
		ret = tDNSKEY
		goto yystate0
	}
yyrule31: // DS
	{
		ret = tDS
		goto yystate0
	}
yyrule32: // EID
	{
		ret = tEID
		goto yystate0
	}
yyrule33: // GID
	{
		ret = tGID
		goto yystate0
	}
yyrule34: // GPOS
	{
		ret = tGPOS
		goto yystate0
	}
yyrule35: // HINFO
	{
		ret = tHINFO
		goto yystate0
	}
yyrule36: // HIP
	{
		ret = tHIP
		goto yystate0
	}
yyrule37: // IPSECKEY
	{
		ret = tIPSECKEY
		goto yystate0
	}
yyrule38: // ISDN
	{
		ret = tISDN
		goto yystate0
	}
yyrule39: // KEY
	{
		ret = tKEY
		goto yystate0
	}
yyrule40: // KX
	{
		ret = tKX
		goto yystate0
	}
yyrule41: // LOC
	{
		ret = tLOC
		goto yystate0
	}
yyrule42: // MX
	{
		ret = tMX
		goto yystate0
	}
yyrule43: // NAPTR
	{
		ret = tNAPTR
		goto yystate0
	}
yyrule44: // NIMLOC
	{
		ret = tNIMLOC
		goto yystate0
	}
yyrule45: // NINFO
	{
		ret = tNINFO
		goto yystate0
	}
yyrule46: // NS
	{
		ret = tNS
		goto yystate0
	}
yyrule47: // NSAP
	{
		ret = tNSAP
		goto yystate0
	}
yyrule48: // NSAP-PTR
	{
		ret = tNSAP_PTR
		goto yystate0
	}
yyrule49: // NSEC
	{
		ret = tNSEC
		goto yystate0
	}
yyrule50: // NSEC3
	{
		ret = tNSEC3
		goto yystate0
	}
yyrule51: // NSEC3PARAM
	{
		ret = tNSEC3PARAM
		goto yystate0
	}
yyrule52: // NXT
	{
		ret = tNXT
		goto yystate0
	}
yyrule53: // PTR
	{
		ret = tPTR
		goto yystate0
	}
yyrule54: // PX
	{
		ret = tPX
		goto yystate0
	}
yyrule55: // RKEY
	{
		ret = tRKEY
		goto yystate0
	}
yyrule56: // RP
	{
		ret = tRP
		goto yystate0
	}
yyrule57: // RRSIG
	{
		ret = tRRSIG
		goto yystate0
	}
yyrule58: // RT
	{
		ret = tRT
		goto yystate0
	}
yyrule59: // SIG
	{
		ret = tSIG
		goto yystate0
	}
yyrule60: // SOA
	{
		ret = tSOA
		goto yystate0
	}
yyrule61: // SPF
	{
		ret = tSPF
		goto yystate0
	}
yyrule62: // SRV
	{
		ret = tSRV
		goto yystate0
	}
yyrule63: // SSHFP
	{
		ret = tSSHFP
		goto yystate0
	}
yyrule64: // TALINK
	{
		ret = tTALINK
		goto yystate0
	}
yyrule65: // TKEY
	{
		ret = tTKEY
		goto yystate0
	}
yyrule66: // TSIG
	{
		ret = tTSIG
		goto yystate0
	}
yyrule67: // TXT
	{
		ret = tTXT
		goto yystate0
	}
yyrule68: // UID
	{
		ret = tUID
		goto yystate0
	}
yyrule69: // UINFO
	{
		ret = tUINFO
		goto yystate0
	}
yyrule70: // UNSPEC
	{
		ret = tUNSPEC
		goto yystate0
	}
yyrule71: // WKS
	{
		ret = tWKS
		goto yystate0
	}
yyrule72: // X25
	{
		ret = tX25
		goto yystate0
	}
yyrule73: // {ipv4}
	{

		ip := net.ParseIP(string(l.buf))
		if ip == nil {
			l.Error(fmt.Sprintf("invalid IP %q", l.buf))
		}
		lval.ip = ip
		return tIPV4
	}
yyrule74: // {ipv6}
	{

		ip := net.ParseIP(string(l.buf))
		if ip == nil {
			l.Error(fmt.Sprintf("invalid IP %q", l.buf))
		}
		lval.ip = ip
		return tIPV6
	}
yyrule75: // [0-9A-V=]+
	{

		ret = tBASE32EXT
		goto yystate0
	}
yyrule76: // [A-Za-z0-9+/=]+
	{

		ret = tBASE64
		goto yystate0
	}
yyrule77: // [0-9a-fA-F]+
	{

		var err error
		lval.data, err = hex.DecodeString(string(l.buf))
		if err != nil {
			l.Error("expected hex string")
		}
		ret = tHEX
		goto yystate0
	}
yyrule78: // -
	{

		lval.data = nil
		ret = tHEX
		goto yystate0
	}
		panic("unreachable")

		goto yyabort // silence unused label error

yyabort: // no lexem recognized
	// no pattern recognized
	if len(l.buf) == 0 {
		ret = int(c)
		l.getc(0)
		return
	}

	return unicode.ReplacementChar
}
